{
 "title": "Virtual Classroom",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\", namespace=\"$namespace\"}[5m])) by (grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Average requests per seconds",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\",namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total number of requests",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\",namespace=\"$namespace\"}[$__range])) by (grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Rate of \"OK\" status",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\", grpc_server_status=\"OK\", namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_method) / sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Error rate by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\", grpc_server_status!~\"OK\", namespace=\"$namespace\"}[5m])) by (grpc_server_status, grpc_server_method) / sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\", namespace=\"$namespace\"}[5m])) by (grpc_server_status, grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}: {{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "gRPC Response status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_status) / ignoring(grpc_server_status) group_left sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"bob|virtualclassroom\", grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method, db))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_name=~\"bob|virtualclassroom\",grpc_server_method=~\"manabie.bob.Student/GetStudentProfile|bob.v1.LessonModifierService/GetLiveLessonState|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|manabie.bob.Course/RetrieveLiveLesson|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|bob.v1.ClassModifierService/JoinLesson|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassReaderService/ListStudentsByLesson\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method, db))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",pod=~\"^(bob|virtualclassroom).+\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(bob|virtualclassroom).+\",namespace=\"$namespace\",unit=\"byte\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob|virtualclassroom).+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(bob|virtualclassroom).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob|virtualclassroom).+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"^(bob|virtualclassroom).+\",namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(bob|virtualclassroom).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob|virtualclassroom).+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(bob|virtualclassroom).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob|virtualclassroom).+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"^(bob|virtualclassroom).+\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Business statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Number of active rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "backend_virtual_classroom_active_rooms_total{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\"}",
     "legendFormat": "active rooms"
    }
   ]
  },
  {
   "title": "Number of rooms with \"update\" room state requests",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"10\"}[$__range]))\n ",
     "legendFormat": "Number of rooms have from 0 to 10 request"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\",app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"20\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"10\"}[$__range])))\n ",
     "legendFormat": "(10, 20]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"50\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"20\"}[$__range])))\n ",
     "legendFormat": "(20, 50]"
    },
    {
     "expr": "\n(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"100\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"50\"}[$__range])))\n ",
     "legendFormat": "(50, 100]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"200\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\",app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"100\"}[$__range])))\n ",
     "legendFormat": "(100, 200]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"200\"}[$__range])))\n ",
     "legendFormat": "(200, 500]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_handled_total_count{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range]))\n",
     "legendFormat": "> 500"
    }
   ]
  },
  {
   "title": "Number of rooms with \"get\" room state requests",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"100\"}[$__range]))\n ",
     "legendFormat": "Number of rooms have from 0 to 100 request"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"100\"}[$__range])))",
     "legendFormat": "(100, 500]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"1000\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range]))) ",
     "legendFormat": "(500, 1000]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"3000\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"1000\"}[$__range])))",
     "legendFormat": "(1000, 3000]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"5000\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"3000\"}[$__range]))) ",
     "legendFormat": "(3000, 5000]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"7000\"}[$__range])) \n- sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"5000\"}[$__range])))",
     "legendFormat": "(5000, 7000]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_handled_total_count{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"7000\"}[$__range]))",
     "legendFormat": "> 7000"
    }
   ]
  },
  {
   "title": "Number of rooms with total \"attendees\" who really joined",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"5\"}[$__range]))\n ",
     "legendFormat": "Number of rooms have from 0 to 5 attendees"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range])) - \nsum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"5\"}[$__range])))",
     "legendFormat": "(5, 10]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"15\"}[$__range])) \n- sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range])))",
     "legendFormat": "(10, 15]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range])) \n- sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"15\"}[$__range])))",
     "legendFormat": "(15, 20]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range])) \n- sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range])))",
     "legendFormat": "(20, 40]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_attendees_total_count{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\",}[$__range])) -\nsum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range]))",
     "legendFormat": "> 40"
    }
   ]
  },
  {
   "title": "Number of rooms with total real \"live time\"",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range]))",
     "legendFormat": "Number of rooms have real live time from 0 to 10 mins"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range])) - sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{ namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range])))",
     "legendFormat": "(10, 20]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range])) \n- sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range])))",
     "legendFormat": "(20, 40]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"60\"}[$__range])) \n- sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range]))) ",
     "legendFormat": "(40, 60]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"90\"}[$__range])) \n- sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"60\"}[$__range])))",
     "legendFormat": "(60, 90]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_total_real_live_time_minutes_count{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\"}[$__range])) -\nsum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\",app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"90\"}[$__range]))",
     "legendFormat": "> 90"
    }
   ]
  }
 ]
}