{
 "title": "J4 metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "UAT : staging, Staging : staging-2, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "scenario",
    "label": "Scenario",
    "query": {
     "query": "label_values(j4_spawned_workers{namespace=\"$namespace\"}, j4_scenario)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Completed HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": " sum(rate(opencensus_io_http_client_completed_count{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\"}[2m])) by (hasura_query)",
     "legendFormat": "{{ hasura_query }}"
    }
   ]
  },
  {
   "title": "J4 P95 HTTP latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_client_roundtrip_latency_bucket{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\"}[5m])) by (le,hasura_query)) ",
     "legendFormat": "{{hasura_query}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(opencensus_io_http_client_completed_count{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\",http_client_status!=\"200\"}[2m])) by (hasura_query)/sum(rate(opencensus_io_http_client_completed_count{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\"}[2m])) by (hasura_query)",
     "legendFormat": "{{hasura_query}}"
    }
   ]
  },
  { "title": "Grpc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Completed GRPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_client_completed_rpcs{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\"}[2m])) by (grpc_client_method)",
     "legendFormat": "{{ grpc_client_method }}"
    }
   ]
  },
  {
   "title": "Error rate by GRPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_client_completed_rpcs{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\",grpc_client_status!=\"OK\"}[2m])) by (grpc_client_method)/sum(rate(grpc_io_client_completed_rpcs{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\"}[2m])) by (grpc_client_method)",
     "legendFormat": "{{ grpc_client_method }}"
    }
   ]
  },
  {
   "title": "Received bytes per GRPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_client_received_bytes_per_rpc_sum{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\"}[2m])) by (grpc_client_method,scenario)\n",
     "legendFormat": "{{grpc_client_method}}"
    }
   ]
  },
  {
   "title": "P95 GRPC latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{namespace=\"$namespace\",grpc_client_method!~\".+/SubscribeV2\",j4_scenario=~\"$scenario.*\"}[5m])) by (le,grpc_client_method))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Scenario error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(j4_worker_execution{namespace=\"$namespace\",j4_haserror=\"true\"}[2m])) by (j4_scenario) / sum(rate(j4_worker_execution{namespace=\"$namespace\"}[2m]))  by (j4_scenario)",
     "legendFormat": "{{j4_scenario}}"
    }
   ]
  },
  {
   "title": "J4 Spawned workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(j4_spawned_workers{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\",j4_worker_status=\"init\"}) by (j4_scenario)",
     "legendFormat": "{{ j4_scenario }} Init"
    },
    {
     "expr": "sum(j4_spawned_workers{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\",j4_worker_status=\"running\"}) by (j4_scenario)",
     "legendFormat": "{{ j4_scenario }} Running"
    }
   ]
  },
  {
   "title": "J4 Spawned workers by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(j4_spawned_workers{namespace=\"$namespace\",j4_scenario=~\"$scenario.*\",j4_worker_status=\"init\"}) by (j4_scenario,pod)",
     "legendFormat": "{{ pod }} {{ j4_scenario }}"
    }
   ]
  },
  {
   "title": "Pod memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",container=\"j4-all-in-one\",namespace=\"$namespace\",pod=~\"^j4-all-in-one.+\"}) by (container,pod)",
     "legendFormat": "{{ container }} {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\",pod=~\"^j4-all-in-one.*\"}[5m])) by(pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"$namespace\",pod=~\"j4-all-in-one-.*\"}) by (pod)",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "RAFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "J4 Quorum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(j4_raft_quorum == 1) by (j4_raft_candidate)",
       "legendFormat": "{{ j4_raft_candidate }}"
      }
     ]
    },
    {
     "title": "Raft peers by pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(j4_raft_peers{namespace=\"$namespace\"}) by(pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}