// Code generated by mockery v2.10.0. DO NOT EDIT.

package mock_alert

import (
	alert "github.com/manabie-com/backend/internal/golibs/alert"
	mock "github.com/stretchr/testify/mock"
)
// SlackFactory is an autogenerated mock type for the SlackFactory type
type SlackFactory struct {
	mock.Mock
}

// Send provides a mock function with given fields: payload
func (_m *SlackFactory) Send(payload alert.Payload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(alert.Payload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendByte provides a mock function with given fields: payload
func (_m *SlackFactory) SendByte(payload []byte) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IAttachment is an autogenerated mock type for the IAttachment type
type IAttachment struct {
	mock.Mock
}

// AddDetailInfo provides a mock function with given fields: missingNumber
func (_m *IAttachment) AddDetailInfo(missingNumber int) {
	_m.Called(missingNumber)
}

// AddField provides a mock function with given fields: field
func (_m *IAttachment) AddField(field alert.Field) {
	_m.Called(field)
}

// AddSourceInfo provides a mock function with given fields: partnerName, env
func (_m *IAttachment) AddSourceInfo(partnerName string, env string) {
	_m.Called(partnerName, env)
}
