// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
	"github.com/manabie-com/backend/internal/lessonmgmt/modules/lesson/domain"
)

type MockLessonClassroomRepo struct {
	mock.Mock
}

func (r *MockLessonClassroomRepo) GetLessonClassroomsWithNamesByLessonIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 []string) (map[string]domain.LessonClassrooms, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(map[string]domain.LessonClassrooms), args.Error(1)
}
