ALTER TABLE ONLY public.conversation_events DROP CONSTRAINT IF EXISTS event_type_check;

ALTER TABLE public.conversation_events
    ADD CONSTRAINT event_type_check CHECK (event_type = ANY (ARRAY[
        'CONVERSATION_EVENT_TYPE_STUDENT_HAND_EVENT'::text,
        'CONVERSATION_EVENT_TYPE_ALLOW_PROHIBIT_TO_SPEAK'::text,
        'CONVERSATION_EVENT_TYPE_ACCEPT_DECLINE_TO_SPEAK'::text,
        'CONVERSATION_EVENT_TYPE_TEACHER_CREATE_POOL'::text,
        'CONVERSATION_EVENT_TYPE_STUDENT_ANSWER_POOL'::text,
        'CONVERSATION_EVENT_TYPE_ALLOW_PROHIBIT_TO_SHOW_CAMERA'::text
]));

ALTER TABLE ONLY public.conversation_events DROP CONSTRAINT IF EXISTS status_check;

ALTER TABLE public.conversation_events
    ADD CONSTRAINT status_check CHECK (status = ANY (ARRAY[
        'CONVERSATION_EVENT_STATUS_STUDENT_RAISE_HAND'::text,
        'CONVERSATION_EVENT_STATUS_STUDENT_PUT_HAND_DOWN'::text,
        'CONVERSATION_EVENT_STATUS_STUDENT_ALLOW_TO_SPEAK'::text,
        'CONVERSATION_EVENT_STATUS_STUDENT_PROHIBIT_TO_SPEAK'::text,
        'CONVERSATION_EVENT_STATUS_STUDENT_ACCEPT_TO_SPEAK'::text,
        'CONVERSATION_EVENT_STATUS_STUDENT_DECLINE_TO_SPEAK'::text,
        'CONVERSATION_EVENT_STATUS_POOL_OPEN'::text,
        'CONVERSATION_EVENT_STATUS_POOL_CLOSE'::text,
        'CONVERSATION_EVENT_STATUS_ALLOW_ALL_STUDENT_TO_SPEAK'::text,
        'CONVERSATION_EVENT_STATUS_PROHIBIT_ALL_STUDENT_TO_SPEAK'::text,
        'CONVERSATION_EVENT_STATUS_ALLOW_STUDENT_TO_SHOW_CAMERA'::text,
        'CONVERSATION_EVENT_STATUS_PROHIBIT_STUDENT_TO_SHOW_CAMERA'::text
]));
