ALTER TABLE ONLY public.conversation_events DROP CONSTRAINT IF EXISTS event_type_check;

ALTER TABLE public.conversation_events
    ADD CONSTRAINT event_type_check CHECK (event_type = ANY (ARRAY[
        'CONVERSATION_EVENT_TYPE_STUDENT_HAND_EVENT',
        'CONVERSATION_EVENT_TYPE_ALLOW_PROHIBIT_TO_SPEAK',
        'CONVERSATION_EVENT_TYPE_ACCEPT_DECLINE_TO_SPEAK',
        'CONVERSATION_EVENT_TYPE_TEACHER_CREATE_POOL',
        'CONVERSATION_EVENT_TYPE_STUDENT_ANSWER_POOL',
        'CONVERSATION_EVENT_TYPE_ALLOW_PROHIBIT_TO_SHOW_CAMERA',
        'CONVERSATION_EVENT_TYPE_HAND_OFF_STUDENT'
]::text[]));

ALTER TABLE ONLY public.conversation_events DROP CONSTRAINT IF EXISTS status_check;

ALTER TABLE public.conversation_events
    ADD CONSTRAINT status_check CHECK (status = ANY (ARRAY[
        'CONVERSATION_EVENT_STATUS_STUDENT_RAISE_HAND',
        'CONVERSATION_EVENT_STATUS_STUDENT_PUT_HAND_DOWN',
        'CONVERSATION_EVENT_STATUS_STUDENT_ALLOW_TO_SPEAK',
        'CONVERSATION_EVENT_STATUS_STUDENT_PROHIBIT_TO_SPEAK',
        'CONVERSATION_EVENT_STATUS_STUDENT_ACCEPT_TO_SPEAK',
        'CONVERSATION_EVENT_STATUS_STUDENT_DECLINE_TO_SPEAK',
        'CONVERSATION_EVENT_STATUS_POOL_OPEN',
        'CONVERSATION_EVENT_STATUS_POOL_CLOSE',
        'CONVERSATION_EVENT_STATUS_ALLOW_ALL_STUDENT_TO_SPEAK',
        'CONVERSATION_EVENT_STATUS_PROHIBIT_ALL_STUDENT_TO_SPEAK',
        'CONVERSATION_EVENT_STATUS_ALLOW_STUDENT_TO_SHOW_CAMERA',
        'CONVERSATION_EVENT_STATUS_PROHIBIT_STUDENT_TO_SHOW_CAMERA',
		'CONVERSATION_EVENT_STATUS_HAND_OFF_ALL_STUDENT',
		'CONVERSATION_EVENT_STATUS_HAND_OFF_STUDENT'
]::text[]));
