ALTER TABLE ONLY public.messages
    DROP CONSTRAINT IF EXISTS messages_type_check;

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_type_check CHECK ((type = ANY ('{MESSAGE_TYPE_TEXT,MESSAGE_TYPE_IMAGE,MESSAGE_TYPE_VIDEO,MESSAGE_TYPE_SYSTEM,MESSAGE_TYPE_BUTTON,MESSAGE_TYPE_COACH_AUTO,MESSAGE_TYPE_FILE}'::text[])))