ALTER TABLE IF EXISTS study_plan_items
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'STUDY_PLAN_ITEM_STATUS_ACTIVE'::TEXT,
ADD COLUMN IF NOT EXISTS school_date TIMESTAMP WITH TIME ZONE,
ADD CONSTRAINT status_check CHECK ((status = ANY (ARRAY['STUDY_PLAN_ITEM_STATUS_NONE'::text, 'STUDY_PLAN_ITEM_STATUS_ACTIVE'::text, 'STUDY_PLAN_ITEM_STATUS_ARCHIVED'::text])));
