// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: tom/v1/lesson_chat_reader.proto

package tpb

import (
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/manabie-com/backend/pkg/manabuf/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LiveLessonConversationMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string     `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Paging         *v1.Paging `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *LiveLessonConversationMessagesRequest) Reset() {
	*x = LiveLessonConversationMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveLessonConversationMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveLessonConversationMessagesRequest) ProtoMessage() {}

func (x *LiveLessonConversationMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveLessonConversationMessagesRequest.ProtoReflect.Descriptor instead.
func (*LiveLessonConversationMessagesRequest) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{0}
}

func (x *LiveLessonConversationMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *LiveLessonConversationMessagesRequest) GetPaging() *v1.Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type LiveLessonConversationMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*MessageResponse `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *LiveLessonConversationMessagesResponse) Reset() {
	*x = LiveLessonConversationMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveLessonConversationMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveLessonConversationMessagesResponse) ProtoMessage() {}

func (x *LiveLessonConversationMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveLessonConversationMessagesResponse.ProtoReflect.Descriptor instead.
func (*LiveLessonConversationMessagesResponse) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{1}
}

func (x *LiveLessonConversationMessagesResponse) GetMessages() []*MessageResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

type LiveLessonPrivateConversationMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string     `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Paging         *v1.Paging `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *LiveLessonPrivateConversationMessagesRequest) Reset() {
	*x = LiveLessonPrivateConversationMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveLessonPrivateConversationMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveLessonPrivateConversationMessagesRequest) ProtoMessage() {}

func (x *LiveLessonPrivateConversationMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveLessonPrivateConversationMessagesRequest.ProtoReflect.Descriptor instead.
func (*LiveLessonPrivateConversationMessagesRequest) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{2}
}

func (x *LiveLessonPrivateConversationMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *LiveLessonPrivateConversationMessagesRequest) GetPaging() *v1.Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type LiveLessonPrivateConversationMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*MessageResponse `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *LiveLessonPrivateConversationMessagesResponse) Reset() {
	*x = LiveLessonPrivateConversationMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveLessonPrivateConversationMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveLessonPrivateConversationMessagesResponse) ProtoMessage() {}

func (x *LiveLessonPrivateConversationMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveLessonPrivateConversationMessagesResponse.ProtoReflect.Descriptor instead.
func (*LiveLessonPrivateConversationMessagesResponse) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{3}
}

func (x *LiveLessonPrivateConversationMessagesResponse) GetMessages() []*MessageResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

type LiveLessonConversationDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LessonId string `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
}

func (x *LiveLessonConversationDetailRequest) Reset() {
	*x = LiveLessonConversationDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveLessonConversationDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveLessonConversationDetailRequest) ProtoMessage() {}

func (x *LiveLessonConversationDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveLessonConversationDetailRequest.ProtoReflect.Descriptor instead.
func (*LiveLessonConversationDetailRequest) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{4}
}

func (x *LiveLessonConversationDetailRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type LiveLessonConversationDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conversation *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
}

func (x *LiveLessonConversationDetailResponse) Reset() {
	*x = LiveLessonConversationDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveLessonConversationDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveLessonConversationDetailResponse) ProtoMessage() {}

func (x *LiveLessonConversationDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveLessonConversationDetailResponse.ProtoReflect.Descriptor instead.
func (*LiveLessonConversationDetailResponse) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{5}
}

func (x *LiveLessonConversationDetailResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type RefreshLiveLessonSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LessonId string `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
}

func (x *RefreshLiveLessonSessionRequest) Reset() {
	*x = RefreshLiveLessonSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshLiveLessonSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLiveLessonSessionRequest) ProtoMessage() {}

func (x *RefreshLiveLessonSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLiveLessonSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshLiveLessonSessionRequest) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshLiveLessonSessionRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type RefreshLiveLessonSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshLiveLessonSessionResponse) Reset() {
	*x = RefreshLiveLessonSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshLiveLessonSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLiveLessonSessionResponse) ProtoMessage() {}

func (x *RefreshLiveLessonSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tom_v1_lesson_chat_reader_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLiveLessonSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshLiveLessonSessionResponse) Descriptor() ([]byte, []int) {
	return file_tom_v1_lesson_chat_reader_proto_rawDescGZIP(), []int{7}
}

var File_tom_v1_lesson_chat_reader_proto protoreflect.FileDescriptor

var file_tom_v1_lesson_chat_reader_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x74, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x1a, 0x74, 0x6f, 0x6d, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7b, 0x0a, 0x25, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x5d, 0x0a, 0x26,
	0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x2c,
	0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x22, 0x64, 0x0a, 0x2d, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x42, 0x0a, 0x23, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x24, 0x4c, 0x69,
	0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x1f,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x20,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x9b, 0x04, 0x0a, 0x17, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x18,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x79, 0x0a, 0x1c, 0x4c,
	0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2b, 0x2e, 0x74, 0x6f,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7f, 0x0a, 0x1e, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2d, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x94, 0x01, 0x0a, 0x25, 0x4c, 0x69, 0x76, 0x65,
	0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x34, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4c,
	0x65, 0x73, 0x73, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x74, 0x6f, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e,
	0x61, 0x62, 0x69, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x6f, 0x6d,
	0x2f, 0x76, 0x31, 0x3b, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tom_v1_lesson_chat_reader_proto_rawDescOnce sync.Once
	file_tom_v1_lesson_chat_reader_proto_rawDescData = file_tom_v1_lesson_chat_reader_proto_rawDesc
)

func file_tom_v1_lesson_chat_reader_proto_rawDescGZIP() []byte {
	file_tom_v1_lesson_chat_reader_proto_rawDescOnce.Do(func() {
		file_tom_v1_lesson_chat_reader_proto_rawDescData = protoimpl.X.CompressGZIP(file_tom_v1_lesson_chat_reader_proto_rawDescData)
	})
	return file_tom_v1_lesson_chat_reader_proto_rawDescData
}

var file_tom_v1_lesson_chat_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tom_v1_lesson_chat_reader_proto_goTypes = []interface{}{
	(*LiveLessonConversationMessagesRequest)(nil),         // 0: tom.v1.LiveLessonConversationMessagesRequest
	(*LiveLessonConversationMessagesResponse)(nil),        // 1: tom.v1.LiveLessonConversationMessagesResponse
	(*LiveLessonPrivateConversationMessagesRequest)(nil),  // 2: tom.v1.LiveLessonPrivateConversationMessagesRequest
	(*LiveLessonPrivateConversationMessagesResponse)(nil), // 3: tom.v1.LiveLessonPrivateConversationMessagesResponse
	(*LiveLessonConversationDetailRequest)(nil),           // 4: tom.v1.LiveLessonConversationDetailRequest
	(*LiveLessonConversationDetailResponse)(nil),          // 5: tom.v1.LiveLessonConversationDetailResponse
	(*RefreshLiveLessonSessionRequest)(nil),               // 6: tom.v1.RefreshLiveLessonSessionRequest
	(*RefreshLiveLessonSessionResponse)(nil),              // 7: tom.v1.RefreshLiveLessonSessionResponse
	(*v1.Paging)(nil),                                     // 8: common.v1.Paging
	(*MessageResponse)(nil),                               // 9: tom.v1.MessageResponse
	(*Conversation)(nil),                                  // 10: tom.v1.Conversation
}
var file_tom_v1_lesson_chat_reader_proto_depIdxs = []int32{
	8,  // 0: tom.v1.LiveLessonConversationMessagesRequest.paging:type_name -> common.v1.Paging
	9,  // 1: tom.v1.LiveLessonConversationMessagesResponse.messages:type_name -> tom.v1.MessageResponse
	8,  // 2: tom.v1.LiveLessonPrivateConversationMessagesRequest.paging:type_name -> common.v1.Paging
	9,  // 3: tom.v1.LiveLessonPrivateConversationMessagesResponse.messages:type_name -> tom.v1.MessageResponse
	10, // 4: tom.v1.LiveLessonConversationDetailResponse.conversation:type_name -> tom.v1.Conversation
	6,  // 5: tom.v1.LessonChatReaderService.RefreshLiveLessonSession:input_type -> tom.v1.RefreshLiveLessonSessionRequest
	4,  // 6: tom.v1.LessonChatReaderService.LiveLessonConversationDetail:input_type -> tom.v1.LiveLessonConversationDetailRequest
	0,  // 7: tom.v1.LessonChatReaderService.LiveLessonConversationMessages:input_type -> tom.v1.LiveLessonConversationMessagesRequest
	2,  // 8: tom.v1.LessonChatReaderService.LiveLessonPrivateConversationMessages:input_type -> tom.v1.LiveLessonPrivateConversationMessagesRequest
	7,  // 9: tom.v1.LessonChatReaderService.RefreshLiveLessonSession:output_type -> tom.v1.RefreshLiveLessonSessionResponse
	5,  // 10: tom.v1.LessonChatReaderService.LiveLessonConversationDetail:output_type -> tom.v1.LiveLessonConversationDetailResponse
	1,  // 11: tom.v1.LessonChatReaderService.LiveLessonConversationMessages:output_type -> tom.v1.LiveLessonConversationMessagesResponse
	3,  // 12: tom.v1.LessonChatReaderService.LiveLessonPrivateConversationMessages:output_type -> tom.v1.LiveLessonPrivateConversationMessagesResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tom_v1_lesson_chat_reader_proto_init() }
func file_tom_v1_lesson_chat_reader_proto_init() {
	if File_tom_v1_lesson_chat_reader_proto != nil {
		return
	}
	file_tom_v1_conversations_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tom_v1_lesson_chat_reader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveLessonConversationMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tom_v1_lesson_chat_reader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveLessonConversationMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tom_v1_lesson_chat_reader_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveLessonPrivateConversationMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tom_v1_lesson_chat_reader_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveLessonPrivateConversationMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tom_v1_lesson_chat_reader_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveLessonConversationDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tom_v1_lesson_chat_reader_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveLessonConversationDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tom_v1_lesson_chat_reader_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshLiveLessonSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tom_v1_lesson_chat_reader_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshLiveLessonSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tom_v1_lesson_chat_reader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tom_v1_lesson_chat_reader_proto_goTypes,
		DependencyIndexes: file_tom_v1_lesson_chat_reader_proto_depIdxs,
		MessageInfos:      file_tom_v1_lesson_chat_reader_proto_msgTypes,
	}.Build()
	File_tom_v1_lesson_chat_reader_proto = out.File
	file_tom_v1_lesson_chat_reader_proto_rawDesc = nil
	file_tom_v1_lesson_chat_reader_proto_goTypes = nil
	file_tom_v1_lesson_chat_reader_proto_depIdxs = nil
}
