// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: eureka/v2/learning_material.proto

package epb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UpdatePublishStatusLearningMaterialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublishStatuses []*UpdatePublishStatusLearningMaterialsRequest_PublishStatus `protobuf:"bytes,1,rep,name=publish_statuses,json=publishStatuses,proto3" json:"publish_statuses,omitempty"`
}

func (x *UpdatePublishStatusLearningMaterialsRequest) Reset() {
	*x = UpdatePublishStatusLearningMaterialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eureka_v2_learning_material_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePublishStatusLearningMaterialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePublishStatusLearningMaterialsRequest) ProtoMessage() {}

func (x *UpdatePublishStatusLearningMaterialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eureka_v2_learning_material_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePublishStatusLearningMaterialsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePublishStatusLearningMaterialsRequest) Descriptor() ([]byte, []int) {
	return file_eureka_v2_learning_material_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePublishStatusLearningMaterialsRequest) GetPublishStatuses() []*UpdatePublishStatusLearningMaterialsRequest_PublishStatus {
	if x != nil {
		return x.PublishStatuses
	}
	return nil
}

type UpdatePublishStatusLearningMaterialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePublishStatusLearningMaterialsResponse) Reset() {
	*x = UpdatePublishStatusLearningMaterialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eureka_v2_learning_material_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePublishStatusLearningMaterialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePublishStatusLearningMaterialsResponse) ProtoMessage() {}

func (x *UpdatePublishStatusLearningMaterialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eureka_v2_learning_material_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePublishStatusLearningMaterialsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePublishStatusLearningMaterialsResponse) Descriptor() ([]byte, []int) {
	return file_eureka_v2_learning_material_proto_rawDescGZIP(), []int{1}
}

type ListLearningMaterialInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningMaterialIds []string `protobuf:"bytes,1,rep,name=learning_material_ids,json=learningMaterialIds,proto3" json:"learning_material_ids,omitempty"`
}

func (x *ListLearningMaterialInfoRequest) Reset() {
	*x = ListLearningMaterialInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eureka_v2_learning_material_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLearningMaterialInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearningMaterialInfoRequest) ProtoMessage() {}

func (x *ListLearningMaterialInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eureka_v2_learning_material_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearningMaterialInfoRequest.ProtoReflect.Descriptor instead.
func (*ListLearningMaterialInfoRequest) Descriptor() ([]byte, []int) {
	return file_eureka_v2_learning_material_proto_rawDescGZIP(), []int{2}
}

func (x *ListLearningMaterialInfoRequest) GetLearningMaterialIds() []string {
	if x != nil {
		return x.LearningMaterialIds
	}
	return nil
}

type ListLearningMaterialInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningMaterials []*ListLearningMaterialInfoResponse_LearningMaterialInfo `protobuf:"bytes,1,rep,name=learning_materials,json=learningMaterials,proto3" json:"learning_materials,omitempty"`
}

func (x *ListLearningMaterialInfoResponse) Reset() {
	*x = ListLearningMaterialInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eureka_v2_learning_material_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLearningMaterialInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearningMaterialInfoResponse) ProtoMessage() {}

func (x *ListLearningMaterialInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eureka_v2_learning_material_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearningMaterialInfoResponse.ProtoReflect.Descriptor instead.
func (*ListLearningMaterialInfoResponse) Descriptor() ([]byte, []int) {
	return file_eureka_v2_learning_material_proto_rawDescGZIP(), []int{3}
}

func (x *ListLearningMaterialInfoResponse) GetLearningMaterials() []*ListLearningMaterialInfoResponse_LearningMaterialInfo {
	if x != nil {
		return x.LearningMaterials
	}
	return nil
}

type UpdatePublishStatusLearningMaterialsRequest_PublishStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningMaterialId string `protobuf:"bytes,1,opt,name=learning_material_id,json=learningMaterialId,proto3" json:"learning_material_id,omitempty"`
	IsPublished        bool   `protobuf:"varint,2,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
}

func (x *UpdatePublishStatusLearningMaterialsRequest_PublishStatus) Reset() {
	*x = UpdatePublishStatusLearningMaterialsRequest_PublishStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eureka_v2_learning_material_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePublishStatusLearningMaterialsRequest_PublishStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePublishStatusLearningMaterialsRequest_PublishStatus) ProtoMessage() {}

func (x *UpdatePublishStatusLearningMaterialsRequest_PublishStatus) ProtoReflect() protoreflect.Message {
	mi := &file_eureka_v2_learning_material_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePublishStatusLearningMaterialsRequest_PublishStatus.ProtoReflect.Descriptor instead.
func (*UpdatePublishStatusLearningMaterialsRequest_PublishStatus) Descriptor() ([]byte, []int) {
	return file_eureka_v2_learning_material_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UpdatePublishStatusLearningMaterialsRequest_PublishStatus) GetLearningMaterialId() string {
	if x != nil {
		return x.LearningMaterialId
	}
	return ""
}

func (x *UpdatePublishStatusLearningMaterialsRequest_PublishStatus) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type ListLearningMaterialInfoResponse_LearningMaterialInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningMaterialId   string `protobuf:"bytes,1,opt,name=learning_material_id,json=learningMaterialId,proto3" json:"learning_material_id,omitempty"`
	LearningMaterialName string `protobuf:"bytes,2,opt,name=learning_material_name,json=learningMaterialName,proto3" json:"learning_material_name,omitempty"`
	ChapterId            string `protobuf:"bytes,4,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	ChapterName          string `protobuf:"bytes,5,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	TopicId              string `protobuf:"bytes,6,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	TopicName            string `protobuf:"bytes,7,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) Reset() {
	*x = ListLearningMaterialInfoResponse_LearningMaterialInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eureka_v2_learning_material_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearningMaterialInfoResponse_LearningMaterialInfo) ProtoMessage() {}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_eureka_v2_learning_material_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearningMaterialInfoResponse_LearningMaterialInfo.ProtoReflect.Descriptor instead.
func (*ListLearningMaterialInfoResponse_LearningMaterialInfo) Descriptor() ([]byte, []int) {
	return file_eureka_v2_learning_material_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) GetLearningMaterialId() string {
	if x != nil {
		return x.LearningMaterialId
	}
	return ""
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) GetLearningMaterialName() string {
	if x != nil {
		return x.LearningMaterialName
	}
	return ""
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *ListLearningMaterialInfoResponse_LearningMaterialInfo) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

var File_eureka_v2_learning_material_proto protoreflect.FileDescriptor

var file_eureka_v2_learning_material_proto_rawDesc = []byte{
	0x0a, 0x21, 0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2f, 0x76, 0x32, 0x2f, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2e, 0x76, 0x32, 0x22, 0x84,
	0x02, 0x0a, 0x2b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x6f,
	0x0a, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x65, 0x75, 0x72, 0x65, 0x6b,
	0x61, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x1a,
	0x64, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x30, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x22, 0x2e, 0x0a, 0x2c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x90, 0x03, 0x0a,
	0x20, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6f, 0x0a, 0x12, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x40, 0x2e,
	0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x11, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x73, 0x1a, 0xfa, 0x01, 0x0a, 0x14, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x14, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x34, 0x0a,
	0x16, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x32,
	0xa8, 0x02, 0x0a, 0x17, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x97, 0x01, 0x0a, 0x24,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x73, 0x12, 0x36, 0x2e, 0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2e, 0x76, 0x32,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x65,
	0x75, 0x72, 0x65, 0x6b, 0x61, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x2a, 0x2e, 0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x69, 0x65,
	0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x75, 0x72, 0x65, 0x6b, 0x61, 0x2f,
	0x76, 0x32, 0x3b, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eureka_v2_learning_material_proto_rawDescOnce sync.Once
	file_eureka_v2_learning_material_proto_rawDescData = file_eureka_v2_learning_material_proto_rawDesc
)

func file_eureka_v2_learning_material_proto_rawDescGZIP() []byte {
	file_eureka_v2_learning_material_proto_rawDescOnce.Do(func() {
		file_eureka_v2_learning_material_proto_rawDescData = protoimpl.X.CompressGZIP(file_eureka_v2_learning_material_proto_rawDescData)
	})
	return file_eureka_v2_learning_material_proto_rawDescData
}

var file_eureka_v2_learning_material_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_eureka_v2_learning_material_proto_goTypes = []interface{}{
	(*UpdatePublishStatusLearningMaterialsRequest)(nil),               // 0: eureka.v2.UpdatePublishStatusLearningMaterialsRequest
	(*UpdatePublishStatusLearningMaterialsResponse)(nil),              // 1: eureka.v2.UpdatePublishStatusLearningMaterialsResponse
	(*ListLearningMaterialInfoRequest)(nil),                           // 2: eureka.v2.ListLearningMaterialInfoRequest
	(*ListLearningMaterialInfoResponse)(nil),                          // 3: eureka.v2.ListLearningMaterialInfoResponse
	(*UpdatePublishStatusLearningMaterialsRequest_PublishStatus)(nil), // 4: eureka.v2.UpdatePublishStatusLearningMaterialsRequest.PublishStatus
	(*ListLearningMaterialInfoResponse_LearningMaterialInfo)(nil),     // 5: eureka.v2.ListLearningMaterialInfoResponse.LearningMaterialInfo
}
var file_eureka_v2_learning_material_proto_depIdxs = []int32{
	4, // 0: eureka.v2.UpdatePublishStatusLearningMaterialsRequest.publish_statuses:type_name -> eureka.v2.UpdatePublishStatusLearningMaterialsRequest.PublishStatus
	5, // 1: eureka.v2.ListLearningMaterialInfoResponse.learning_materials:type_name -> eureka.v2.ListLearningMaterialInfoResponse.LearningMaterialInfo
	0, // 2: eureka.v2.LearningMaterialService.UpdatePublishStatusLearningMaterials:input_type -> eureka.v2.UpdatePublishStatusLearningMaterialsRequest
	2, // 3: eureka.v2.LearningMaterialService.ListLearningMaterialInfo:input_type -> eureka.v2.ListLearningMaterialInfoRequest
	1, // 4: eureka.v2.LearningMaterialService.UpdatePublishStatusLearningMaterials:output_type -> eureka.v2.UpdatePublishStatusLearningMaterialsResponse
	3, // 5: eureka.v2.LearningMaterialService.ListLearningMaterialInfo:output_type -> eureka.v2.ListLearningMaterialInfoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eureka_v2_learning_material_proto_init() }
func file_eureka_v2_learning_material_proto_init() {
	if File_eureka_v2_learning_material_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eureka_v2_learning_material_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePublishStatusLearningMaterialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eureka_v2_learning_material_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePublishStatusLearningMaterialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eureka_v2_learning_material_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLearningMaterialInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eureka_v2_learning_material_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLearningMaterialInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eureka_v2_learning_material_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePublishStatusLearningMaterialsRequest_PublishStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eureka_v2_learning_material_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLearningMaterialInfoResponse_LearningMaterialInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eureka_v2_learning_material_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eureka_v2_learning_material_proto_goTypes,
		DependencyIndexes: file_eureka_v2_learning_material_proto_depIdxs,
		MessageInfos:      file_eureka_v2_learning_material_proto_msgTypes,
	}.Build()
	File_eureka_v2_learning_material_proto = out.File
	file_eureka_v2_learning_material_proto_rawDesc = nil
	file_eureka_v2_learning_material_proto_goTypes = nil
	file_eureka_v2_learning_material_proto_depIdxs = nil
}
