{
 "title": "Unleash Dashboard using Thanos",
 "description": "Unleash Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, Manabie : manabie, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(feature_toggles_total{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(feature_toggles_total{gke_cluster=\"$cluster\", namespace=~\"$namespace\"}, app_kubernetes_io_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of feature toggles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(feature_toggles_total{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(users_total{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Number of projects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(projects_total{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Current free connections in DB pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(db_pool_free{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Current connections in use in DB pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(db_pool_used{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Number of acquiring are waiting for a resource to be released in DB pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(db_pool_pending_acquires{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Number of asynchronous create calls are running in DB pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(db_pool_pending_creates{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Maximum DB pool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(db_pool_max{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Minimum DB pool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(db_pool_min{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_name=~\"$server\"}) by (app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  }
 ]
}