SET 'auto.offset.reset' = 'earliest';

CREATE STREAM IF NOT EXISTS BANK_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.invoicemgmt.bank', value_format='AVRO');

CREATE STREAM IF NOT EXISTS BANK_STREAM_FORMATTED_V1
    AS SELECT
        BANK_STREAM_ORIGIN_V1.AFTER->BANK_ID AS KEY,
        AS_VALUE(BANK_STREAM_ORIGIN_V1.AFTER->BANK_ID) AS BANK_ID,
        BANK_STREAM_ORIGIN_V1.AFTER->BANK_CODE AS BANK_CODE,
        BANK_STREAM_ORIGIN_V1.AFTER->BANK_NAME AS BANK_NAME,
        BANK_STREAM_ORIGIN_V1.AFTER->BANK_NAME_PHONETIC AS BANK_NAME_PHONETIC,
        BANK_STREAM_ORIGIN_V1.AFTER->IS_ARCHIVED AS BANK_IS_ARCHIVED,
        BANK_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS BANK_CREATED_AT,
        BANK_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS BANK_UPDATED_AT,
        BANK_STREAM_ORIGIN_V1.AFTER->DELETED_AT AS BANK_DELETED_AT
    FROM BANK_STREAM_ORIGIN_V1
    WHERE BANK_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY BANK_STREAM_ORIGIN_V1.AFTER->BANK_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS BANK_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}BANK_STREAM_FORMATTED_V1', value_format='AVRO');
