CREATE STREAM IF NOT EXISTS TS_LESSON
AS SELECT
    TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED.LESSON_ID AS KEY,
    AS_VALUE(TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED.LESSON_ID) AS LESSON_ID,
    TIMESHEET_TIMESHEET_TABLE.KEY AS TS_KEY,
    AS_VALUE(TIMESHEET_TIMESHEET_TABLE.KEY) AS TIMESHEET_ID,
    TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED.FLAG_ON AS FLAG_ON,
    TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED.CREATED_AT AS TIMESHEET_LESSON_HOUR_CREATED_AT,
    TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED.UPDATED_AT AS TIMESHEET_LESSON_HOUR_UPDATED_AT,
    TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED.DELETED_AT AS TIMESHEET_LESSON_HOUR_DELETED_AT,
    TIMESHEET_TIMESHEET_TABLE.STAFF_ID AS STAFF_ID,
    TIMESHEET_TIMESHEET_TABLE.TIMESHEET_STATUS AS TIMESHEET_STATUS,
    TIMESHEET_TIMESHEET_TABLE.TIMESHEET_DATE AS TIMESHEET_DATE,
    TIMESHEET_TIMESHEET_TABLE.REMARK AS TIMESHEET_REMARK,
    TIMESHEET_TIMESHEET_TABLE.LOCATION_ID AS LOCATION_ID,
    TIMESHEET_TIMESHEET_TABLE.CREATED_AT AS TIMESHEET_CREATED_AT,
    TIMESHEET_TIMESHEET_TABLE.UPDATED_AT AS TIMESHEET_UPDATED_AT,
    TIMESHEET_TIMESHEET_TABLE.DELETED_AT AS TIMESHEET_DELETED_AT
FROM TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED
JOIN TIMESHEET_TIMESHEET_TABLE
ON TIMESHEET_TIMESHEET_LESSON_HOURS_FORMATTED.TIMESHEET_ID = TIMESHEET_TIMESHEET_TABLE.KEY;