SET 'auto.offset.reset' = 'earliest';

CREATE STREAM IF NOT EXISTS MATERIAL_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.fatima.material', value_format='AVRO');

CREATE STREAM IF NOT EXISTS MATERIAL_STREAM_FORMATTED_V1
    AS SELECT
        MATERIAL_STREAM_ORIGIN_V1.AFTER->MATERIAL_ID AS KEY,
        AS_VALUE(MATERIAL_STREAM_ORIGIN_V1.AFTER->MATERIAL_ID) AS MATERIAL_ID,
        MATERIAL_STREAM_ORIGIN_V1.AFTER->MATERIAL_TYPE AS MATERIAL_TYPE,
        MATERIAL_STREAM_ORIGIN_V1.AFTER->CUSTOM_BILLING_DATE AS CUSTOM_BILLING_DATE,
        CAST(NULL AS VARCHAR) AS MATERIAL_CREATED_AT,
        CAST(NULL AS VARCHAR) AS MATERIAL_UPDATED_AT,
        CAST(NULL AS VARCHAR) AS MATERIAL_DELETED_AT
    FROM MATERIAL_STREAM_ORIGIN_V1
    WHERE MATERIAL_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY AFTER->MATERIAL_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS MATERIAL_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}MATERIAL_STREAM_FORMATTED_V1', value_format='AVRO');

CREATE STREAM IF NOT EXISTS PRODUCT_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.fatima.product', value_format='AVRO');

CREATE STREAM IF NOT EXISTS PRODUCT_STREAM_FORMATTED_V1
    AS SELECT
        PRODUCT_STREAM_ORIGIN_V1.AFTER->PRODUCT_ID AS KEY,
        AS_VALUE(PRODUCT_STREAM_ORIGIN_V1.AFTER->PRODUCT_ID) AS PRODUCT_ID,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->NAME AS NAME,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->PRODUCT_TYPE AS PRODUCT_TYPE,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->TAX_ID AS TAX_ID,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->AVAILABLE_FROM AS AVAILABLE_FROM,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->AVAILABLE_UNTIL AS AVAILABLE_UNTIL,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->REMARKS AS REMARKS,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->CUSTOM_BILLING_PERIOD AS CUSTOM_BILLING_PERIOD,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->DISABLE_PRO_RATING_FLAG AS DISABLE_PRO_RATING_FLAG,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->BILLING_SCHEDULE_ID AS BILLING_SCHEDULE_ID,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->IS_ARCHIVED AS IS_ARCHIVED,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->IS_UNIQUE AS IS_UNIQUE,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS PRODUCT_CREATED_AT,
        PRODUCT_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS PRODUCT_UPDATED_AT,
        CAST(NULL AS VARCHAR) AS PRODUCT_DELETED_AT
    FROM PRODUCT_STREAM_ORIGIN_V1
    WHERE PRODUCT_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY AFTER->PRODUCT_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS PRODUCT_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}PRODUCT_STREAM_FORMATTED_V1', value_format='AVRO');


-- needed join table here
CREATE TABLE IF NOT EXISTS MATERIAL_PUBLIC_INFO_V1
AS SELECT
    MATERIAL_TABLE_FORMATTED_V1.KEY AS MATERIAL_ID,
    MATERIAL_TABLE_FORMATTED_V1.MATERIAL_TYPE AS MATERIAL_TYPE,
    MATERIAL_TABLE_FORMATTED_V1.CUSTOM_BILLING_DATE AS CUSTOM_BILLING_DATE,
    MATERIAL_TABLE_FORMATTED_V1.MATERIAL_CREATED_AT AS MATERIAL_CREATED_AT,
    MATERIAL_TABLE_FORMATTED_V1.MATERIAL_UPDATED_AT AS MATERIAL_UPDATED_AT,
    MATERIAL_TABLE_FORMATTED_V1.MATERIAL_DELETED_AT AS MATERIAL_DELETED_AT,
    AS_VALUE(PRODUCT_TABLE_FORMATTED_V1.KEY) AS PRODUCT_ID,
    PRODUCT_TABLE_FORMATTED_V1.NAME AS NAME,
    PRODUCT_TABLE_FORMATTED_V1.PRODUCT_TYPE AS PRODUCT_TYPE,
    PRODUCT_TABLE_FORMATTED_V1.TAX_ID AS TAX_ID,
    PRODUCT_TABLE_FORMATTED_V1.AVAILABLE_FROM AS AVAILABLE_FROM,
    PRODUCT_TABLE_FORMATTED_V1.AVAILABLE_UNTIL AS AVAILABLE_UNTIL,
    PRODUCT_TABLE_FORMATTED_V1.REMARKS AS REMARKS,
    PRODUCT_TABLE_FORMATTED_V1.CUSTOM_BILLING_PERIOD AS CUSTOM_BILLING_PERIOD,
    PRODUCT_TABLE_FORMATTED_V1.BILLING_SCHEDULE_ID AS BILLING_SCHEDULE_ID,
    PRODUCT_TABLE_FORMATTED_V1.DISABLE_PRO_RATING_FLAG AS DISABLE_PRO_RATING_FLAG,
    PRODUCT_TABLE_FORMATTED_V1.IS_ARCHIVED AS IS_ARCHIVED,
    PRODUCT_TABLE_FORMATTED_V1.IS_UNIQUE AS IS_UNIQUE,
    PRODUCT_TABLE_FORMATTED_V1.PRODUCT_CREATED_AT AS PRODUCT_CREATED_AT,
    PRODUCT_TABLE_FORMATTED_V1.PRODUCT_UPDATED_AT AS PRODUCT_UPDATED_AT,
    PRODUCT_TABLE_FORMATTED_V1.PRODUCT_DELETED_AT AS PRODUCT_DELETED_AT
FROM MATERIAL_TABLE_FORMATTED_V1
JOIN PRODUCT_TABLE_FORMATTED_V1
ON MATERIAL_TABLE_FORMATTED_V1.MATERIAL_ID = PRODUCT_TABLE_FORMATTED_V1.KEY;

CREATE SINK CONNECTOR IF NOT EXISTS SINK_MATERIAL_PUBLIC_INFO WITH (
      'connector.class'='io.confluent.connect.jdbc.JdbcSinkConnector',
      'transforms.unwrap.delete.handling.mode'='drop',
      'tasks.max'='1',
      'topics'='{{ .Values.topicPrefix }}MATERIAL_PUBLIC_INFO_V1',
      'fields.whitelist'='material_id,material_type,custom_billing_date,material_created_at,material_updated_at,material_deleted_at,product_id,name,product_type,tax_id,available_from,available_until,remarks,custom_billing_period,billing_schedule_id,disable_pro_rating_flag,is_archived,is_unique,product_created_at,product_updated_at,product_deleted_at',
      'key.converter'='org.apache.kafka.connect.storage.StringConverter',
      'value.converter'='io.confluent.connect.avro.AvroConverter',
      'value.converter.schema.registry.url'='{{ .Values.cpRegistryHost }}',
      'delete.enabled'='false',
      'transforms.unwrap.drop.tombstones'='true',
      'auto.create'='true',
      'connection.url'='${file:/decrypted/kafka-connect.secrets.properties:kec_url}',
      'insert.mode'='upsert',
      'table.name.format'='public.material',
      'pk.mode'='record_key',
      'transforms'='RenameField',
      'transforms.RenameField.type'= 'org.apache.kafka.connect.transforms.ReplaceField$Value',
      'transforms.RenameField.renames'='MATERIAL_ID:material_id,MATERIAL_TYPE:material_type,CUSTOM_BILLING_DATE:custom_billing_date,MATERIAL_CREATED_AT:material_created_at,MATERIAL_UPDATED_AT:material_updated_at,MATERIAL_DELETED_AT:material_deleted_at,PRODUCT_ID:product_id,NAME:name,PRODUCT_TYPE:product_type,TAX_ID:tax_id,AVAILABLE_FROM:available_from,AVAILABLE_UNTIL:available_until,REMARKS:remarks,CUSTOM_BILLING_PERIOD:custom_billing_period,BILLING_SCHEDULE_ID:billing_schedule_id,DISABLE_PRO_RATING_FLAG:disable_pro_rating_flag,IS_ARCHIVED:is_archived,IS_UNIQUE:is_unique,PRODUCT_CREATED_AT:product_created_at,PRODUCT_UPDATED_AT:product_updated_at,PRODUCT_DELETED_AT:product_deleted_at',
      'pk.fields'='material_id'
);
