CREATE STREAM IF NOT EXISTS TIMESHEET_TIMESHEET_FORMATTED
AS SELECT
    AFTER->TIMESHEET_ID AS KEY,
    AS_VALUE(AFTER->TIMESHEET_ID) AS TIMESHEET_ID,
    AFTER->STAFF_ID AS STAFF_ID,
    AFTER->LOCATION_ID AS LOCATION_ID,
    AFTER->TIMESHEET_STATUS AS TIMESHEET_STATUS,
    AFTER->TIMESHEET_DATE AS TIMESHEET_DATE,
    AFTER->REMARK AS REMARK,
    AFTER->CREATED_AT AS CREATED_AT,
    AFTER->UPDATED_AT AS UPDATED_AT,
    AFTER->DELETED_AT AS DELETED_AT
FROM TIMESHEET_TIMESHEET_ORIGINAL
WHERE TIMESHEET_TIMESHEET_ORIGINAL.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
PARTITION BY AFTER->TIMESHEET_ID
EMIT CHANGES;

CREATE TABLE IF NOT EXISTS TIMESHEET_TIMESHEET_TABLE (KEY VARCHAR(STRING) PRIMARY KEY)
WITH(kafka_topic='{{ .Values.topicPrefix }}TIMESHEET_TIMESHEET_FORMATTED', value_format='AVRO');

CREATE STREAM IF NOT EXISTS TIMESHEET_OTHER_WORKING_HOURS_FORMATTED
AS SELECT
    AFTER->OTHER_WORKING_HOURS_ID AS KEY,
    AS_VALUE(AFTER->OTHER_WORKING_HOURS_ID) AS OTHER_WORKING_HOURS_ID,
    AFTER->TIMESHEET_ID AS TIMESHEET_ID,
    AFTER->TIMESHEET_CONFIG_ID AS TIMESHEET_CONFIG_ID,
    AFTER->START_TIME AS START_TIME,
    AFTER->END_TIME AS END_TIME,
    AFTER->TOTAL_HOUR AS TOTAL_HOUR,
    AFTER->REMARKS AS REMARKS,
    AFTER->CREATED_AT AS CREATED_AT,
    AFTER->UPDATED_AT AS UPDATED_AT,
    AFTER->DELETED_AT AS DELETED_AT
FROM TIMESHEET_OTHER_WORKING_HOURS_ORIGINAL
WHERE TIMESHEET_OTHER_WORKING_HOURS_ORIGINAL.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
PARTITION BY AFTER->OTHER_WORKING_HOURS_ID
EMIT CHANGES;

CREATE TABLE IF NOT EXISTS TIMESHEET_OTHER_WORKING_HOURS_TABLE (KEY VARCHAR(STRING) PRIMARY KEY)
WITH(kafka_topic='{{ .Values.topicPrefix }}TIMESHEET_OTHER_WORKING_HOURS_FORMATTED', value_format='AVRO');

CREATE STREAM IF NOT EXISTS TIMESHEET_TRANSPORTATION_EXPENSE_FORMATTED
AS SELECT
    AFTER->TRANSPORTATION_EXPENSE_ID AS KEY,
    AS_VALUE(AFTER->TRANSPORTATION_EXPENSE_ID) AS TRANSPORTATION_EXPENSE_ID,
    AFTER->TIMESHEET_ID AS TIMESHEET_ID,
    AFTER->TRANSPORTATION_TYPE AS TRANSPORTATION_TYPE,
    AFTER->TRANSPORTATION_FROM AS TRANSPORTATION_FROM,
    AFTER->TRANSPORTATION_TO AS TRANSPORTATION_TO,
    AFTER->COST_AMOUNT AS COST_AMOUNT,
    AFTER->ROUND_TRIP AS ROUND_TRIP,
    AFTER->REMARKS AS REMARKS,
    AFTER->CREATED_AT AS CREATED_AT,
    AFTER->UPDATED_AT AS UPDATED_AT,
    AFTER->DELETED_AT AS DELETED_AT
FROM TIMESHEET_TRANSPORTATION_EXPENSE_ORIGINAL
WHERE TIMESHEET_TRANSPORTATION_EXPENSE_ORIGINAL.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
PARTITION BY AFTER->TRANSPORTATION_EXPENSE_ID
EMIT CHANGES;

CREATE TABLE IF NOT EXISTS TIMESHEET_TRANSPORTATION_EXPENSE_TABLE (KEY VARCHAR(STRING) PRIMARY KEY)
WITH(kafka_topic='{{ .Values.topicPrefix }}TIMESHEET_TRANSPORTATION_EXPENSE_FORMATTED', value_format='AVRO');