SET 'auto.offset.reset' = 'earliest';

CREATE STREAM IF NOT EXISTS INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.invoicemgmt.invoice_adjustment', value_format='AVRO');

CREATE STREAM IF NOT EXISTS INVOICE_ADJUSTMENT_STREAM_FORMATTED_V1
    AS SELECT
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->INVOICE_ADJUSTMENT_ID AS KEY,
        AS_VALUE(INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->INVOICE_ADJUSTMENT_ID) AS INVOICE_ADJUSTMENT_ID,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->INVOICE_ID AS INVOICE_ID,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->DESCRIPTION AS DESCRIPTION,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->AMOUNT AS AMOUNT,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->STUDENT_ID AS STUDENT_ID,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->INVOICE_ADJUSTMENT_SEQUENCE_NUMBER AS INVOICE_ADJUSTMENT_SEQUENCE_NUMBER,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS INVOICE_ADJUSTMENT_CREATED_AT,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS INVOICE_ADJUSTMENT_UPDATED_AT,
        INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->DELETED_AT AS INVOICE_ADJUSTMENT_DELETED_AT
    FROM INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1
    WHERE INVOICE_ADJUSTMENT_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY AFTER->INVOICE_ADJUSTMENT_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}INVOICE_ADJUSTMENT_STREAM_FORMATTED_V1', value_format='AVRO');

CREATE TABLE IF NOT EXISTS INVOICE_ADJUSTMENT_PUBLIC_INFO_V1
AS SELECT
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.KEY AS INVOICE_ADJUSTMENT_ID,
    AS_VALUE(INVOICE_TABLE_FORMATTED_V1.KEY) AS INVOICE_ID,
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.DESCRIPTION AS DESCRIPTION,
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.AMOUNT AS AMOUNT,
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.STUDENT_ID AS STUDENT_ID,
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.INVOICE_ADJUSTMENT_SEQUENCE_NUMBER AS INVOICE_ADJUSTMENT_SEQUENCE_NUMBER,
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.INVOICE_ADJUSTMENT_CREATED_AT AS INVOICE_ADJUSTMENT_CREATED_AT,
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.INVOICE_ADJUSTMENT_UPDATED_AT AS INVOICE_ADJUSTMENT_UPDATED_AT,
    INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.INVOICE_ADJUSTMENT_DELETED_AT AS INVOICE_ADJUSTMENT_DELETED_AT,
    INVOICE_TABLE_FORMATTED_V1.INVOICE_TYPE AS INVOICE_TYPE,
    INVOICE_TABLE_FORMATTED_V1.INVOICE_STATUS AS INVOICE_STATUS,
    INVOICE_TABLE_FORMATTED_V1.SUB_TOTAL AS SUB_TOTAL,
    INVOICE_TABLE_FORMATTED_V1.TOTAL AS TOTAL,
    INVOICE_TABLE_FORMATTED_V1.OUTSTANDING_BALANCE AS OUTSTANDING_BALANCE,
    INVOICE_TABLE_FORMATTED_V1.AMOUNT_PAID AS AMOUNT_PAID,
    INVOICE_TABLE_FORMATTED_V1.AMOUNT_REFUNDED AS AMOUNT_REFUNDED,
    INVOICE_TABLE_FORMATTED_V1.CREATED_AT AS INVOICE_CREATED_AT,
    INVOICE_TABLE_FORMATTED_V1.UPDATED_AT AS INVOICE_UPDATED_AT,
    INVOICE_TABLE_FORMATTED_V1.DELETED_AT AS INVOICE_DELETED_AT
FROM INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1
JOIN INVOICE_TABLE_FORMATTED_V1
ON INVOICE_ADJUSTMENT_TABLE_FORMATTED_V1.INVOICE_ID = INVOICE_TABLE_FORMATTED_V1.KEY;


CREATE SINK CONNECTOR IF NOT EXISTS SINK_INVOICE_ADJUSTMENT_PUBLIC_INFO_V1 WITH (
      'connector.class'='io.confluent.connect.jdbc.JdbcSinkConnector',
      'transforms.unwrap.delete.handling.mode'='drop',
      'tasks.max'='1',
      'topics'='{{ .Values.topicPrefix }}INVOICE_ADJUSTMENT_PUBLIC_INFO_V1',
      'fields.whitelist'='invoice_adjustment_id,invoice_id,description,amount,student_id,invoice_adjustment_sequence_number,invoice_adjustment_updated_at,invoice_adjustment_created_at,invoice_adjustment_deleted_at,invoice_type,invoice_status,sub_total,total,outstanding_balance,amount_paid,amount_refunded,invoice_created_at,invoice_updated_at,invoice_deleted_at',
      'key.converter'='org.apache.kafka.connect.storage.StringConverter',
      'value.converter'='io.confluent.connect.avro.AvroConverter',
      'value.converter.schema.registry.url'='{{ .Values.cpRegistryHost }}',
      'delete.enabled'='false',
      'transforms.unwrap.drop.tombstones'='true',
      'auto.create'='true',
      'connection.url'='${file:/decrypted/kafka-connect.secrets.properties:kec_url}',
      'insert.mode'='upsert',
      'table.name.format'='public.invoice_adjustment',
      'pk.mode'='record_key',
      'transforms'='RenameField',
      'transforms.RenameField.type'= 'org.apache.kafka.connect.transforms.ReplaceField$Value',
      'transforms.RenameField.renames'='INVOICE_ADJUSTMENT_ID:invoice_adjustment_id,INVOICE_ID:invoice_id,DESCRIPTION:description,AMOUNT:amount,STUDENT_ID:student_id,INVOICE_ADJUSTMENT_SEQUENCE_NUMBER:invoice_adjustment_sequence_number,INVOICE_ADJUSTMENT_CREATED_AT:invoice_adjustment_created_at,INVOICE_ADJUSTMENT_UPDATED_AT:invoice_adjustment_updated_at,INVOICE_ADJUSTMENT_DELETED_AT:invoice_adjustment_deleted_at,INVOICE_TYPE:invoice_type,INVOICE_STATUS:invoice_status,SUB_TOTAL:sub_total,TOTAL:total,OUTSTANDING_BALANCE:outstanding_balance,AMOUNT_PAID:amount_paid,AMOUNT_REFUNDED:amount_refunded,INVOICE_CREATED_AT:invoice_created_at,INVOICE_UPDATED_AT:invoice_updated_at,INVOICE_DELETED_AT:invoice_deleted_at',
      'pk.fields'='invoice_adjustment_id'
);
