SET 'auto.offset.reset' = 'earliest';

CREATE STREAM IF NOT EXISTS BILLING_RATIO_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.fatima.billing_ratio', value_format='AVRO');

CREATE STREAM IF NOT EXISTS BILLING_RATIO_STREAM_FORMATTED_V1
    AS SELECT
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->BILLING_RATIO_ID AS KEY,
        AS_VALUE(BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->BILLING_RATIO_ID) AS BILLING_RATIO_ID,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->START_DATE AS BILLING_RATIO_START_DATE,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->END_DATE AS BILLING_RATIO_END_DATE,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->BILLING_SCHEDULE_PERIOD_ID AS BILLING_SCHEDULE_PERIOD_ID,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->BILLING_RATIO_NUMERATOR AS BILLING_RATIO_NUMERATOR,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->BILLING_RATIO_DENOMINATOR AS BILLING_RATIO_DENOMINATOR,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->IS_ARCHIVED AS BILLING_RATIO_IS_ARCHIVED,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS BILLING_RATIO_CREATED_AT,
        BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS BILLING_RATIO_UPDATED_AT,
        CAST(NULL AS VARCHAR) AS BILLING_RATIO_DELETED_AT
    FROM BILLING_RATIO_STREAM_ORIGIN_V1
    WHERE BILLING_RATIO_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY AFTER->BILLING_RATIO_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS BILLING_RATIO_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}BILLING_RATIO_STREAM_FORMATTED_V1', value_format='AVRO');

CREATE STREAM IF NOT EXISTS BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.fatima.billing_schedule_period', value_format='AVRO');

CREATE STREAM IF NOT EXISTS BILLING_SCHEDULE_PERIOD_STREAM_FORMATTED_V1
    AS SELECT
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->BILLING_SCHEDULE_PERIOD_ID AS KEY,
        AS_VALUE(BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->BILLING_SCHEDULE_PERIOD_ID) AS BILLING_SCHEDULE_PERIOD_ID,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->NAME AS BILLING_SCHEDULE_PERIOD_NAME,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->BILLING_SCHEDULE_ID AS BILLING_SCHEDULE_ID,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->START_DATE AS BILLING_SCHEDULE_PERIOD_START_DATE,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->END_DATE AS BILLING_SCHEDULE_PERIOD_END_DATE,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->BILLING_DATE AS BILLING_DATE,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->REMARKS AS BILLING_SCHEDULE_PERIOD_REMARKS,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->IS_ARCHIVED AS BILLING_SCHEDULE_PERIOD_IS_ARCHIVED,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS BILLING_SCHEDULE_PERIOD_CREATED_AT,
        BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS BILLING_SCHEDULE_PERIOD_UPDATED_AT,
        CAST(NULL AS VARCHAR) AS BILLING_SCHEDULE_PERIOD_DELETED_AT
    FROM BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1
    WHERE BILLING_SCHEDULE_PERIOD_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY AFTER->BILLING_SCHEDULE_PERIOD_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}BILLING_SCHEDULE_PERIOD_STREAM_FORMATTED_V1', value_format='AVRO');

CREATE TABLE IF NOT EXISTS BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1
AS SELECT
    BILLING_RATIO_TABLE_FORMATTED_V1.KEY AS ROW_KEY,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_ID AS BILLING_RATIO_ID,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_START_DATE AS BILLING_RATIO_START_DATE,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_END_DATE AS BILLING_RATIO_END_DATE,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_NUMERATOR AS BILLING_RATIO_NUMERATOR,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_DENOMINATOR AS BILLING_RATIO_DENOMINATOR,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_IS_ARCHIVED AS BILLING_RATIO_IS_ARCHIVED,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_CREATED_AT AS BILLING_RATIO_CREATED_AT,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_UPDATED_AT AS BILLING_RATIO_UPDATED_AT,
    BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_RATIO_DELETED_AT AS BILLING_RATIO_DELETED_AT,
    AS_VALUE(BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.KEY) AS BILLING_SCHEDULE_PERIOD_ID,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_NAME AS BILLING_SCHEDULE_PERIOD_NAME,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_ID AS BILLING_SCHEDULE_ID,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_START_DATE AS BILLING_SCHEDULE_PERIOD_START_DATE,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_END_DATE AS BILLING_SCHEDULE_PERIOD_END_DATE,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_DATE AS BILLING_DATE,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_REMARKS AS BILLING_SCHEDULE_PERIOD_REMARKS,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_IS_ARCHIVED AS BILLING_SCHEDULE_PERIOD_IS_ARCHIVED,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_CREATED_AT AS BILLING_SCHEDULE_PERIOD_CREATED_AT,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_UPDATED_AT AS BILLING_SCHEDULE_PERIOD_UPDATED_AT,
    BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_DELETED_AT AS BILLING_SCHEDULE_PERIOD_DELETED_AT
FROM BILLING_RATIO_TABLE_FORMATTED_V1
JOIN BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1
ON BILLING_RATIO_TABLE_FORMATTED_V1.BILLING_SCHEDULE_PERIOD_ID = BILLING_SCHEDULE_PERIOD_TABLE_FORMATTED_V1.KEY;

CREATE STREAM IF NOT EXISTS BILLING_SCHEDULE_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.fatima.billing_schedule', value_format='AVRO');

CREATE STREAM IF NOT EXISTS BILLING_SCHEDULE_STREAM_FORMATTED_V1
    AS SELECT
        BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->BILLING_SCHEDULE_ID AS KEY,
        AS_VALUE(BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->BILLING_SCHEDULE_ID) AS BILLING_SCHEDULE_ID,
        BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->NAME AS BILLING_SCHEDULE_NAME,
        BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->REMARKS AS BILLING_SCHEDULE_REMARKS,
        BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->IS_ARCHIVED AS BILLING_SCHEDULE_IS_ARCHIVED,
        BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS BILLING_SCHEDULE_CREATED_AT,
        BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS BILLING_SCHEDULE_UPDATED_AT,
        CAST(NULL AS VARCHAR) AS BILLING_SCHEDULE_DELETED_AT
    FROM BILLING_SCHEDULE_STREAM_ORIGIN_V1
    WHERE BILLING_SCHEDULE_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY AFTER->BILLING_SCHEDULE_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS BILLING_SCHEDULE_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}BILLING_SCHEDULE_STREAM_FORMATTED_V1', value_format='AVRO');

CREATE TABLE IF NOT EXISTS BILLING_RATIO_PUBLIC_INFO_V1
AS SELECT
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.ROW_KEY AS ROW_KEY,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_ID AS BILLING_RATIO_ID,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_START_DATE AS BILLING_RATIO_START_DATE,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_END_DATE AS BILLING_RATIO_END_DATE,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_NUMERATOR AS BILLING_RATIO_NUMERATOR,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_DENOMINATOR AS BILLING_RATIO_DENOMINATOR,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_IS_ARCHIVED AS BILLING_RATIO_IS_ARCHIVED,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_CREATED_AT AS BILLING_RATIO_CREATED_AT,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_UPDATED_AT AS BILLING_RATIO_UPDATED_AT,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_RATIO_DELETED_AT AS BILLING_RATIO_DELETED_AT,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_ID AS BILLING_SCHEDULE_PERIOD_ID,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_NAME AS BILLING_SCHEDULE_PERIOD_NAME,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_START_DATE AS BILLING_SCHEDULE_PERIOD_START_DATE,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_END_DATE AS BILLING_SCHEDULE_PERIOD_END_DATE,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_DATE AS BILLING_DATE,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_REMARKS AS BILLING_SCHEDULE_PERIOD_REMARKS,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_IS_ARCHIVED AS BILLING_SCHEDULE_PERIOD_IS_ARCHIVED,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_CREATED_AT AS BILLING_SCHEDULE_PERIOD_CREATED_AT,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_UPDATED_AT AS BILLING_SCHEDULE_PERIOD_UPDATED_AT,
    BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_PERIOD_DELETED_AT AS BILLING_SCHEDULE_PERIOD_DELETED_AT,
    AS_VALUE(BILLING_SCHEDULE_TABLE_FORMATTED_V1.KEY) AS BILLING_SCHEDULE_ID,
    BILLING_SCHEDULE_TABLE_FORMATTED_V1.BILLING_SCHEDULE_NAME AS BILLING_SCHEDULE_NAME,
    BILLING_SCHEDULE_TABLE_FORMATTED_V1.BILLING_SCHEDULE_REMARKS AS BILLING_SCHEDULE_REMARKS,
    BILLING_SCHEDULE_TABLE_FORMATTED_V1.BILLING_SCHEDULE_IS_ARCHIVED AS BILLING_SCHEDULE_IS_ARCHIVED,
    BILLING_SCHEDULE_TABLE_FORMATTED_V1.BILLING_SCHEDULE_CREATED_AT AS BILLING_SCHEDULE_CREATED_AT,
    BILLING_SCHEDULE_TABLE_FORMATTED_V1.BILLING_SCHEDULE_UPDATED_AT AS BILLING_SCHEDULE_UPDATED_AT,
    BILLING_SCHEDULE_TABLE_FORMATTED_V1.BILLING_SCHEDULE_DELETED_AT AS BILLING_SCHEDULE_DELETED_AT
FROM BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1
JOIN BILLING_SCHEDULE_TABLE_FORMATTED_V1
ON BILLING_RATIO_SCHEDULE_PERIOD_PUBLIC_INFO_V1.BILLING_SCHEDULE_ID = BILLING_SCHEDULE_TABLE_FORMATTED_V1.KEY;
