{
 "title": "Communication using Thanos",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "UAT : staging, Staging : staging-2, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total connection per Tom nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(manabie_app_tom_total_conn{gke_cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection disconnection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(manabie_app_tom_total_client_disconnect{gke_cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (app)",
     "legendFormat": "Total client disconnection"
    },
    {
     "expr": "sum(rate(manabie_app_tom_total_server_disconnect{gke_cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (app)",
     "legendFormat": "Total server disconnection"
    }
   ]
  },
  {
   "title": "Notification creation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(manabie_notification_created_counter{gke_cluster=\"$cluster\", namespace=\"$namespace\"}[1d]))) by (app)",
     "legendFormat": "{{app}} app"
    }
   ]
  },
  {
   "title": "User notification creation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(manabie_user_notification_created_counter{gke_cluster=\"$cluster\", namespace=\"$namespace\"}[1d]))) by (app)",
     "legendFormat": "{{app}} app"
    }
   ]
  }
 ]
}