{
 "title": "Overall GRPC Perf using Thanos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "UAT : staging, Staging : staging-2, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs{namespace=\"$namespace\"}, app_kubernetes_io_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods & APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "rpc/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Status code Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service\",grpc_server_method!~\"health|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_status) / ignoring(grpc_server_status) group_left sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service\",grpc_server_method!~\"health|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) * 100 > 0",
     "legendFormat": "{{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Error rate by method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\".+health.+|.+Subscribe.*\",namespace=\"$namespace\",grpc_server_status=~\"INTERNAL|UNKNOWN\"}[$__rate_interval])) by (grpc_server_status, grpc_server_method) / sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\".+health.+|.+Subscribe.*\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_status, grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}: {{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "rpc/s by method",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\".+Health.+|.+Subscribe.*\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_method)",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service\",grpc_server_method!~\".+Health.+|.+Upload|.+Subscribe.*|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service\",grpc_server_method!~\".+Health.+|.+Upload|.+Subscribe.*|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{gke_cluster=\"$cluster\", pod=~\"^($service).+\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\".+Health.+|.+Upload|.+Subscribe|.+StreamingEvent|.+Subscribe.*\",namespace=\"$namespace\"}[$__rate_interval]) > 0) by (le))",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|manabie.bob.UploadService/Upload|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval]) > 0) by (le))",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Handler Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetstream_processed_messages{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service.*\",namespace=\"$namespace\"}[5m])) by (consumer_handler_status) / ignoring(consumer_handler_status) group_left sum(rate(jetstream_processed_messages{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service.*\",namespace=\"$namespace\"}[5m])) * 100 > 0",
     "legendFormat": "{{ consumer_handler_status }}"
    }
   ]
  },
  {
   "title": "Handler P95 Processing Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jetstream_processed_messages_latency_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=~\"$service.*\",namespace=\"$namespace\"}[$__rate_interval])) by (le, jetstream_queue_name, jetstream_subject_name))",
     "legendFormat": "{{ jetstream_queue_name }} - {{ jetstream_subject_name }}"
    }
   ]
  }
 ]
}