{
 "title": "Overall HTTP Perf using Thanos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(istio_requests_total{destination_service_namespace=\"$namespace\"}, destination_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "rpc/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{gke_cluster=\"$cluster\", destination_service_name=~\"$service\", destination_service_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(istio_requests_total{gke_cluster=\"$cluster\", destination_service_name=~\"$service\", destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Status code Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (response_code) / ignoring(response_code) group_left sum(rate(istio_requests_total{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) * 100 > 0",
     "legendFormat": "{{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{gke_cluster=\"$cluster\", image!=\"\",container!=\"POD\",pod=~\"^($service-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{gke_cluster=\"$cluster\", container!=\"POD\",pod=~\"^($service-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"core\"}) /\ncount(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{gke_cluster=\"$cluster\", container!=\"POD\",pod=~\"^($service-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"core\"}) /\ncount(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{gke_cluster=\"$cluster\", image!=\"\",container!=\"POD\",pod=~\"^($service-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{gke_cluster=\"$cluster\", container!=\"POD\",pod=~\"^($service-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"byte\"}) /\ncount(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{gke_cluster=\"$cluster\", container!=\"POD\",pod=~\"^($service-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"core\"}) /\ncount(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Receive Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_bytes_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_bytes_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    },
    {}
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_response_bytes_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_response_bytes_bucket{gke_cluster=\"$cluster\", destination_service_name=~\"$service\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    }
   ]
  }
 ]
}