{
 "title": "Services performance using Thanos",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, Manabie : manabie, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "rpc/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[$__rate_interval]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|manabie.bob.UploadService/Upload|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|manabie.bob.UploadService/Upload|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "gRPC Response status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"health|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_status) / ignoring(grpc_server_status) group_left sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"health|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Error rate by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\".+health.+|.+Subscribe\",namespace=\"$namespace\",grpc_server_status=~\"INTERNAL|UNKNOWN\"}[$__rate_interval])) by (grpc_server_status, grpc_server_method) / sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\".+health.+|.+Subscribe\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_status, grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}: {{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "rpc/s by method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!=\"grpc.health.v1.Health/Check\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_method)",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Request distribution by pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!=\"grpc.health.v1.Health/Check\",namespace=\"$namespace\"}[$__rate_interval])) by (pod) / ignoring(pod) group_left sum(rate(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!=\"grpc.health.v1.Health/Check\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{gke_cluster=\"$cluster\", image!=\"\",container!=\"POD\",pod=~\"^($service).+\",namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{gke_cluster=\"$cluster\", image!=\"\",container!=\"POD\",pod=~\"^($service).+\",namespace=\"$namespace\"}[$__rate_interval])) by (container, pod)",
     "legendFormat": "{{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{gke_cluster=\"$cluster\", image!=\"\",container!=\"POD\",pod=~\"^($service).+\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{gke_cluster=\"$cluster\", image!=\"\",container!=\"POD\",namespace=\"$namespace\",pod=~\"^$service.+\"}) by (container, pod)",
     "legendFormat": "{{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P50)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_io_server_server_latency_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|manabie.bob.UploadService/Upload|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method))",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P95)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|manabie.bob.UploadService/Upload|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method, db))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Received bytes per Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_received_bytes_per_rpc_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|manabie.bob.UploadService/Upload|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Sent bytes per Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_sent_bytes_per_rpc_bucket{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|manabie.bob.UploadService/Upload|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval]) > 0) by (le, grpc_server_method))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{gke_cluster=\"$cluster\", pod=~\"^($service).+\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_local_call{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+Subscribe|.+StreamingEvent\",cache_status=\"hit\",namespace=\"$namespace\"}[$__rate_interval])) by (cache_group) / sum(rate(cache_local_call{gke_cluster=\"$cluster\", app_kubernetes_io_name=\"$service\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+Subscribe|.+StreamingEvent\",namespace=\"$namespace\"}[$__rate_interval])) by (cache_group)",
     "legendFormat": "{{ cache_group }}"
    }
   ]
  }
 ]
}