// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/manabie-com/backend/internal/golibs/database"
	mock "github.com/stretchr/testify/mock"
)

// IOrderServiceForOrderDetail is an autogenerated mock type for the IOrderServiceForOrderDetail type
type IOrderServiceForOrderDetail struct {
	mock.Mock
}

type IOrderServiceForOrderDetail_Expecter struct {
	mock *mock.Mock
}

func (_m *IOrderServiceForOrderDetail) EXPECT() *IOrderServiceForOrderDetail_Expecter {
	return &IOrderServiceForOrderDetail_Expecter{mock: &_m.Mock}
}

// GetOrderTypeByOrderID provides a mock function with given fields: ctx, db, orderID
func (_m *IOrderServiceForOrderDetail) GetOrderTypeByOrderID(ctx context.Context, db database.Ext, orderID string) (string, error) {
	ret := _m.Called(ctx, db, orderID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Ext, string) (string, error)); ok {
		return rf(ctx, db, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Ext, string) string); ok {
		r0 = rf(ctx, db, orderID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Ext, string) error); ok {
		r1 = rf(ctx, db, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderTypeByOrderID'
type IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call struct {
	*mock.Call
}

// GetOrderTypeByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.Ext
//   - orderID string
func (_e *IOrderServiceForOrderDetail_Expecter) GetOrderTypeByOrderID(ctx interface{}, db interface{}, orderID interface{}) *IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call {
	return &IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call{Call: _e.mock.On("GetOrderTypeByOrderID", ctx, db, orderID)}
}

func (_c *IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call) Run(run func(ctx context.Context, db database.Ext, orderID string)) *IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.Ext), args[2].(string))
	})
	return _c
}

func (_c *IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call) Return(orderType string, err error) *IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call {
	_c.Call.Return(orderType, err)
	return _c
}

func (_c *IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call) RunAndReturn(run func(context.Context, database.Ext, string) (string, error)) *IOrderServiceForOrderDetail_GetOrderTypeByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewIOrderServiceForOrderDetail interface {
	mock.TestingT
	Cleanup(func())
}

// NewIOrderServiceForOrderDetail creates a new instance of IOrderServiceForOrderDetail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIOrderServiceForOrderDetail(t mockConstructorTestingTNewIOrderServiceForOrderDetail) *IOrderServiceForOrderDetail {
	mock := &IOrderServiceForOrderDetail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
