// Code generated by mockgen. DO NOT EDIT.
package mock_timesheet

import (
	"context"

	"github.com/manabie-com/backend/internal/timesheet/domain/dto"
	"github.com/stretchr/testify/mock"
)

type MockAutoCreateFlagActivityLogServiceImpl struct {
	mock.Mock
}

func (r *MockAutoCreateFlagActivityLogServiceImpl) UpsertFlagLog(arg1 context.Context, arg2 *dto.AutoCreateFlagActivityLog) error {
	args := r.Called(arg1, arg2)
	return args.Error(0)
}
