// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/jackc/pgtype"
	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/eureka/entities"
	"github.com/manabie-com/backend/internal/golibs/database"
)

type MockCourseStudentAccessPathRepo struct {
	mock.Mock
}

func (r *MockCourseStudentAccessPathRepo) BulkUpsert(arg1 context.Context, arg2 database.QueryExecer, arg3 []*entities.CourseStudentsAccessPath) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}

func (r *MockCourseStudentAccessPathRepo) DeleteLatestCourseStudentAccessPathsByCourseStudentIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}

func (r *MockCourseStudentAccessPathRepo) GetByLocationsAndCourse(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray, arg4 pgtype.TextArray) ([]*entities.CourseStudentsAccessPath, error) {
	args := r.Called(arg1, arg2, arg3, arg4)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entities.CourseStudentsAccessPath), args.Error(1)
}

func (r *MockCourseStudentAccessPathRepo) GetByLocationsAndStudents(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray, arg4 pgtype.TextArray) ([]*entities.CourseStudentsAccessPath, error) {
	args := r.Called(arg1, arg2, arg3, arg4)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entities.CourseStudentsAccessPath), args.Error(1)
}

func (r *MockCourseStudentAccessPathRepo) GetByLocationsStudentsAndCourse(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray, arg4 pgtype.TextArray, arg5 pgtype.TextArray) ([]*entities.CourseStudentsAccessPath, error) {
	args := r.Called(arg1, arg2, arg3, arg4, arg5)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entities.CourseStudentsAccessPath), args.Error(1)
}
