// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/jackc/pgtype"
	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/eureka/repositories"
	"github.com/manabie-com/backend/internal/golibs/database"
)

type MockStudentRepo struct {
	mock.Mock
}

func (r *MockStudentRepo) FilterByGradeBookView(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray, arg4 pgtype.TextArray, arg5 pgtype.TextArray, arg6 pgtype.Int4Array, arg7 pgtype.TextArray, arg8 pgtype.Text, arg9 pgtype.TextArray, arg10 int64, arg11 int64) ([]*repositories.StudentInfo, error) {
	args := r.Called(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*repositories.StudentInfo), args.Error(1)
}

func (r *MockStudentRepo) FilterOutDeletedStudentIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 []string) ([]string, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]string), args.Error(1)
}

func (r *MockStudentRepo) FindClassesByCourseID(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.Text) (*pgtype.TextArray, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*pgtype.TextArray), args.Error(1)
}

func (r *MockStudentRepo) FindStudentsByClassIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray) (*pgtype.TextArray, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*pgtype.TextArray), args.Error(1)
}

func (r *MockStudentRepo) FindStudentsByCourseID(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.Text) (*pgtype.TextArray, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*pgtype.TextArray), args.Error(1)
}

func (r *MockStudentRepo) FindStudentsByCourseLocation(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.Text, arg4 pgtype.TextArray) (*pgtype.TextArray, error) {
	args := r.Called(arg1, arg2, arg3, arg4)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*pgtype.TextArray), args.Error(1)
}

func (r *MockStudentRepo) FindStudentsByLocation(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray) (*pgtype.TextArray, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*pgtype.TextArray), args.Error(1)
}
