{
 "title": "Confluent Schema Registry using Thanos",
 "tags": [ "6.0.1" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, Manabie : manabie, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(cp_kafka_schema_registry_jetty_metrics_connections_active{gke_cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Kafka Schema Registry servers",
   "type": "singlestat",
   "description": "Number of Kafka Schema Registry servers",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_schema_registry_jetty_metrics_connections_active{gke_cluster=\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_active{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Open Rate",
   "type": "singlestat",
   "description": "The average rate per second of opened TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_opened_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Close Rate",
   "type": "singlestat",
   "description": "The average rate per second of closed TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_closed_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Busy thread count",
   "type": "singlestat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_busy_thread_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Total thread count",
   "type": "singlestat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_busy_thread_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}/cp_kafka_schema_registry_jetty_metrics_thread_pool_usage{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Thread pool usage",
   "type": "gauge",
   "description": "The average rate per second of closed TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_thread_pool_usage{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{gke_cluster=\"$cluster\", image!=\"\", namespace=~\"^$namespace$\", pod=~\"$pod\"}[10m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "sum without(area)(jvm_memory_bytes_max{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Total request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_request_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate (average by second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_request_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_request_error_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error request rate ( average per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_request_error_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Subject get schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Subjects get schema request count",
   "type": "graph",
   "description": "api POST /subjects/{subject}",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_get_schema_request_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Subjects get schema request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_get_schema_request_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error subjects get schema request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_get_schema_request_error_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error subjects get schema request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_get_schema_request_error_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Subject version register request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Current subject versions register request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_versions_register_request_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Subjects versions register request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_versions_register_request_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error subject versions register request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_versions_register_request_error_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error subject versions register request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jersey_metrics_subjects_versions_register_request_error_rate{gke_cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}