{
 "title": "Debezium using Thanos",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, Manabie : manabie, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "connector_type",
    "label": "Connector Type",
    "query": {
     "query": "debezium_metrics_TotalNumberOfEventsSeen{gke_cluster=\"$cluster\"}"
    }
   },
   {
    "name": "connector_name",
    "label": "Connector Name",
    "query": {
     "query": "debezium_metrics_TotalNumberOfEventsSeen{gke_cluster=\"$cluster\", plugin=\"$connector_type\"}"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(debezium_metrics_TotalNumberOfEventsSeen{gke_cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time since last event",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\", name=\"$connector_name\",context=~\"(binlog|streaming)\"}"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{gke_cluster=\"$cluster\", plugin=\"$connector_type\", namespace=~\"$namespace\", name=\"$connector_name\",context=~\"(binlog|streaming)\"}",
     "legendFormat": "Total events received"
    },
    {
     "expr": "debezium_metrics_NumberOfEventsSkipped{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=~\"$namespace\",name=\"$connector_name\",context=~\"(binlog|streaming)\"}",
     "legendFormat": "Events skipped"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_Connected{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=~\"(binlog|streaming)\"}"
    }
   ]
  },
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Table count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Remaining tables",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Aborted",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Total events received"
    },
    {
     "expr": "debezium_metrics_NumberOfEventsSkipped{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Events skipped"
    }
   ]
  },
  {
   "title": "Rows scanned",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "debezium_metrics_RowsScanned{gke_cluster=\"$cluster\", plugin=\"$connector_type\",namespace=\"$namespace\",name=\"$connector_name\"}"
    }
   ]
  },
  {
   "title": "Connector Status",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connector_status{gke_cluster=\"$cluster\", namespace=~\"$namespace\"}"
    }
   ]
  },
  { "title": "Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Connector Task",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_metrics_task_startup_failure_total{gke_cluster=\"$cluster\", namespace=\"$namespace\"}"
    },
    {
     "expr": "kafka_connect_worker_metrics_task_startup_success_total{gke_cluster=\"$cluster\", namespace=\"$namespace\"}"
    },
    {
     "expr": "kafka_connect_worker_metrics_task_count{gke_cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of connectors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_connect_worker_metrics_connector_count{gke_cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Network traffic rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_metrics_incoming_byte_rate{gke_cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "Incoming({{client}})"
    },
    {
     "expr": "kafka_connect_metrics_outgoing_byte_rate{gke_cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "Outgoing({{client}})"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{gke_cluster=\"$cluster\", area='heap',namespace=\"$namespace\"}",
     "legendFormat": "Used-{{namespace}}-{{pod}}"
    },
    {
     "expr": "jvm_memory_bytes_max{gke_cluster=\"$cluster\", area='heap',namespace=\"$namespace\"}",
     "legendFormat": "Maximum-{{pod}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{gke_cluster=\"$cluster\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "jvm_threads_peak{gke_cluster=\"$cluster\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "jvm_threads_started_total{gke_cluster=\"$cluster\"}",
     "legendFormat": "Started in total"
    }
   ]
  }
 ]
}