{
 "title": "Kafka Exporter Overview using Thanos",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{gke_cluster=\"$cluster\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{gke_cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{gke_cluster=\"$cluster\", instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": {
     "query": "label_values(kafka_connect_connector_worker_connector_running_task_count{gke_cluster=~\"$cluster\", namespace=~\"$namespace\"}, connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of tasks in worker",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_metrics_task_count{gke_cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connector task with partition",
   "type": "graph",
   "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_partition_count{gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"} > 0 ",
     "legendFormat": "{{connector}} (task: {{task}})"
    }
   ]
  },
  {
   "title": "Connector running task count",
   "type": "graph",
   "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_worker_connector_running_task_count{gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"} > 0 ",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Thread state of kafka component",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{gke_cluster=\"$cluster\", namespace=~\"$namespace\"} > 0 ",
     "legendFormat": "{{pod}} - {{state}}"
    }
   ]
  },
  { "title": "Sync monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "sink  record  rate",
   "type": "graph",
   "description": "After transformations are applied, this is the average per-second number of records output from the transformations and sent to the task belonging to the named sink connector in the worker (excludes any records filtered out by the transformations)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_sink_task_sink_record_send_rate{gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"}) by (connector) >0 ",
     "legendFormat": "SEND : {{connector}}"
    },
    {
     "expr": "sum(kafka_connect_sink_task_sink_record_read_rate {gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"}) by (connector) > 0 ",
     "legendFormat": "READ  : {{connector}}"
    }
   ]
  },
  {
   "title": "Sink record active count",
   "type": "graph",
   "description": "Most recent number of records read from Kafka but not yet completely committed, flushed, or acknowledged by the sink task",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_sink_task_sink_record_active_count{gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"}) by (connector)",
     "legendFormat": "sink {{connector}}"
    },
    {
     "expr": "sum(kafka_connect_source_task_source_record_active_count{gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"}) by (connector)",
     "legendFormat": "source  {{connector}}"
    }
   ]
  },
  {
   "title": "Put batch max time ms",
   "type": "graph",
   "description": "Maximum time in milliseconds taken by this task to put a batch of sink records\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_sink_task_put_batch_max_time_ms{gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"}) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Fail task by consumer ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_task_error_total_record_errors {gke_cluster=\"$cluster\",namespace=~\"$namespace\"}) by (connector, total_record_errors)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{gke_cluster=\"$cluster\",topic=~\"$topic\",namespace=~\"$namespace\" }) by (consumergroup, topic )",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message throughput per minute",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{gke_cluster=\"$cluster\", instance=~'$instance', topic=~\"$topic\", namespace=~\"$namespace\"}[5m])/5) by (topic) > 0",
     "legendFormat": "producer push  {{topic}}"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{gke_cluster=\"$cluster\", instance=~'$instance',topic=~\"$topic\",namespace=~\"$namespace\"}[5m])/5) by (consumergroup, topic) > 0",
     "legendFormat": "consumer poll   {{topic}}"
    }
   ]
  },
  {
   "title": "offset commit completion rate",
   "type": "graph",
   "description": "Average per-second number of offset commit completions that have completed successfully",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_sink_task_offset_commit_completion_rate{gke_cluster=~\"$cluster\", namespace=~\"$namespace\", connector=~\"$connector\"}) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{gke_cluster=\"$cluster\", instance=\"$instance\",topic=~\"$topic\",namespace=~\"$namespace\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latest offset of partition by topic",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{gke_cluster=\"$cluster\", topic=~\"$topic\", namespace=~\"$namespace\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer current offset",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset{gke_cluster=\"$cluster\", topic=~\"$topic\", namespace=~\"$namespace\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "kafka_topic_partition_current_offset{gke_cluster=\"$cluster\", topic=~\"$topic\", namespace=~\"$namespace\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}