{
 "title": "Ksql",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, Manabie : manabie, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo,"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics_cur_size_all_mem_tables{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics_cur_size_all_mem_tables{gke_cluster=\"$cluster\", namespace=~\"$namespace\"}, instance)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics_cur_size_all_mem_tables{gke_cluster=\"$cluster\"}, pod)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": { "query": "label_values(quantile)" } }
  ]
 },
 "panels": [
  {
   "title": "Current size of all memory tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_cur_size_all_mem_tables{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Pending error query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ksql_engine_query_stats_pending_error_queries{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Persistence queries message lags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Query engine stats error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ksql_engine_query_stats_error_rate{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "stream state bytes written total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_bytes_written_total{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Liveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ksql_engine_query_stats_liveness_indicator{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "Message Consume per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "ksql_consumer_metrics_consumer_messages_per_sec{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Count queries not running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ksql_engine_query_stats_not_running_queries{gke_cluster=\"$cluster\",  namespace=~\"^$namespace$\",  pod=~\"$pod$\"}",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  }
 ]
}