{
 "title": "Kafka Topics using Thanos",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, Manabie : manabie, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(kafka_log_log_size{gke_cluster=\"$cluster\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total # of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{gke_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesinpersec{gke_cluster=\"$cluster\", namespace=~\"$namespace\",topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{gke_cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total # of Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount{gke_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesinpersec{gke_cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesoutpersec{gke_cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Produce Request per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{gke_cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Request per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{gke_cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Topic offsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Start Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{gke_cluster=\"$cluster\", topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "End Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{gke_cluster=\"$cluster\", topic=~\"$topic\"}"
    }
   ]
  }
 ]
}