ALTER TABLE ONLY public.emails DROP CONSTRAINT IF EXISTS email_status_type_check;
ALTER TABLE public.emails ADD CONSTRAINT email_status_type_check CHECK (status = ANY (ARRAY[
		'EMAIL_STATUS_NONE',
		'EMAIL_STATUS_QUEUED_FAILED',
		'EMAIL_STATUS_QUEUED',
		'EMAIL_STATUS_PROCESSED_FAILED',
		'EMAIL_STATUS_PROCESSED'
]::TEXT[]));
