CREATE TABLE IF NOT EXISTS bob.lesson_members_public_info (
    lesson_id text NOT NULL,
    student_id text NOT NULL,
    course_id text,
    lesson_members_updated_at timestamptz NOT NULL,
    lesson_members_created_at timestamptz NOT NULL,
    lesson_members_deleted_at timestamptz,
    attendance_status text,
    attendance_remark text,
    attendance_notice text,
    attendance_reason text,
    attendance_note text,
    lessons_created_at timestamptz NOT NULL,
    lessons_updated_at timestamptz NOT NULL,
    lessons_deleted_at timestamptz,
    end_at timestamptz,
    control_settings jsonb null,
    lesson_group_id text,
    room_id text,
    lesson_type text,
    status text,
    stream_learner_counter int4 NOT NULL,
    learner_ids _text NOT NULL DEFAULT '{}'::text[],
    name text,
    start_time timestamptz NULL,
    end_time timestamptz NULL,
    room_state jsonb NULL,
    class_id text,
    center_id text,
    teaching_method text,
    teaching_medium text,
    scheduling_status text,
    is_locked bool NOT NULL,
    scheduler_id text,

    CONSTRAINT pk__lesson_members_public_info PRIMARY KEY (lesson_id,student_id)
);
