
CREATE TABLE IF NOT EXISTS public.order (
    bill_item_sequence_number INTEGER,
    order_id TEXT NOT NULL,
    product_id TEXT,
    product_description TEXT NOT NULL,
    product_pricing INTEGER,
    discount_amount_type TEXT,
    discount_amount_value numeric(12,2),
    bill_type TEXT NOT NULL,
    billing_status TEXT NOT NULL,
    billing_date timestamp with time zone,
    billing_from timestamp with time zone,
    billing_to timestamp with time zone,
    billing_schedule_period_id text,
    discount_amount numeric(12,2),
    tax_amount numeric(12,2),
    final_price numeric(12,2) NOT NULL,
    student_id TEXT NOT NULL,
    student_product_id TEXT,
    billing_approval_status TEXT,
    billing_item_description JSONB NULL,
    location_id TEXT NOT NULL,
    discount_id TEXT,
    previous_bill_item_sequence_number INTEGER,
    previous_bill_item_status TEXT,
    adjustment_price numeric(12,2),
    is_latest_bill_item boolean NULL,
    price numeric(12,2),
    old_price numeric(12,2),
    billing_ratio_numerator INTEGER,
    billing_ratio_denominator INTEGER,
    bill_item_is_reviewed BOOLEAN DEFAULT FALSE,
    raw_discount_amount numeric(12,2),
    bill_item_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    bill_item_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    bill_item_deleted_at timestamp with time zone,
    order_sequence_number INTEGER,
    order_comment TEXT,
    order_status TEXT NOT NULL,
    order_type TEXT,
    student_full_name TEXT NOT NULL,
    order_is_reviewed BOOLEAN DEFAULT FALSE,
    withdrawal_effective_date timestamp with time zone,
    background TEXT,
    future_measures TEXT,
    loa_start_date timestamp with time zone,
    loa_end_date timestamp with time zone,
    order_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    order_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    order_deleted_at timestamp with time zone,
    tax_id TEXT NOT NULL,
    tax_name TEXT NOT NULL,
    tax_percentage INTEGER NOT NULL,
    tax_category TEXT NOT NULL,
    default_flag BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    tax_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    tax_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    tax_deleted_at timestamp with time zone,
    CONSTRAINT order_pk PRIMARY KEY (bill_item_sequence_number,order_id)
);

ALTER PUBLICATION kec_publication ADD TABLE public.order;
