// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: virtualclassroom/v1/zegocloud.proto

package vpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetAuthenticationTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAuthenticationTokenRequest) Reset() {
	*x = GetAuthenticationTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthenticationTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthenticationTokenRequest) ProtoMessage() {}

func (x *GetAuthenticationTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthenticationTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAuthenticationTokenRequest) Descriptor() ([]byte, []int) {
	return file_virtualclassroom_v1_zegocloud_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthenticationTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAuthenticationTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthToken string `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	AppId     int32  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSign   string `protobuf:"bytes,3,opt,name=app_sign,json=appSign,proto3" json:"app_sign,omitempty"`
}

func (x *GetAuthenticationTokenResponse) Reset() {
	*x = GetAuthenticationTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthenticationTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthenticationTokenResponse) ProtoMessage() {}

func (x *GetAuthenticationTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthenticationTokenResponse.ProtoReflect.Descriptor instead.
func (*GetAuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return file_virtualclassroom_v1_zegocloud_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthenticationTokenResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *GetAuthenticationTokenResponse) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetAuthenticationTokenResponse) GetAppSign() string {
	if x != nil {
		return x.AppSign
	}
	return ""
}

type GetAuthenticationTokenV2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAuthenticationTokenV2Request) Reset() {
	*x = GetAuthenticationTokenV2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthenticationTokenV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthenticationTokenV2Request) ProtoMessage() {}

func (x *GetAuthenticationTokenV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthenticationTokenV2Request.ProtoReflect.Descriptor instead.
func (*GetAuthenticationTokenV2Request) Descriptor() ([]byte, []int) {
	return file_virtualclassroom_v1_zegocloud_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthenticationTokenV2Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAuthenticationTokenV2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthToken string `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
}

func (x *GetAuthenticationTokenV2Response) Reset() {
	*x = GetAuthenticationTokenV2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthenticationTokenV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthenticationTokenV2Response) ProtoMessage() {}

func (x *GetAuthenticationTokenV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthenticationTokenV2Response.ProtoReflect.Descriptor instead.
func (*GetAuthenticationTokenV2Response) Descriptor() ([]byte, []int) {
	return file_virtualclassroom_v1_zegocloud_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthenticationTokenV2Response) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type GetChatConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetChatConfigRequest) Reset() {
	*x = GetChatConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatConfigRequest) ProtoMessage() {}

func (x *GetChatConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatConfigRequest.ProtoReflect.Descriptor instead.
func (*GetChatConfigRequest) Descriptor() ([]byte, []int) {
	return file_virtualclassroom_v1_zegocloud_proto_rawDescGZIP(), []int{4}
}

type GetChatConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSign string `protobuf:"bytes,2,opt,name=app_sign,json=appSign,proto3" json:"app_sign,omitempty"`
}

func (x *GetChatConfigResponse) Reset() {
	*x = GetChatConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatConfigResponse) ProtoMessage() {}

func (x *GetChatConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtualclassroom_v1_zegocloud_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatConfigResponse.ProtoReflect.Descriptor instead.
func (*GetChatConfigResponse) Descriptor() ([]byte, []int) {
	return file_virtualclassroom_v1_zegocloud_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatConfigResponse) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetChatConfigResponse) GetAppSign() string {
	if x != nil {
		return x.AppSign
	}
	return ""
}

var File_virtualclassroom_v1_zegocloud_proto protoreflect.FileDescriptor

var file_virtualclassroom_v1_zegocloud_proto_rawDesc = []byte{
	0x0a, 0x23, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f,
	0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x7a, 0x65, 0x67, 0x6f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x22, 0x38, 0x0a, 0x1d, 0x47, 0x65,
	0x74, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x70, 0x70, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x22, 0x3a, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x32, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x32, 0x88, 0x03, 0x0a, 0x10, 0x5a, 0x65,
	0x67, 0x6f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x81,
	0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x32, 0x2e, 0x76, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x87, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x32, 0x12,
	0x34, 0x2e, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x29, 0x2e,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x69, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62,
	0x75, 0x66, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72,
	0x6f, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_virtualclassroom_v1_zegocloud_proto_rawDescOnce sync.Once
	file_virtualclassroom_v1_zegocloud_proto_rawDescData = file_virtualclassroom_v1_zegocloud_proto_rawDesc
)

func file_virtualclassroom_v1_zegocloud_proto_rawDescGZIP() []byte {
	file_virtualclassroom_v1_zegocloud_proto_rawDescOnce.Do(func() {
		file_virtualclassroom_v1_zegocloud_proto_rawDescData = protoimpl.X.CompressGZIP(file_virtualclassroom_v1_zegocloud_proto_rawDescData)
	})
	return file_virtualclassroom_v1_zegocloud_proto_rawDescData
}

var file_virtualclassroom_v1_zegocloud_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_virtualclassroom_v1_zegocloud_proto_goTypes = []interface{}{
	(*GetAuthenticationTokenRequest)(nil),    // 0: virtualclassroom.v1.GetAuthenticationTokenRequest
	(*GetAuthenticationTokenResponse)(nil),   // 1: virtualclassroom.v1.GetAuthenticationTokenResponse
	(*GetAuthenticationTokenV2Request)(nil),  // 2: virtualclassroom.v1.GetAuthenticationTokenV2Request
	(*GetAuthenticationTokenV2Response)(nil), // 3: virtualclassroom.v1.GetAuthenticationTokenV2Response
	(*GetChatConfigRequest)(nil),             // 4: virtualclassroom.v1.GetChatConfigRequest
	(*GetChatConfigResponse)(nil),            // 5: virtualclassroom.v1.GetChatConfigResponse
}
var file_virtualclassroom_v1_zegocloud_proto_depIdxs = []int32{
	0, // 0: virtualclassroom.v1.ZegoCloudService.GetAuthenticationToken:input_type -> virtualclassroom.v1.GetAuthenticationTokenRequest
	2, // 1: virtualclassroom.v1.ZegoCloudService.GetAuthenticationTokenV2:input_type -> virtualclassroom.v1.GetAuthenticationTokenV2Request
	4, // 2: virtualclassroom.v1.ZegoCloudService.GetChatConfig:input_type -> virtualclassroom.v1.GetChatConfigRequest
	1, // 3: virtualclassroom.v1.ZegoCloudService.GetAuthenticationToken:output_type -> virtualclassroom.v1.GetAuthenticationTokenResponse
	3, // 4: virtualclassroom.v1.ZegoCloudService.GetAuthenticationTokenV2:output_type -> virtualclassroom.v1.GetAuthenticationTokenV2Response
	5, // 5: virtualclassroom.v1.ZegoCloudService.GetChatConfig:output_type -> virtualclassroom.v1.GetChatConfigResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_virtualclassroom_v1_zegocloud_proto_init() }
func file_virtualclassroom_v1_zegocloud_proto_init() {
	if File_virtualclassroom_v1_zegocloud_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_virtualclassroom_v1_zegocloud_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthenticationTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualclassroom_v1_zegocloud_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthenticationTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualclassroom_v1_zegocloud_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthenticationTokenV2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualclassroom_v1_zegocloud_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthenticationTokenV2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualclassroom_v1_zegocloud_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualclassroom_v1_zegocloud_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_virtualclassroom_v1_zegocloud_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_virtualclassroom_v1_zegocloud_proto_goTypes,
		DependencyIndexes: file_virtualclassroom_v1_zegocloud_proto_depIdxs,
		MessageInfos:      file_virtualclassroom_v1_zegocloud_proto_msgTypes,
	}.Build()
	File_virtualclassroom_v1_zegocloud_proto = out.File
	file_virtualclassroom_v1_zegocloud_proto_rawDesc = nil
	file_virtualclassroom_v1_zegocloud_proto_goTypes = nil
	file_virtualclassroom_v1_zegocloud_proto_depIdxs = nil
}
