{
 "title": "Dashboard is generated for Virtual Classroom service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"virtualclassroom|bob\",grpc_server_method=~\"bob.v1.LessonReaderService/GetLiveLessonState|virtualclassroom.v1.LessonRecordingService/StartRecording|virtualclassroom.v1.LessonRecordingService/GetRecordingByLessonID|virtualclassroom.v1.LessonRecordingService/GetRecordingDownloadLinkByID|virtualclassroom.v1.LessonRecordingService/StopRecording|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|virtualclassroom.v1.VirtualClassroomReaderService/RetrieveWhiteboardToken|virtualclassroom.v1.VirtualClassroomReaderService/GetLiveLessonState|virtualclassroom.v1.VirtualClassroomModifierService/EndLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/ModifyVirtualClassroomState|virtualclassroom.v1.VirtualClassroomModifierService/PreparePublish|virtualclassroom.v1.VirtualClassroomModifierService/Unpublish|virtualclassroom.v1.VirtualClassroomModifierService/JoinLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/LeaveLiveLesson|virtualclassroom.v1.LiveRoomReaderService/GetLiveRoomState|virtualclassroom.v1.LiveRoomReaderService/GetWhiteboardToken|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|bob.v1.ClassReaderService/ListStudentsByLesson|virtualclassroom.v1.VirtualLessonReaderService/GetLessons|virtualclassroom.v1.VirtualLessonReaderService/GetLiveLessonsByLocations|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonID|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonIDs|virtualclassroom.v1.LiveRoomModifierService/UnpublishLiveRoom|virtualclassroom.v1.LiveRoomModifierService/JoinLiveRoom|virtualclassroom.v1.LiveRoomModifierService/LeaveLiveRoom|virtualclassroom.v1.LiveRoomModifierService/EndLiveRoom|virtualclassroom.v1.LiveRoomModifierService/ModifyLiveRoomState|virtualclassroom.v1.LiveRoomModifierService/PreparePublishLiveRoom|virtualclassroom.v1.ZegoCloudService/GetAuthenticationToken|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassModifierService/JoinLesson|manabie.bob.Student/GetStudentProfile|manabie.bob.Course/RetrieveLiveLesson\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{ grpc_server_method=~\"bob.v1.LessonReaderService/GetLiveLessonState|virtualclassroom.v1.LessonRecordingService/StartRecording|virtualclassroom.v1.LessonRecordingService/GetRecordingByLessonID|virtualclassroom.v1.LessonRecordingService/GetRecordingDownloadLinkByID|virtualclassroom.v1.LessonRecordingService/StopRecording|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|virtualclassroom.v1.VirtualClassroomReaderService/RetrieveWhiteboardToken|virtualclassroom.v1.VirtualClassroomReaderService/GetLiveLessonState|virtualclassroom.v1.VirtualClassroomModifierService/EndLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/ModifyVirtualClassroomState|virtualclassroom.v1.VirtualClassroomModifierService/PreparePublish|virtualclassroom.v1.VirtualClassroomModifierService/Unpublish|virtualclassroom.v1.VirtualClassroomModifierService/JoinLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/LeaveLiveLesson|virtualclassroom.v1.LiveRoomReaderService/GetLiveRoomState|virtualclassroom.v1.LiveRoomReaderService/GetWhiteboardToken|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|bob.v1.ClassReaderService/ListStudentsByLesson|virtualclassroom.v1.VirtualLessonReaderService/GetLessons|virtualclassroom.v1.VirtualLessonReaderService/GetLiveLessonsByLocations|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonID|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonIDs|virtualclassroom.v1.LiveRoomModifierService/UnpublishLiveRoom|virtualclassroom.v1.LiveRoomModifierService/JoinLiveRoom|virtualclassroom.v1.LiveRoomModifierService/LeaveLiveRoom|virtualclassroom.v1.LiveRoomModifierService/EndLiveRoom|virtualclassroom.v1.LiveRoomModifierService/ModifyLiveRoomState|virtualclassroom.v1.LiveRoomModifierService/PreparePublishLiveRoom|virtualclassroom.v1.ZegoCloudService/GetAuthenticationToken|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassModifierService/JoinLesson|manabie.bob.Student/GetStudentProfile|manabie.bob.Course/RetrieveLiveLesson\", app_kubernetes_io_name=~\"virtualclassroom|bob\"}[$__rate_interval] offset $__range))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Successful request rate by methods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"virtualclassroom|bob\",grpc_server_method=~\"bob.v1.LessonReaderService/GetLiveLessonState|virtualclassroom.v1.LessonRecordingService/StartRecording|virtualclassroom.v1.LessonRecordingService/GetRecordingByLessonID|virtualclassroom.v1.LessonRecordingService/GetRecordingDownloadLinkByID|virtualclassroom.v1.LessonRecordingService/StopRecording|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|virtualclassroom.v1.VirtualClassroomReaderService/RetrieveWhiteboardToken|virtualclassroom.v1.VirtualClassroomReaderService/GetLiveLessonState|virtualclassroom.v1.VirtualClassroomModifierService/EndLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/ModifyVirtualClassroomState|virtualclassroom.v1.VirtualClassroomModifierService/PreparePublish|virtualclassroom.v1.VirtualClassroomModifierService/Unpublish|virtualclassroom.v1.VirtualClassroomModifierService/JoinLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/LeaveLiveLesson|virtualclassroom.v1.LiveRoomReaderService/GetLiveRoomState|virtualclassroom.v1.LiveRoomReaderService/GetWhiteboardToken|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|bob.v1.ClassReaderService/ListStudentsByLesson|virtualclassroom.v1.VirtualLessonReaderService/GetLessons|virtualclassroom.v1.VirtualLessonReaderService/GetLiveLessonsByLocations|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonID|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonIDs|virtualclassroom.v1.LiveRoomModifierService/UnpublishLiveRoom|virtualclassroom.v1.LiveRoomModifierService/JoinLiveRoom|virtualclassroom.v1.LiveRoomModifierService/LeaveLiveRoom|virtualclassroom.v1.LiveRoomModifierService/EndLiveRoom|virtualclassroom.v1.LiveRoomModifierService/ModifyLiveRoomState|virtualclassroom.v1.LiveRoomModifierService/PreparePublishLiveRoom|virtualclassroom.v1.ZegoCloudService/GetAuthenticationToken|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassModifierService/JoinLesson|manabie.bob.Student/GetStudentProfile|manabie.bob.Course/RetrieveLiveLesson\", grpc_server_status=\"OK\", namespace=\"$namespace\"}[$__rate_interval])) by ( grpc_server_method) / sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"virtualclassroom|bob\", namespace=\"$namespace\"}[$__rate_interval])) by ( grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "gRPC Response status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"virtualclassroom|bob\",grpc_server_method=~\"bob.v1.LessonReaderService/GetLiveLessonState|virtualclassroom.v1.LessonRecordingService/StartRecording|virtualclassroom.v1.LessonRecordingService/GetRecordingByLessonID|virtualclassroom.v1.LessonRecordingService/GetRecordingDownloadLinkByID|virtualclassroom.v1.LessonRecordingService/StopRecording|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|virtualclassroom.v1.VirtualClassroomReaderService/RetrieveWhiteboardToken|virtualclassroom.v1.VirtualClassroomReaderService/GetLiveLessonState|virtualclassroom.v1.VirtualClassroomModifierService/EndLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/ModifyVirtualClassroomState|virtualclassroom.v1.VirtualClassroomModifierService/PreparePublish|virtualclassroom.v1.VirtualClassroomModifierService/Unpublish|virtualclassroom.v1.VirtualClassroomModifierService/JoinLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/LeaveLiveLesson|virtualclassroom.v1.LiveRoomReaderService/GetLiveRoomState|virtualclassroom.v1.LiveRoomReaderService/GetWhiteboardToken|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|bob.v1.ClassReaderService/ListStudentsByLesson|virtualclassroom.v1.VirtualLessonReaderService/GetLessons|virtualclassroom.v1.VirtualLessonReaderService/GetLiveLessonsByLocations|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonID|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonIDs|virtualclassroom.v1.LiveRoomModifierService/UnpublishLiveRoom|virtualclassroom.v1.LiveRoomModifierService/JoinLiveRoom|virtualclassroom.v1.LiveRoomModifierService/LeaveLiveRoom|virtualclassroom.v1.LiveRoomModifierService/EndLiveRoom|virtualclassroom.v1.LiveRoomModifierService/ModifyLiveRoomState|virtualclassroom.v1.LiveRoomModifierService/PreparePublishLiveRoom|virtualclassroom.v1.ZegoCloudService/GetAuthenticationToken|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassModifierService/JoinLesson|manabie.bob.Student/GetStudentProfile|manabie.bob.Course/RetrieveLiveLesson\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_status) / ignoring(grpc_server_status) group_left sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"virtualclassroom|bob\", grpc_server_method=~\"bob.v1.LessonReaderService/GetLiveLessonState|virtualclassroom.v1.LessonRecordingService/StartRecording|virtualclassroom.v1.LessonRecordingService/GetRecordingByLessonID|virtualclassroom.v1.LessonRecordingService/GetRecordingDownloadLinkByID|virtualclassroom.v1.LessonRecordingService/StopRecording|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|virtualclassroom.v1.VirtualClassroomReaderService/RetrieveWhiteboardToken|virtualclassroom.v1.VirtualClassroomReaderService/GetLiveLessonState|virtualclassroom.v1.VirtualClassroomModifierService/EndLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/ModifyVirtualClassroomState|virtualclassroom.v1.VirtualClassroomModifierService/PreparePublish|virtualclassroom.v1.VirtualClassroomModifierService/Unpublish|virtualclassroom.v1.VirtualClassroomModifierService/JoinLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/LeaveLiveLesson|virtualclassroom.v1.LiveRoomReaderService/GetLiveRoomState|virtualclassroom.v1.LiveRoomReaderService/GetWhiteboardToken|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|bob.v1.ClassReaderService/ListStudentsByLesson|virtualclassroom.v1.VirtualLessonReaderService/GetLessons|virtualclassroom.v1.VirtualLessonReaderService/GetLiveLessonsByLocations|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonID|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonIDs|virtualclassroom.v1.LiveRoomModifierService/UnpublishLiveRoom|virtualclassroom.v1.LiveRoomModifierService/JoinLiveRoom|virtualclassroom.v1.LiveRoomModifierService/LeaveLiveRoom|virtualclassroom.v1.LiveRoomModifierService/EndLiveRoom|virtualclassroom.v1.LiveRoomModifierService/ModifyLiveRoomState|virtualclassroom.v1.LiveRoomModifierService/PreparePublishLiveRoom|virtualclassroom.v1.ZegoCloudService/GetAuthenticationToken|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassModifierService/JoinLesson|manabie.bob.Student/GetStudentProfile|manabie.bob.Course/RetrieveLiveLesson\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P90)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_name=~\"virtualclassroom|bob\",grpc_server_method=~\"bob.v1.LessonReaderService/GetLiveLessonState|virtualclassroom.v1.LessonRecordingService/StartRecording|virtualclassroom.v1.LessonRecordingService/GetRecordingByLessonID|virtualclassroom.v1.LessonRecordingService/GetRecordingDownloadLinkByID|virtualclassroom.v1.LessonRecordingService/StopRecording|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|virtualclassroom.v1.VirtualClassroomReaderService/RetrieveWhiteboardToken|virtualclassroom.v1.VirtualClassroomReaderService/GetLiveLessonState|virtualclassroom.v1.VirtualClassroomModifierService/EndLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/ModifyVirtualClassroomState|virtualclassroom.v1.VirtualClassroomModifierService/PreparePublish|virtualclassroom.v1.VirtualClassroomModifierService/Unpublish|virtualclassroom.v1.VirtualClassroomModifierService/JoinLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/LeaveLiveLesson|virtualclassroom.v1.LiveRoomReaderService/GetLiveRoomState|virtualclassroom.v1.LiveRoomReaderService/GetWhiteboardToken|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|bob.v1.ClassReaderService/ListStudentsByLesson|virtualclassroom.v1.VirtualLessonReaderService/GetLessons|virtualclassroom.v1.VirtualLessonReaderService/GetLiveLessonsByLocations|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonID|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonIDs|virtualclassroom.v1.LiveRoomModifierService/UnpublishLiveRoom|virtualclassroom.v1.LiveRoomModifierService/JoinLiveRoom|virtualclassroom.v1.LiveRoomModifierService/LeaveLiveRoom|virtualclassroom.v1.LiveRoomModifierService/EndLiveRoom|virtualclassroom.v1.LiveRoomModifierService/ModifyLiveRoomState|virtualclassroom.v1.LiveRoomModifierService/PreparePublishLiveRoom|virtualclassroom.v1.ZegoCloudService/GetAuthenticationToken|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassModifierService/JoinLesson|manabie.bob.Student/GetStudentProfile|manabie.bob.Course/RetrieveLiveLesson\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method, db))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_name=~\"virtualclassroom|bob\",grpc_server_method=~\"bob.v1.LessonReaderService/GetLiveLessonState|virtualclassroom.v1.LessonRecordingService/StartRecording|virtualclassroom.v1.LessonRecordingService/GetRecordingByLessonID|virtualclassroom.v1.LessonRecordingService/GetRecordingDownloadLinkByID|virtualclassroom.v1.LessonRecordingService/StopRecording|bob.v1.CourseReaderService/ListCourses|bob.v1.CourseReaderService/ListLessonMedias|virtualclassroom.v1.VirtualClassroomReaderService/RetrieveWhiteboardToken|virtualclassroom.v1.VirtualClassroomReaderService/GetLiveLessonState|virtualclassroom.v1.VirtualClassroomModifierService/EndLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/ModifyVirtualClassroomState|virtualclassroom.v1.VirtualClassroomModifierService/PreparePublish|virtualclassroom.v1.VirtualClassroomModifierService/Unpublish|virtualclassroom.v1.VirtualClassroomModifierService/JoinLiveLesson|virtualclassroom.v1.VirtualClassroomModifierService/LeaveLiveLesson|virtualclassroom.v1.LiveRoomReaderService/GetLiveRoomState|virtualclassroom.v1.LiveRoomReaderService/GetWhiteboardToken|bob.v1.LessonModifierService/ModifyLiveLessonState|bob.v1.LessonModifierService/PreparePublish|bob.v1.LessonModifierService/Unpublish|bob.v1.ClassReaderService/ListStudentsByLesson|virtualclassroom.v1.VirtualLessonReaderService/GetLessons|virtualclassroom.v1.VirtualLessonReaderService/GetLiveLessonsByLocations|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonID|virtualclassroom.v1.VirtualLessonReaderService/GetLearnersByLessonIDs|virtualclassroom.v1.LiveRoomModifierService/UnpublishLiveRoom|virtualclassroom.v1.LiveRoomModifierService/JoinLiveRoom|virtualclassroom.v1.LiveRoomModifierService/LeaveLiveRoom|virtualclassroom.v1.LiveRoomModifierService/EndLiveRoom|virtualclassroom.v1.LiveRoomModifierService/ModifyLiveRoomState|virtualclassroom.v1.LiveRoomModifierService/PreparePublishLiveRoom|virtualclassroom.v1.ZegoCloudService/GetAuthenticationToken|bob.v1.ClassModifierService/LeaveLesson|bob.v1.ClassModifierService/EndLiveLesson|bob.v1.ClassModifierService/JoinLesson|manabie.bob.Student/GetStudentProfile|manabie.bob.Course/RetrieveLiveLesson\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method, db))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",pod=~\"^(virtualclassroom|bob).+\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(virtualclassroom|bob).+\",namespace=\"$namespace\",unit=\"byte\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(virtualclassroom|bob).+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(virtualclassroom|bob).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(virtualclassroom|bob).+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"^(virtualclassroom|bob).+\",namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(virtualclassroom|bob).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(virtualclassroom|bob).+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(virtualclassroom|bob).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(virtualclassroom|bob).+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"^(virtualclassroom|bob).+\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Business statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Number of active rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(backend_virtual_classroom_active_rooms_total{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\"})",
     "legendFormat": "active rooms"
    }
   ]
  },
  {
   "title": "Number of rooms with \"update\" room state requests",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"10\"}[$__range]))",
     "legendFormat": "Number of rooms have from 0 to 10 request"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\",app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"20\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"10\"}[$__range])))",
     "legendFormat": "(10, 20]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"50\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"20\"}[$__range])))",
     "legendFormat": "(20, 50]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"100\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"50\"}[$__range])))",
     "legendFormat": "(50, 100]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"200\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"100\"}[$__range])))",
     "legendFormat": "(100, 200]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"200\"}[$__range])))",
     "legendFormat": "(200, 500]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_handled_total_count{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range]))",
     "legendFormat": "> 500"
    }
   ]
  },
  {
   "title": "Number of rooms with \"get\" room state requests",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"update_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"10\"}[$__range]))",
     "legendFormat": "Number of rooms have from 0 to 10 request"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"100\"}[$__range])))",
     "legendFormat": "(100, 500]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"1000\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"500\"}[$__range])))",
     "legendFormat": "(500, 1000]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"3000\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"1000\"}[$__range])))",
     "legendFormat": "(1000, 3000]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"5000\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"3000\"}[$__range])))",
     "legendFormat": "(3000, 5000]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"7000\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"5000\"}[$__range])))",
     "legendFormat": "(5000, 7000]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_handled_total_count{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\"}[$__range])) - sum(increase(backend_virtual_classroom_handled_total_bucket{action=\"get_room_state\", app_kubernetes_io_name=~\"bob|virtualclassroom\", namespace=\"$namespace\", le=\"7000\"}[$__range]))",
     "legendFormat": "> 7000"
    }
   ]
  },
  {
   "title": "Number of rooms with total \"attendees\" who really joined",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"5\"}[$__range]))",
     "legendFormat": "Number of rooms have from 0 to 5 attendees"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range])) -\n              sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"5\"}[$__range])))",
     "legendFormat": "(5, 10]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"15\"}[$__range]))\n              - sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range])))",
     "legendFormat": "(10, 15]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range]))\n              - sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"15\"}[$__range])))",
     "legendFormat": "(15, 20]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range]))\n              - sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range])))",
     "legendFormat": "(20, 40]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_attendees_total_count{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\",}[$__range])) -\n              sum(increase(backend_virtual_classroom_attendees_total_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range]))",
     "legendFormat": "> 40"
    }
   ]
  },
  {
   "title": "Number of rooms with total real \"live time\"",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range]))",
     "legendFormat": "Number of rooms have real live time from 0 to 10 mins"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range])) - sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{ namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"10\"}[$__range])))",
     "legendFormat": "(10, 20]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range]))\n              - sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"20\"}[$__range])))",
     "legendFormat": "(20, 40]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"60\"}[$__range]))\n              - sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"40\"}[$__range])))",
     "legendFormat": "(40, 60]"
    },
    {
     "expr": "(sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"90\"}[$__range]))\n              - sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"60\"}[$__range])))",
     "legendFormat": "(60, 90]"
    },
    {
     "expr": "sum(increase(backend_virtual_classroom_total_real_live_time_minutes_count{namespace=\"$namespace\", app_kubernetes_io_name=~\"bob|virtualclassroom\"}[$__range])) -\n              sum(increase(backend_virtual_classroom_total_real_live_time_minutes_bucket{namespace=\"$namespace\",app_kubernetes_io_name=~\"bob|virtualclassroom\", le=\"90\"}[$__range]))",
     "legendFormat": "> 90"
    }
   ]
  }
 ]
}