{
 "title": "Dashboard is generated for entryexitmgmt service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"entryexitmgmt\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{ grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\", app_kubernetes_io_name=~\"entryexitmgmt\"}[$__rate_interval] offset $__range))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Successful request rate by methods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"entryexitmgmt\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\", grpc_server_status=\"OK\", namespace=\"$namespace\"}[$__rate_interval])) by ( grpc_server_method) / sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"entryexitmgmt\", namespace=\"$namespace\"}[$__rate_interval])) by ( grpc_server_method)",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "gRPC Response status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"entryexitmgmt\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\",namespace=\"$namespace\"}[$__rate_interval])) by (grpc_server_status) / ignoring(grpc_server_status) group_left sum(rate(grpc_io_server_completed_rpcs{app_kubernetes_io_name=~\"entryexitmgmt\", grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P90)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_name=~\"entryexitmgmt\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method, db))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Latency by Method (P95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{app_kubernetes_io_name=~\"entryexitmgmt\",grpc_server_method!~\"grpc.health.v1.Health/Check|.+TopicIcon.+\",namespace=\"$namespace\"}[$__rate_interval])) by (le, grpc_server_method, db))",
     "legendFormat": "{{ grpc_server_method }}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",pod=~\"^(entryexitmgmt).+\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(entryexitmgmt).+\",namespace=\"$namespace\",unit=\"byte\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(entryexitmgmt).+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(entryexitmgmt).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(entryexitmgmt).+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"^(entryexitmgmt).+\",namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(entryexitmgmt).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(entryexitmgmt).+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(entryexitmgmt).+\",namespace=\"$namespace\",unit=\"core\"}) /\n                   count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(entryexitmgmt).+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"^(entryexitmgmt).+\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}