CREATE DATABASE alloydb;
CREATE DATABASE aphelios;
CREATE DATABASE bob;
CREATE DATABASE bob_hasura_metadata;
CREATE DATABASE calendar;
CREATE DATABASE draft;
CREATE DATABASE draft_hasura_metadata;
CREATE DATABASE entryexitmgmt;
CREATE DATABASE eureka;
CREATE DATABASE eureka_hasura_metadata;
CREATE DATABASE fatima;
CREATE DATABASE fatima_hasura_metadata;
CREATE DATABASE invoicemgmt;
CREATE DATABASE mastermgmt;
CREATE DATABASE mlflow;
CREATE DATABASE nats;
CREATE DATABASE timesheet;
CREATE DATABASE tom;
CREATE DATABASE unleash;
CREATE DATABASE unleashv2;
CREATE DATABASE zeus;
CREATE DATABASE zeus_hasura_metadata;
CREATE DATABASE lessonmgmt;
CREATE DATABASE notificationmgmt;
CREATE DATABASE auth;
CREATE DATABASE auth_hasura_metadata;

CREATE USER "aphelios" WITH PASSWORD 'example';
CREATE USER "bob" WITH PASSWORD 'example';
CREATE USER "bob_hasura" WITH PASSWORD 'example';
CREATE USER "calendar" WITH PASSWORD 'example';
CREATE USER "draft" WITH PASSWORD 'example';
CREATE USER "draft_hasura" WITH PASSWORD 'example';
CREATE USER "elasticsearch" WITH PASSWORD 'example';
CREATE USER "enigma" WITH PASSWORD 'example';
CREATE USER "entryexitmgmt" WITH PASSWORD 'example';
CREATE USER "eureka" WITH PASSWORD 'example';
CREATE USER "eureka_hasura" WITH PASSWORD 'example';
CREATE USER "fatima" WITH PASSWORD 'example';
CREATE USER "fatima_hasura" WITH PASSWORD 'example';
CREATE USER "hasura" WITH PASSWORD 'example';
CREATE USER "hephaestus" WITH PASSWORD 'example';
CREATE USER "invoicemgmt" WITH PASSWORD 'example';
CREATE USER "j4" WITH PASSWORD 'example';
CREATE USER "kafka_connector" REPLICATION PASSWORD 'example';
CREATE USER "lessonmgmt" WITH PASSWORD 'example';
CREATE USER "mastermgmt" WITH PASSWORD 'example';
CREATE USER "nats-jetstream" WITH PASSWORD 'example';
CREATE USER "notificationmgmt" WITH PASSWORD 'example';
CREATE USER "payment" WITH PASSWORD 'example';
CREATE USER "shamir" WITH PASSWORD 'example';
CREATE USER "timesheet" WITH PASSWORD 'example';
CREATE USER "tom" WITH PASSWORD 'example';
CREATE USER "unleash" WITH PASSWORD 'example';
CREATE USER "unleashv2" WITH PASSWORD 'example';
CREATE USER "usermgmt" WITH PASSWORD 'example';
CREATE USER "virtualclassroom" WITH PASSWORD 'example';
CREATE USER "yasuo" WITH PASSWORD 'example';
CREATE USER "zeus" WITH PASSWORD 'example';
CREATE USER "zeus_hasura" WITH PASSWORD 'example';
CREATE USER "conversationmgmt" WITH PASSWORD 'example';
CREATE USER "spike" WITH PASSWORD 'example';
CREATE USER "discount" WITH PASSWORD 'example';
CREATE USER "auth" WITH PASSWORD 'example';
CREATE USER "auth_hasura" WITH PASSWORD 'example';

-- grant permission for hasura user to create schema hdb_catalog
GRANT ALL PRIVILEGES ON DATABASE "bob" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "calendar" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "entryexitmgmt" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "eureka" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "fatima" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "invoicemgmt" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "mastermgmt" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "timesheet" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "lessonmgmt" TO hasura;
GRANT ALL PRIVILEGES ON DATABASE "auth" TO hasura;

GRANT CREATE ON DATABASE "bob_hasura_metadata" TO bob_hasura;
GRANT CREATE ON DATABASE "draft_hasura_metadata" TO draft_hasura;
GRANT CREATE ON DATABASE "eureka_hasura_metadata" TO eureka_hasura;
GRANT CREATE ON DATABASE "fatima_hasura_metadata" TO fatima_hasura;
GRANT CREATE ON DATABASE "zeus_hasura_metadata" TO zeus_hasura;
GRANT CREATE ON DATABASE "auth_hasura_metadata" TO auth_hasura;

GRANT CREATE, CONNECT, TEMPORARY, TEMP ON DATABASE "unleash" TO unleash;
GRANT CREATE, CONNECT, TEMPORARY, TEMP ON DATABASE "unleashv2" TO unleashv2;

\connect unleash;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO unleash;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO unleash;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO unleash;
GRANT CREATE, USAGE ON SCHEMA public TO unleash;

\connect unleashv2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO unleashv2;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO unleashv2;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO unleashv2;
GRANT CREATE, USAGE ON SCHEMA public TO unleashv2;

\connect bob;
GRANT USAGE ON SCHEMA public TO bob;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO bob;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO bob;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO bob;

GRANT USAGE ON SCHEMA public TO draft;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO draft;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO draft;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO draft;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO draft;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO draft;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO draft;

GRANT USAGE ON SCHEMA public TO enigma;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO enigma;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO enigma;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO enigma;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO enigma;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO enigma;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO enigma;

GRANT USAGE ON SCHEMA public TO entryexitmgmt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO entryexitmgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO entryexitmgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO entryexitmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO entryexitmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO entryexitmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO entryexitmgmt;

GRANT USAGE ON SCHEMA public TO lessonmgmt;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO lessonmgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO lessonmgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO lessonmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO lessonmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO lessonmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO lessonmgmt;

GRANT USAGE ON SCHEMA public TO mastermgmt;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO mastermgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO mastermgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO mastermgmt;

GRANT USAGE ON SCHEMA public TO notificationmgmt;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO notificationmgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO notificationmgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO notificationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO notificationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO notificationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO notificationmgmt;

GRANT USAGE ON SCHEMA public TO payment;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO payment;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO payment;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO payment;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO payment;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO payment;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO payment;

GRANT USAGE ON SCHEMA public TO usermgmt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO usermgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO usermgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO usermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO usermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO usermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO usermgmt;

GRANT USAGE ON SCHEMA public TO virtualclassroom;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO virtualclassroom;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO virtualclassroom;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO virtualclassroom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO virtualclassroom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO virtualclassroom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO virtualclassroom;

GRANT USAGE ON SCHEMA public TO yasuo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO yasuo;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO yasuo;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO yasuo;

GRANT USAGE ON SCHEMA public TO calendar;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO calendar;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO calendar;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO calendar;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO calendar;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO calendar;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO calendar;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON TABLES TO shamir;
ALTER ROLE shamir BYPASSRLS;
ALTER ROLE hasura BYPASSRLS;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

GRANT USAGE ON SCHEMA public TO bob_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO bob_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO bob_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO bob_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO bob_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO bob_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO bob_hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO j4;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO j4;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO j4;
ALTER ROLE j4 BYPASSRLS;

\connect bob_hasura_metadata;
GRANT USAGE ON SCHEMA public TO bob_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO bob_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO bob_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO bob_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO bob_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO bob_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO bob_hasura;

\connect eureka;
GRANT USAGE ON SCHEMA public TO eureka;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to eureka;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO eureka;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO eureka;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO eureka;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO eureka;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO eureka;

GRANT USAGE ON SCHEMA public TO bob;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public to bob;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO bob;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO bob;

GRANT USAGE ON SCHEMA public TO usermgmt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO usermgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO usermgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO usermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO usermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO usermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO usermgmt;

GRANT USAGE ON SCHEMA public TO mastermgmt;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public to mastermgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO mastermgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO mastermgmt;

GRANT USAGE ON SCHEMA public TO yasuo;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public to yasuo;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO yasuo;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO yasuo;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO eureka_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO eureka_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO eureka_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO eureka_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO eureka_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO eureka_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO eureka_hasura;

\connect eureka_hasura_metadata;
GRANT USAGE ON SCHEMA public TO eureka_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO eureka_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO eureka_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO eureka_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO eureka_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO eureka_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO eureka_hasura;

\connect fatima;
GRANT USAGE ON SCHEMA public TO fatima;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to fatima;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO fatima;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO fatima;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fatima;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO fatima;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO fatima;

GRANT USAGE ON SCHEMA public TO payment;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to payment;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO payment;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO payment;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO payment;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO payment;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO payment;

GRANT USAGE ON SCHEMA public TO discount;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO discount;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO discount;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO discount;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO discount;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO discount;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO discount;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO fatima_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO fatima_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO fatima_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO fatima_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO fatima_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO fatima_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO fatima_hasura;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;

\connect fatima_hasura_metadata;
GRANT USAGE ON SCHEMA public TO fatima_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO fatima_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO fatima_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO fatima_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO fatima_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO fatima_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO fatima_hasura;


\connect tom;
GRANT USAGE ON SCHEMA public TO tom;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to tom;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO tom;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO tom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, DELETE, UPDATE ON TABLES TO tom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO tom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO tom;

GRANT USAGE ON SCHEMA public TO conversationmgmt;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO conversationmgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO conversationmgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO conversationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO conversationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO conversationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO conversationmgmt;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO j4;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO j4;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO j4;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;

\connect invoicemgmt;
GRANT USAGE ON SCHEMA public TO invoicemgmt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO invoicemgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO invoicemgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO invoicemgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO invoicemgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO invoicemgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO invoicemgmt;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;

\connect timesheet;
GRANT USAGE ON SCHEMA public TO timesheet;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO timesheet;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO timesheet;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO timesheet;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO timesheet;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO timesheet;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO timesheet;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;

\connect mastermgmt;
GRANT USAGE ON SCHEMA public TO mastermgmt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mastermgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO mastermgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO mastermgmt;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

CREATE SCHEMA IF NOT EXISTS manabie;
GRANT USAGE ON SCHEMA manabie TO mastermgmt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA manabie TO mastermgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA manabie TO mastermgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA manabie TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA manabie GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA manabie GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO mastermgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA manabie GRANT EXECUTE ON FUNCTIONS TO mastermgmt;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA manabie TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA manabie TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA manabie GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;

\connect alloydb;
-- schema bob
CREATE SCHEMA bob;
GRANT CREATE, USAGE ON SCHEMA bob TO hephaestus;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bob to hephaestus;
ALTER DEFAULT PRIVILEGES IN SCHEMA bob GRANT ALL PRIVILEGES ON TABLES TO hephaestus;

\connect lessonmgmt;
GRANT USAGE ON SCHEMA public TO bob;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO bob;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO bob;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO bob;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO bob;

GRANT USAGE ON SCHEMA public TO lessonmgmt;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO lessonmgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO lessonmgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO lessonmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lessonmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO lessonmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO lessonmgmt;

GRANT USAGE ON SCHEMA public TO calendar;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO calendar;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO calendar;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO calendar;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO calendar;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO calendar;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO calendar;

GRANT USAGE ON SCHEMA public TO virtualclassroom;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO virtualclassroom;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO virtualclassroom;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO virtualclassroom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO virtualclassroom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO virtualclassroom;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO virtualclassroom;

GRANT USAGE ON SCHEMA public TO yasuo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO yasuo;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO yasuo;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO yasuo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO yasuo;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;

\connect notificationmgmt;

GRANT USAGE ON SCHEMA public TO spike;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO spike;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO spike;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO spike;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO spike;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO spike;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO spike;

\connect auth;

GRANT USAGE ON SCHEMA public TO shamir;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO shamir;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO shamir;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO shamir;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO shamir;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO shamir;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO shamir;

GRANT USAGE ON SCHEMA public TO auth;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO auth;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO auth;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO auth;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO auth;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO auth;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO auth;

GRANT USAGE ON SCHEMA public TO hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO hasura;

GRANT USAGE ON SCHEMA public TO auth_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO auth_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO auth_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO auth_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO auth_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO auth_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO auth_hasura;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

\connect auth_hasura_metadata;

GRANT USAGE ON SCHEMA public TO auth_hasura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO auth_hasura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO auth_hasura;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO auth_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO auth_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO auth_hasura;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO auth_hasura;
