\connect notificationmgmt;

GRANT USAGE ON SCHEMA public TO notificationmgmt;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO notificationmgmt;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO notificationmgmt;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO notificationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO notificationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO notificationmgmt;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO notificationmgmt;

ALTER ROLE kafka_connector BYPASSRLS;
GRANT USAGE ON SCHEMA public TO kafka_connector;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO kafka_connector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO kafka_connector;

GRANT USAGE ON SCHEMA public TO hephaestus;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO hephaestus;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO hephaestus;