// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"
	"time"

	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
	"github.com/manabie-com/backend/internal/lessonmgmt/modules/allocation/domain"
)

type MockLessonAllocationRepo struct {
	mock.Mock
}

func (r *MockLessonAllocationRepo) CountAssignedSlotPerStudentCourse(arg1 context.Context, arg2 database.QueryExecer, arg3 string, arg4 string) (uint32, error) {
	args := r.Called(arg1, arg2, arg3, arg4)
	return args.Get(0).(uint32), args.Error(1)
}

func (r *MockLessonAllocationRepo) CountPurchasedSlotPerStudentSubscription(arg1 context.Context, arg2 database.QueryExecer, arg3 uint8, arg4 time.Time, arg5 time.Time, arg6 string, arg7 string, arg8 string) (uint32, error) {
	args := r.Called(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	return args.Get(0).(uint32), args.Error(1)
}

func (r *MockLessonAllocationRepo) GetByStudentSubscriptionAndWeek(arg1 context.Context, arg2 database.QueryExecer, arg3 string, arg4 string, arg5 []string) (map[string][]*domain.LessonAllocationInfo, error) {
	args := r.Called(arg1, arg2, arg3, arg4, arg5)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(map[string][]*domain.LessonAllocationInfo), args.Error(1)
}

func (r *MockLessonAllocationRepo) GetLessonAllocation(arg1 context.Context, arg2 database.QueryExecer, arg3 domain.LessonAllocationFilter) ([]*domain.AllocatedStudent, map[string]uint32, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Get(1).(map[string]uint32), args.Error(2)
	}
	return args.Get(0).([]*domain.AllocatedStudent), args.Get(1).(map[string]uint32), args.Error(2)
}
