{
 "title": "JetStream using Thanos",
 "description": "NATS JetStream Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "UAT : staging, Staging : staging-2, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jetstream_server_total_streams{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(jetstream_server_total_streams{gke_cluster=\"$cluster\", namespace=~\"$namespace\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(jetstream_stream_last_seq{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\"}, stream_name)"
    }
   },
   {
    "name": "consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(jetstream_consumer_num_pending{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\"}, consumer_name)"
    }
   },
   {
    "name": "gcp_project",
    "label": "GCP Project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gnatsd_varz_jetstream_stats_storage{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\"})/sum(gnatsd_varz_jetstream_config_max_storage{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gnatsd_varz_jetstream_stats_storage{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gnatsd_varz_connections{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gnatsd_varz_jetstream_config_max_storage{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jetstream_server_total_consumers{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", is_meta_leader=\"true\"})"
    }
   ]
  },
  { "title": "Stream metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Stream data size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jetstream_stream_total_bytes{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream message count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jetstream_stream_total_messages{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\", is_stream_leader=\"true\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m/s" } },
   "yaxes": [
    { "format": "m/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetstream_stream_total_messages{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\", is_stream_leader=\"true\"}[5m])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total delivered messages",
   "type": "graph",
   "description": "Latest sequence number of a stream consumer.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jetstream_consumer_delivered_consumer_seq{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\", consumer_name=~\"$consumer\", is_consumer_leader=\"true\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Pending messages",
   "type": "graph",
   "description": "Number of pending messages from a consumer (i.e. messages that are waiting to be sent to the consumer).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jetstream_consumer_num_pending{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\", consumer_name=~\"$consumer\", is_consumer_leader=\"true\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Acks Pending",
   "type": "graph",
   "description": "Number of pending acks from a consumer (i.e. messages that have been sent to the consumer but not acknowledged by the consumer yet).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jetstream_consumer_num_ack_pending{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\", consumer_name=~\"$consumer\", is_consumer_leader=\"true\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Redelivered messages",
   "type": "graph",
   "description": "Number of redelivered messages from a consumer.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jetstream_consumer_num_redelivered{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\", is_consumer_leader=\"true\"}) by (stream_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Consumer count",
   "type": "graph",
   "description": "Total number of consumers from a stream",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jetstream_stream_consumer_count{gke_cluster=\"$cluster\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$server\", stream_name=~\"$stream\", is_stream_leader=\"true\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "[WIP] Log entry count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.namespace_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.label.namespace_name",
       "=~",
       ".+nats-jetstream",
       "AND",
       "resource.label.container_name",
       "=",
       "nats-jetstream"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.namespace_name"
      ],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/log_entry_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$gcp_project",
      "query": "",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}