// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
	"github.com/manabie-com/backend/internal/usermgmt/modules/user/core/entity"
)

type MockDomainSchoolRepo struct {
	mock.Mock
}

func (r *MockDomainSchoolRepo) GetByIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 []string) (entity.DomainSchools, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(entity.DomainSchools), args.Error(1)
}

func (r *MockDomainSchoolRepo) GetByIDsAndGradeID(arg1 context.Context, arg2 database.QueryExecer, arg3 []string, arg4 string) (entity.DomainSchools, error) {
	args := r.Called(arg1, arg2, arg3, arg4)
	return args.Get(0).(entity.DomainSchools), args.Error(1)
}

func (r *MockDomainSchoolRepo) GetByPartnerInternalIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 []string) (entity.DomainSchools, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(entity.DomainSchools), args.Error(1)
}
