{
 "title": "Kubernetes Monitoring Overview",
 "description": "Dashboard for Kubernetes cluster with Prometheus.",
 "tags": [
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "UAT : staging, Staging : staging-2, JPREP : production, JP-Partners : jp-partners, Tokyo : tokyo"
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_info{gke_cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{gke_cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{gke_cluster=\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Nodes base CPU usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (node) (irate(node_cpu_seconds_total{gke_cluster=\"$cluster\", mode=\"idle\",node=~\"^$Node$\",job=\"kubernetes-service-endpoints\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "Node base Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{gke_cluster=\"$cluster\", id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname)/ on (kubernetes_io_hostname) machine_memory_bytes{gke_cluster=\"$cluster\", kubernetes_io_hostname=~\"^$Node$\"}"
    }
   ]
  },
  {
   "title": "Pods based CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{gke_cluster=\"$cluster\", image!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$namespace$\", container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods based Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{gke_cluster=\"$cluster\", container!=\"\",kubernetes_io_hostname=~\"$Node\", namespace=~\"^$namespace$\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Control Plane Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(up{gke_cluster=\"$cluster\", job=~\"kubernetes-apiservers|kube-scheduler|kube-controller-manager\"} == 0)"
    }
   ]
  },
  {
   "title": "Node Unschedulable",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{gke_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{gke_cluster=\"$cluster\", node=~\"$Node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_condition{gke_cluster=\"$cluster\", condition=\"Ready\", node=~\"$Node\", status!=\"true\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "CPU Requested ($Node)",
   "type": "gauge",
   "description": "requested cores / all capacity cores",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{gke_cluster=\"$cluster\", node=~\"^$Node$\",resource=\"cpu\"}) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Requeted ($Node)",
   "type": "gauge",
   "description": "requested mem/all capacity mem",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{gke_cluster=\"$cluster\", node=~\"^$Node$\",resource=\"memory\"}) / sum (machine_memory_bytes{gke_cluster=\"$cluster\", kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{gke_cluster=\"$cluster\", condition=\"DiskPressure\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{gke_cluster=\"$cluster\", condition=\"NetworkUnavailable\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{gke_cluster=\"$cluster\", condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{gke_cluster=\"$cluster\", condition=\"MemoryPressure\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{gke_cluster=\"$cluster\", condition=\"PIDPressure\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Pod Usage ($Node)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_info{gke_cluster=\"$cluster\", node=~\"^$Node$\"})) * 100 / (sum(kube_node_info) * 110)"
    }
   ]
  },
  {
   "title": "CPU Usage ($Node)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{gke_cluster=\"$cluster\", mode=\"idle\",node=~\"^$Node$\",job=\"kubernetes-service-endpoints\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Mem Usage ($Node)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1- ((avg_over_time(node_memory_MemFree_bytes{gke_cluster=\"$cluster\", node=~\"^$Node$\", job=\"kubernetes-service-endpoints\"}[5m]) + avg_over_time(node_memory_Cached_bytes{gke_cluster=\"$cluster\", node=~\"^$Node$\", job=\"kubernetes-service-endpoints\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{gke_cluster=\"$cluster\", node=~\"^$Node$\",job=\"kubernetes-service-endpoints\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{gke_cluster=\"$cluster\", node=~\"^$Node$\",job=\"kubernetes-service-endpoints\"}[5m])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage ($Node)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{gke_cluster=\"$cluster\", mountpoint=\"/\",fstype!=\"rootfs\",node=~\"^$Node$\",job=\"kubernetes-service-endpoints\"} * 100) / node_filesystem_size_bytes{gke_cluster=\"$cluster\", mountpoint=\"/\",fstype!=\"rootfs\",node=~\"^$Node$\",job=\"kubernetes-service-endpoints\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{gke_cluster=\"$cluster\", node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Capacity pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{gke_cluster=\"$cluster\"}) * 110"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{gke_cluster=\"$cluster\", id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{gke_cluster=\"$cluster\", node=~\"^$Node$\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{gke_cluster=\"$cluster\", kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{gke_cluster=\"$cluster\", id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{gke_cluster=\"$cluster\", node=~\"^$Node$\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{gke_cluster=\"$cluster\", kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{gke_cluster=\"$cluster\", device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{gke_cluster=\"$cluster\", device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Top projects and pods usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Top 10 project based on CPU requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kube_pod_container_resource_requests{gke_cluster=\"$cluster\", resource=\"cpu\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top 10 project based on mem request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kube_pod_container_resource_requests{gke_cluster=\"$cluster\", resource=\"memory\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Container restart",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{gke_cluster=\"$cluster\"}[$__rate_interval]) > 0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Apiserver request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{gke_cluster=\"$cluster\"}[$__rate_interval])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API server total requests code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_total{gke_cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Apiserver request latency",
   "type": "graph",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{gke_cluster=\"$cluster\", verb!~\"CONNECT|WATCH\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{gke_cluster=\"$cluster\", verb!~\"CONNECT|WATCH\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{gke_cluster=\"$cluster\", verb!~\"CONNECT|WATCH\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 "
    }
   ]
  },
  {
   "title": "Workqueue service time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "s", "label": "service time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Etcd request latency",
   "type": "graph",
   "description": "etcd request latency (p95)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Workqueue processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{gke_cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Nodes network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{gke_cluster=\"$cluster\", image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_role)",
     "legendFormat": "-> {{ kubernetes_io_role }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{gke_cluster=\"$cluster\", image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_role)",
     "legendFormat": "<- {{ kubernetes_io_role }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{gke_cluster=\"$cluster\", image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_role,kubernetes_io_hostname)",
     "legendFormat": "-> {{ kubernetes_io_role }}: {{ kubernetes_io_hostname }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{gke_cluster=\"$cluster\", image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_role,kubernetes_io_hostname)",
     "legendFormat": "<- {{ kubernetes_io_role }}: {{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{gke_cluster=\"$cluster\", image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{gke_cluster=\"$cluster\", image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{gke_cluster=\"$cluster\", kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{gke_cluster=\"$cluster\", kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}