/*
  ____            _   _           _
 / ___|   _   _  | | | |   __ _  | |__    _   _   ___
 \___ \  | | | | | | | |  / _` | | '_ \  | | | | / __|
  ___) | | |_| | | | | | | (_| | | |_) | | |_| | \__ \
 |____/   \__, | |_| |_|  \__,_| |_.__/   \__,_| |___/
          |___/

*/
// * Code generated by protoc-gen-syllabus. DO NOT EDIT.
// * versions:
// * - protoc-gen-syllabus (devel)
// * - protoc                   v3.14.0
// * source: common

package scpb

func (x UserGroup) FromString(str string) UserGroup {
	switch str {
	case UserGroup_USER_GROUP_NONE.String():
		return UserGroup_USER_GROUP_NONE
	case UserGroup_USER_GROUP_STUDENT.String():
		return UserGroup_USER_GROUP_STUDENT
	case UserGroup_USER_GROUP_COACH.String():
		return UserGroup_USER_GROUP_COACH
	case UserGroup_USER_GROUP_TUTOR.String():
		return UserGroup_USER_GROUP_TUTOR
	case UserGroup_USER_GROUP_STAFF.String():
		return UserGroup_USER_GROUP_STAFF
	case UserGroup_USER_GROUP_ADMIN.String():
		return UserGroup_USER_GROUP_ADMIN
	case UserGroup_USER_GROUP_TEACHER.String():
		return UserGroup_USER_GROUP_TEACHER
	case UserGroup_USER_GROUP_PARENT.String():
		return UserGroup_USER_GROUP_PARENT
	case UserGroup_USER_GROUP_CONTENT_ADMIN.String():
		return UserGroup_USER_GROUP_CONTENT_ADMIN
	case UserGroup_USER_GROUP_CONTENT_STAFF.String():
		return UserGroup_USER_GROUP_CONTENT_STAFF
	case UserGroup_USER_GROUP_SALES_ADMIN.String():
		return UserGroup_USER_GROUP_SALES_ADMIN
	case UserGroup_USER_GROUP_SALES_STAFF.String():
		return UserGroup_USER_GROUP_SALES_STAFF
	case UserGroup_USER_GROUP_CS_ADMIN.String():
		return UserGroup_USER_GROUP_CS_ADMIN
	case UserGroup_USER_GROUP_CS_STAFF.String():
		return UserGroup_USER_GROUP_CS_STAFF
	case UserGroup_USER_GROUP_SCHOOL_ADMIN.String():
		return UserGroup_USER_GROUP_SCHOOL_ADMIN
	case UserGroup_USER_GROUP_SCHOOL_STAFF.String():
		return UserGroup_USER_GROUP_SCHOOL_STAFF
	}
	return UserGroup(0)
}
