// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"
	"time"

	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
	"github.com/manabie-com/backend/internal/timesheet/domain/dto"
)

type MockTimesheetLocationListRepoImpl struct {
	mock.Mock
}

func (r *MockTimesheetLocationListRepoImpl) GetNonConfirmedLocationCount(arg1 context.Context, arg2 database.QueryExecer, arg3 time.Time) (*dto.GetNonConfirmedLocationCountOut, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.GetNonConfirmedLocationCountOut), args.Error(1)
}

func (r *MockTimesheetLocationListRepoImpl) GetTimesheetLocationCount(arg1 context.Context, arg2 database.QueryExecer, arg3 string) (*dto.TimesheetLocationAggregate, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*dto.TimesheetLocationAggregate), args.Error(1)
}

func (r *MockTimesheetLocationListRepoImpl) GetTimesheetLocationList(arg1 context.Context, arg2 database.QueryExecer, arg3 *dto.GetTimesheetLocationListReq) ([]*dto.TimesheetLocation, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*dto.TimesheetLocation), args.Error(1)
}
