// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: yasuo/v1/imports.proto

package ypb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ImportSchoolsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportSchoolsRequest) Reset() {
	*x = ImportSchoolsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportSchoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSchoolsRequest) ProtoMessage() {}

func (x *ImportSchoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSchoolsRequest.ProtoReflect.Descriptor instead.
func (*ImportSchoolsRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{0}
}

func (x *ImportSchoolsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportSchoolsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportSchoolsResponse) Reset() {
	*x = ImportSchoolsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportSchoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSchoolsResponse) ProtoMessage() {}

func (x *ImportSchoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSchoolsResponse.ProtoReflect.Descriptor instead.
func (*ImportSchoolsResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{1}
}

type ImportPresetStudyPlansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportPresetStudyPlansRequest) Reset() {
	*x = ImportPresetStudyPlansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportPresetStudyPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPresetStudyPlansRequest) ProtoMessage() {}

func (x *ImportPresetStudyPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPresetStudyPlansRequest.ProtoReflect.Descriptor instead.
func (*ImportPresetStudyPlansRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{2}
}

func (x *ImportPresetStudyPlansRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportPresetStudyPlansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportPresetStudyPlansResponse) Reset() {
	*x = ImportPresetStudyPlansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportPresetStudyPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPresetStudyPlansResponse) ProtoMessage() {}

func (x *ImportPresetStudyPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPresetStudyPlansResponse.ProtoReflect.Descriptor instead.
func (*ImportPresetStudyPlansResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{3}
}

type ImportCoursesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportCoursesRequest) Reset() {
	*x = ImportCoursesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCoursesRequest) ProtoMessage() {}

func (x *ImportCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCoursesRequest.ProtoReflect.Descriptor instead.
func (*ImportCoursesRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{4}
}

func (x *ImportCoursesRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportCoursesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
}

func (x *ImportCoursesResponse) Reset() {
	*x = ImportCoursesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCoursesResponse) ProtoMessage() {}

func (x *ImportCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCoursesResponse.ProtoReflect.Descriptor instead.
func (*ImportCoursesResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{5}
}

func (x *ImportCoursesResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type ImportBooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportBooksRequest) Reset() {
	*x = ImportBooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBooksRequest) ProtoMessage() {}

func (x *ImportBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBooksRequest.ProtoReflect.Descriptor instead.
func (*ImportBooksRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{6}
}

func (x *ImportBooksRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportBooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
}

func (x *ImportBooksResponse) Reset() {
	*x = ImportBooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBooksResponse) ProtoMessage() {}

func (x *ImportBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBooksResponse.ProtoReflect.Descriptor instead.
func (*ImportBooksResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{7}
}

func (x *ImportBooksResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type ImportChaptersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportChaptersRequest) Reset() {
	*x = ImportChaptersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportChaptersRequest) ProtoMessage() {}

func (x *ImportChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportChaptersRequest.ProtoReflect.Descriptor instead.
func (*ImportChaptersRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{8}
}

func (x *ImportChaptersRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImportChaptersRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportChaptersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
}

func (x *ImportChaptersResponse) Reset() {
	*x = ImportChaptersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportChaptersResponse) ProtoMessage() {}

func (x *ImportChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportChaptersResponse.ProtoReflect.Descriptor instead.
func (*ImportChaptersResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{9}
}

func (x *ImportChaptersResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type ImportTopicsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportTopicsRequest) Reset() {
	*x = ImportTopicsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTopicsRequest) ProtoMessage() {}

func (x *ImportTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTopicsRequest.ProtoReflect.Descriptor instead.
func (*ImportTopicsRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{10}
}

func (x *ImportTopicsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportTopicsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportTopicsResponse) Reset() {
	*x = ImportTopicsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTopicsResponse) ProtoMessage() {}

func (x *ImportTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTopicsResponse.ProtoReflect.Descriptor instead.
func (*ImportTopicsResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{11}
}

type ImportLearningObjectivesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportLearningObjectivesRequest) Reset() {
	*x = ImportLearningObjectivesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportLearningObjectivesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLearningObjectivesRequest) ProtoMessage() {}

func (x *ImportLearningObjectivesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLearningObjectivesRequest.ProtoReflect.Descriptor instead.
func (*ImportLearningObjectivesRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{12}
}

func (x *ImportLearningObjectivesRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImportLearningObjectivesRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportLearningObjectivesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportLearningObjectivesResponse) Reset() {
	*x = ImportLearningObjectivesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportLearningObjectivesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLearningObjectivesResponse) ProtoMessage() {}

func (x *ImportLearningObjectivesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLearningObjectivesResponse.ProtoReflect.Descriptor instead.
func (*ImportLearningObjectivesResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{13}
}

type ImportQuizzesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportQuizzesRequest) Reset() {
	*x = ImportQuizzesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportQuizzesRequest) ProtoMessage() {}

func (x *ImportQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportQuizzesRequest.ProtoReflect.Descriptor instead.
func (*ImportQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{14}
}

func (x *ImportQuizzesRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImportQuizzesRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportQuizzesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
}

func (x *ImportQuizzesResponse) Reset() {
	*x = ImportQuizzesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yasuo_v1_imports_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportQuizzesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportQuizzesResponse) ProtoMessage() {}

func (x *ImportQuizzesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yasuo_v1_imports_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportQuizzesResponse.ProtoReflect.Descriptor instead.
func (*ImportQuizzesResponse) Descriptor() ([]byte, []int) {
	return file_yasuo_v1_imports_proto_rawDescGZIP(), []int{15}
}

func (x *ImportQuizzesResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

var File_yasuo_v1_imports_proto protoreflect.FileDescriptor

var file_yasuo_v1_imports_proto_rawDesc = []byte{
	0x0a, 0x16, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e,
	0x76, 0x31, 0x22, 0x30, 0x0a, 0x14, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x68, 0x6f,
	0x6f, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a,
	0x1d, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x75,
	0x64, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x20, 0x0a, 0x1e, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x50, 0x6c, 0x61,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x37, 0x0a, 0x15,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x66, 0x75, 0x6c, 0x22, 0x2e, 0x0a, 0x12, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x35, 0x0a, 0x13, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x22, 0x4e, 0x0a, 0x15,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x38, 0x0a, 0x16,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x22, 0x2f, 0x0a, 0x13, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x58, 0x0a, 0x1f, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4d, 0x0a,
	0x14, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x37, 0x0a, 0x15,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x66, 0x75, 0x6c, 0x32, 0xe5, 0x05, 0x0a, 0x0d, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x1e, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x6d, 0x0a, 0x16, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79,
	0x50, 0x6c, 0x61, 0x6e, 0x73, 0x12, 0x27, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x75,
	0x64, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x52, 0x0a, 0x0d, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x79, 0x61,
	0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x79, 0x61,
	0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x55,
	0x0a, 0x0e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x1f, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x4c, 0x0a, 0x0b, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x1c, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x28, 0x01, 0x12, 0x4f, 0x0a, 0x0c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x73, 0x12, 0x1d, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x12, 0x73, 0x0a, 0x18, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x12, 0x29, 0x2e, 0x79, 0x61, 0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x79, 0x61,
	0x73, 0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x52, 0x0a, 0x0d, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x79, 0x61, 0x73,
	0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x51, 0x75, 0x69, 0x7a,
	0x7a, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x79, 0x61, 0x73,
	0x75, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x51, 0x75, 0x69, 0x7a,
	0x7a, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x61,
	0x62, 0x69, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x75, 0x66, 0x2f, 0x79, 0x61, 0x73, 0x75,
	0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yasuo_v1_imports_proto_rawDescOnce sync.Once
	file_yasuo_v1_imports_proto_rawDescData = file_yasuo_v1_imports_proto_rawDesc
)

func file_yasuo_v1_imports_proto_rawDescGZIP() []byte {
	file_yasuo_v1_imports_proto_rawDescOnce.Do(func() {
		file_yasuo_v1_imports_proto_rawDescData = protoimpl.X.CompressGZIP(file_yasuo_v1_imports_proto_rawDescData)
	})
	return file_yasuo_v1_imports_proto_rawDescData
}

var file_yasuo_v1_imports_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_yasuo_v1_imports_proto_goTypes = []interface{}{
	(*ImportSchoolsRequest)(nil),             // 0: yasuo.v1.ImportSchoolsRequest
	(*ImportSchoolsResponse)(nil),            // 1: yasuo.v1.ImportSchoolsResponse
	(*ImportPresetStudyPlansRequest)(nil),    // 2: yasuo.v1.ImportPresetStudyPlansRequest
	(*ImportPresetStudyPlansResponse)(nil),   // 3: yasuo.v1.ImportPresetStudyPlansResponse
	(*ImportCoursesRequest)(nil),             // 4: yasuo.v1.ImportCoursesRequest
	(*ImportCoursesResponse)(nil),            // 5: yasuo.v1.ImportCoursesResponse
	(*ImportBooksRequest)(nil),               // 6: yasuo.v1.ImportBooksRequest
	(*ImportBooksResponse)(nil),              // 7: yasuo.v1.ImportBooksResponse
	(*ImportChaptersRequest)(nil),            // 8: yasuo.v1.ImportChaptersRequest
	(*ImportChaptersResponse)(nil),           // 9: yasuo.v1.ImportChaptersResponse
	(*ImportTopicsRequest)(nil),              // 10: yasuo.v1.ImportTopicsRequest
	(*ImportTopicsResponse)(nil),             // 11: yasuo.v1.ImportTopicsResponse
	(*ImportLearningObjectivesRequest)(nil),  // 12: yasuo.v1.ImportLearningObjectivesRequest
	(*ImportLearningObjectivesResponse)(nil), // 13: yasuo.v1.ImportLearningObjectivesResponse
	(*ImportQuizzesRequest)(nil),             // 14: yasuo.v1.ImportQuizzesRequest
	(*ImportQuizzesResponse)(nil),            // 15: yasuo.v1.ImportQuizzesResponse
}
var file_yasuo_v1_imports_proto_depIdxs = []int32{
	0,  // 0: yasuo.v1.ImportService.ImportSchools:input_type -> yasuo.v1.ImportSchoolsRequest
	2,  // 1: yasuo.v1.ImportService.ImportPresetStudyPlans:input_type -> yasuo.v1.ImportPresetStudyPlansRequest
	4,  // 2: yasuo.v1.ImportService.ImportCourses:input_type -> yasuo.v1.ImportCoursesRequest
	8,  // 3: yasuo.v1.ImportService.ImportChapters:input_type -> yasuo.v1.ImportChaptersRequest
	6,  // 4: yasuo.v1.ImportService.ImportBooks:input_type -> yasuo.v1.ImportBooksRequest
	10, // 5: yasuo.v1.ImportService.ImportTopics:input_type -> yasuo.v1.ImportTopicsRequest
	12, // 6: yasuo.v1.ImportService.ImportLearningObjectives:input_type -> yasuo.v1.ImportLearningObjectivesRequest
	14, // 7: yasuo.v1.ImportService.ImportQuizzes:input_type -> yasuo.v1.ImportQuizzesRequest
	1,  // 8: yasuo.v1.ImportService.ImportSchools:output_type -> yasuo.v1.ImportSchoolsResponse
	3,  // 9: yasuo.v1.ImportService.ImportPresetStudyPlans:output_type -> yasuo.v1.ImportPresetStudyPlansResponse
	5,  // 10: yasuo.v1.ImportService.ImportCourses:output_type -> yasuo.v1.ImportCoursesResponse
	9,  // 11: yasuo.v1.ImportService.ImportChapters:output_type -> yasuo.v1.ImportChaptersResponse
	7,  // 12: yasuo.v1.ImportService.ImportBooks:output_type -> yasuo.v1.ImportBooksResponse
	11, // 13: yasuo.v1.ImportService.ImportTopics:output_type -> yasuo.v1.ImportTopicsResponse
	13, // 14: yasuo.v1.ImportService.ImportLearningObjectives:output_type -> yasuo.v1.ImportLearningObjectivesResponse
	15, // 15: yasuo.v1.ImportService.ImportQuizzes:output_type -> yasuo.v1.ImportQuizzesResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_yasuo_v1_imports_proto_init() }
func file_yasuo_v1_imports_proto_init() {
	if File_yasuo_v1_imports_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yasuo_v1_imports_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportSchoolsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportSchoolsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportPresetStudyPlansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportPresetStudyPlansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCoursesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCoursesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportBooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportBooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportChaptersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportChaptersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportTopicsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportTopicsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportLearningObjectivesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportLearningObjectivesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportQuizzesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yasuo_v1_imports_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportQuizzesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yasuo_v1_imports_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yasuo_v1_imports_proto_goTypes,
		DependencyIndexes: file_yasuo_v1_imports_proto_depIdxs,
		MessageInfos:      file_yasuo_v1_imports_proto_msgTypes,
	}.Build()
	File_yasuo_v1_imports_proto = out.File
	file_yasuo_v1_imports_proto_rawDesc = nil
	file_yasuo_v1_imports_proto_goTypes = nil
	file_yasuo_v1_imports_proto_depIdxs = nil
}
