CREATE TABLE IF NOT EXISTS public.discount (
    order_item_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    product_id TEXT,
    discount_id TEXT,
    start_date timestamp with time zone,
    student_product_id TEXT,
    product_name TEXT,
    effective_date timestamp with time zone,
    cancellation_date timestamp with time zone,
    end_date timestamp with time zone,
    order_item_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    order_item_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    order_item_deleted_at timestamp with time zone,
    discount_name TEXT NOT NULL,
    discount_type TEXT NOT NULL,
    discount_amount_type TEXT NOT NULL,
    discount_amount_value numeric(12,2) NOT NULL,
    recurring_valid_duration INTEGER,
    available_from timestamp with time zone NOT NULL,
    available_until timestamp with time zone NOT NULL,
    remarks TEXT,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    student_tag_id_validation TEXT,
    parent_tag_id_validation TEXT,
    discount_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    discount_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    discount_deleted_at timestamp with time zone,
    CONSTRAINT discount_order_item_pk PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public.material (
    material_id TEXT NOT NULL,
    material_type TEXT NOT NULL,
    custom_billing_date timestamp with time zone,
    material_created_at timestamp with time zone,
    material_updated_at timestamp with time zone,
    material_deleted_at timestamp with time zone,
    product_id TEXT NOT NULL,
    name TEXT NOT NULL,
    product_type TEXT NOT NULL,
    tax_id TEXT,
    available_from timestamp with time zone NOT NULL,
    available_until timestamp with time zone NOT NULL,
    remarks TEXT,
    custom_billing_period timestamp with time zone,
    billing_schedule_id TEXT,
    disable_pro_rating_flag BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    is_unique BOOLEAN DEFAULT FALSE,
    product_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    product_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    product_deleted_at timestamp with time zone,
    CONSTRAINT material_pk PRIMARY KEY (material_id)
);

CREATE TABLE IF NOT EXISTS public.billing_ratio (
    billing_ratio_id TEXT NOT NULL,
    billing_ratio_start_date timestamp with time zone NOT NULL,
    billing_ratio_end_date timestamp with time zone NOT NULL,
    billing_ratio_numerator INTEGER NOT NULL,
    billing_ratio_denominator INTEGER NOT NULL,
    billing_ratio_is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    billing_ratio_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    billing_ratio_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    billing_ratio_deleted_at timestamp with time zone,
    billing_schedule_period_id TEXT NOT NULL,
    billing_schedule_period_name TEXT NOT NULL,
    billing_schedule_period_start_date timestamp with time zone NOT NULL,
    billing_schedule_period_end_date timestamp with time zone NOT NULL,
    billing_date timestamp with time zone NOT NULL,
    billing_schedule_period_remarks TEXT,
    billing_schedule_period_is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    billing_schedule_period_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    billing_schedule_period_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    billing_schedule_period_deleted_at timestamp with time zone,
    billing_schedule_id TEXT NOT NULL,
    billing_schedule_name TEXT NOT NULL,
    billing_schedule_remarks TEXT,
    billing_schedule_is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    billing_schedule_created_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    billing_schedule_updated_at timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    billing_schedule_deleted_at timestamp with time zone,
    CONSTRAINT billing_ratio_pk PRIMARY KEY (billing_ratio_id)
);

ALTER PUBLICATION kec_publication ADD TABLE 
public.discount,
public.material,
public.billing_ratio;
