// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: lessonmgmt/v1/class.proto

package lpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetByStudentSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentSubscriptionId []string `protobuf:"bytes,1,rep,name=student_subscription_id,json=studentSubscriptionId,proto3" json:"student_subscription_id,omitempty"`
}

func (x *GetByStudentSubscriptionRequest) Reset() {
	*x = GetByStudentSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_class_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByStudentSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByStudentSubscriptionRequest) ProtoMessage() {}

func (x *GetByStudentSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_class_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByStudentSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetByStudentSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_class_proto_rawDescGZIP(), []int{0}
}

func (x *GetByStudentSubscriptionRequest) GetStudentSubscriptionId() []string {
	if x != nil {
		return x.StudentSubscriptionId
	}
	return nil
}

type GetByStudentSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassUnassigned []*GetByStudentSubscriptionResponse_ClassUnassigned `protobuf:"bytes,1,rep,name=class_unassigned,json=classUnassigned,proto3" json:"class_unassigned,omitempty"`
}

func (x *GetByStudentSubscriptionResponse) Reset() {
	*x = GetByStudentSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_class_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByStudentSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByStudentSubscriptionResponse) ProtoMessage() {}

func (x *GetByStudentSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_class_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByStudentSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetByStudentSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_class_proto_rawDescGZIP(), []int{1}
}

func (x *GetByStudentSubscriptionResponse) GetClassUnassigned() []*GetByStudentSubscriptionResponse_ClassUnassigned {
	if x != nil {
		return x.ClassUnassigned
	}
	return nil
}

type GetByStudentSubscriptionResponse_ClassUnassigned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentSubscriptionId string `protobuf:"bytes,1,opt,name=student_subscription_id,json=studentSubscriptionId,proto3" json:"student_subscription_id,omitempty"`
	IsClassUnassigned     bool   `protobuf:"varint,2,opt,name=is_class_unassigned,json=isClassUnassigned,proto3" json:"is_class_unassigned,omitempty"`
}

func (x *GetByStudentSubscriptionResponse_ClassUnassigned) Reset() {
	*x = GetByStudentSubscriptionResponse_ClassUnassigned{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_class_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByStudentSubscriptionResponse_ClassUnassigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByStudentSubscriptionResponse_ClassUnassigned) ProtoMessage() {}

func (x *GetByStudentSubscriptionResponse_ClassUnassigned) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_class_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByStudentSubscriptionResponse_ClassUnassigned.ProtoReflect.Descriptor instead.
func (*GetByStudentSubscriptionResponse_ClassUnassigned) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_class_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetByStudentSubscriptionResponse_ClassUnassigned) GetStudentSubscriptionId() string {
	if x != nil {
		return x.StudentSubscriptionId
	}
	return ""
}

func (x *GetByStudentSubscriptionResponse_ClassUnassigned) GetIsClassUnassigned() bool {
	if x != nil {
		return x.IsClassUnassigned
	}
	return false
}

var File_lessonmgmt_v1_class_proto protoreflect.FileDescriptor

var file_lessonmgmt_v1_class_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x59, 0x0a, 0x1f, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a,
	0x17, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x15,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x89, 0x02, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x10, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x5f, 0x75, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x55, 0x6e, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x0f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x55, 0x6e, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x1a, 0x79, 0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x55,
	0x6e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x73, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x2e, 0x0a, 0x13, 0x69, 0x73, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x75, 0x6e,
	0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11,
	0x69, 0x73, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x55, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x32, 0x91, 0x01, 0x0a, 0x12, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x69, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x61, 0x6e, 0x61,
	0x62, 0x75, 0x66, 0x2f, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x76,
	0x31, 0x3b, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lessonmgmt_v1_class_proto_rawDescOnce sync.Once
	file_lessonmgmt_v1_class_proto_rawDescData = file_lessonmgmt_v1_class_proto_rawDesc
)

func file_lessonmgmt_v1_class_proto_rawDescGZIP() []byte {
	file_lessonmgmt_v1_class_proto_rawDescOnce.Do(func() {
		file_lessonmgmt_v1_class_proto_rawDescData = protoimpl.X.CompressGZIP(file_lessonmgmt_v1_class_proto_rawDescData)
	})
	return file_lessonmgmt_v1_class_proto_rawDescData
}

var file_lessonmgmt_v1_class_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lessonmgmt_v1_class_proto_goTypes = []interface{}{
	(*GetByStudentSubscriptionRequest)(nil),                  // 0: lessonmgmt.v1.GetByStudentSubscriptionRequest
	(*GetByStudentSubscriptionResponse)(nil),                 // 1: lessonmgmt.v1.GetByStudentSubscriptionResponse
	(*GetByStudentSubscriptionResponse_ClassUnassigned)(nil), // 2: lessonmgmt.v1.GetByStudentSubscriptionResponse.ClassUnassigned
}
var file_lessonmgmt_v1_class_proto_depIdxs = []int32{
	2, // 0: lessonmgmt.v1.GetByStudentSubscriptionResponse.class_unassigned:type_name -> lessonmgmt.v1.GetByStudentSubscriptionResponse.ClassUnassigned
	0, // 1: lessonmgmt.v1.ClassReaderService.GetByStudentSubscription:input_type -> lessonmgmt.v1.GetByStudentSubscriptionRequest
	1, // 2: lessonmgmt.v1.ClassReaderService.GetByStudentSubscription:output_type -> lessonmgmt.v1.GetByStudentSubscriptionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lessonmgmt_v1_class_proto_init() }
func file_lessonmgmt_v1_class_proto_init() {
	if File_lessonmgmt_v1_class_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lessonmgmt_v1_class_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByStudentSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_class_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByStudentSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_class_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByStudentSubscriptionResponse_ClassUnassigned); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lessonmgmt_v1_class_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lessonmgmt_v1_class_proto_goTypes,
		DependencyIndexes: file_lessonmgmt_v1_class_proto_depIdxs,
		MessageInfos:      file_lessonmgmt_v1_class_proto_msgTypes,
	}.Build()
	File_lessonmgmt_v1_class_proto = out.File
	file_lessonmgmt_v1_class_proto_rawDesc = nil
	file_lessonmgmt_v1_class_proto_goTypes = nil
	file_lessonmgmt_v1_class_proto_depIdxs = nil
}
