// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: lessonmgmt/v1/lesson_executor.proto

package lpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ImportError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowNumber int32  `protobuf:"varint,1,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ImportError) Reset() {
	*x = ImportError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportError) ProtoMessage() {}

func (x *ImportError) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportError.ProtoReflect.Descriptor instead.
func (*ImportError) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ImportError) GetRowNumber() int32 {
	if x != nil {
		return x.RowNumber
	}
	return 0
}

func (x *ImportError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExportClassroomsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportClassroomsRequest) Reset() {
	*x = ExportClassroomsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportClassroomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportClassroomsRequest) ProtoMessage() {}

func (x *ExportClassroomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportClassroomsRequest.ProtoReflect.Descriptor instead.
func (*ExportClassroomsRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{1}
}

type ExportClassroomsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExportClassroomsResponse) Reset() {
	*x = ExportClassroomsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportClassroomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportClassroomsResponse) ProtoMessage() {}

func (x *ExportClassroomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportClassroomsResponse.ProtoReflect.Descriptor instead.
func (*ExportClassroomsResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ExportClassroomsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenerateLessonCSVTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateLessonCSVTemplateRequest) Reset() {
	*x = GenerateLessonCSVTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateLessonCSVTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLessonCSVTemplateRequest) ProtoMessage() {}

func (x *GenerateLessonCSVTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLessonCSVTemplateRequest.ProtoReflect.Descriptor instead.
func (*GenerateLessonCSVTemplateRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{3}
}

type GenerateLessonCSVTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GenerateLessonCSVTemplateResponse) Reset() {
	*x = GenerateLessonCSVTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateLessonCSVTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLessonCSVTemplateResponse) ProtoMessage() {}

func (x *GenerateLessonCSVTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLessonCSVTemplateResponse.ProtoReflect.Descriptor instead.
func (*GenerateLessonCSVTemplateResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateLessonCSVTemplateResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImportLessonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeZone string `protobuf:"bytes,2,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
}

func (x *ImportLessonRequest) Reset() {
	*x = ImportLessonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLessonRequest) ProtoMessage() {}

func (x *ImportLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLessonRequest.ProtoReflect.Descriptor instead.
func (*ImportLessonRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{5}
}

func (x *ImportLessonRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ImportLessonRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type ImportLessonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*ImportLessonResponse_ImportLessonError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ImportLessonResponse) Reset() {
	*x = ImportLessonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLessonResponse) ProtoMessage() {}

func (x *ImportLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLessonResponse.ProtoReflect.Descriptor instead.
func (*ImportLessonResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{6}
}

func (x *ImportLessonResponse) GetErrors() []*ImportLessonResponse_ImportLessonError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ExportTeacherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportTeacherRequest) Reset() {
	*x = ExportTeacherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTeacherRequest) ProtoMessage() {}

func (x *ExportTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTeacherRequest.ProtoReflect.Descriptor instead.
func (*ExportTeacherRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{7}
}

type ExportTeacherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExportTeacherResponse) Reset() {
	*x = ExportTeacherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTeacherResponse) ProtoMessage() {}

func (x *ExportTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTeacherResponse.ProtoReflect.Descriptor instead.
func (*ExportTeacherResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{8}
}

func (x *ExportTeacherResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExportEnrolledStudentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timezone string `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *ExportEnrolledStudentRequest) Reset() {
	*x = ExportEnrolledStudentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportEnrolledStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEnrolledStudentRequest) ProtoMessage() {}

func (x *ExportEnrolledStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEnrolledStudentRequest.ProtoReflect.Descriptor instead.
func (*ExportEnrolledStudentRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{9}
}

func (x *ExportEnrolledStudentRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type ExportEnrolledStudentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExportEnrolledStudentResponse) Reset() {
	*x = ExportEnrolledStudentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportEnrolledStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEnrolledStudentResponse) ProtoMessage() {}

func (x *ExportEnrolledStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEnrolledStudentResponse.ProtoReflect.Descriptor instead.
func (*ExportEnrolledStudentResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{10}
}

func (x *ExportEnrolledStudentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImportClassroomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ImportClassroomRequest) Reset() {
	*x = ImportClassroomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportClassroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportClassroomRequest) ProtoMessage() {}

func (x *ImportClassroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportClassroomRequest.ProtoReflect.Descriptor instead.
func (*ImportClassroomRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{11}
}

func (x *ImportClassroomRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportClassroomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*ImportError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ImportClassroomResponse) Reset() {
	*x = ImportClassroomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportClassroomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportClassroomResponse) ProtoMessage() {}

func (x *ImportClassroomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportClassroomResponse.ProtoReflect.Descriptor instead.
func (*ImportClassroomResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{12}
}

func (x *ImportClassroomResponse) GetErrors() []*ImportError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ExportCourseTeachingTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportCourseTeachingTimeRequest) Reset() {
	*x = ExportCourseTeachingTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportCourseTeachingTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportCourseTeachingTimeRequest) ProtoMessage() {}

func (x *ExportCourseTeachingTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportCourseTeachingTimeRequest.ProtoReflect.Descriptor instead.
func (*ExportCourseTeachingTimeRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{13}
}

type ExportCourseTeachingTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExportCourseTeachingTimeResponse) Reset() {
	*x = ExportCourseTeachingTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportCourseTeachingTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportCourseTeachingTimeResponse) ProtoMessage() {}

func (x *ExportCourseTeachingTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportCourseTeachingTimeResponse.ProtoReflect.Descriptor instead.
func (*ExportCourseTeachingTimeResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{14}
}

func (x *ExportCourseTeachingTimeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImportCourseTeachingTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Timezone string `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *ImportCourseTeachingTimeRequest) Reset() {
	*x = ImportCourseTeachingTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCourseTeachingTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCourseTeachingTimeRequest) ProtoMessage() {}

func (x *ImportCourseTeachingTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCourseTeachingTimeRequest.ProtoReflect.Descriptor instead.
func (*ImportCourseTeachingTimeRequest) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{15}
}

func (x *ImportCourseTeachingTimeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ImportCourseTeachingTimeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type ImportCourseTeachingTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*ImportError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ImportCourseTeachingTimeResponse) Reset() {
	*x = ImportCourseTeachingTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCourseTeachingTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCourseTeachingTimeResponse) ProtoMessage() {}

func (x *ImportCourseTeachingTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCourseTeachingTimeResponse.ProtoReflect.Descriptor instead.
func (*ImportCourseTeachingTimeResponse) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{16}
}

func (x *ImportCourseTeachingTimeResponse) GetErrors() []*ImportError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ImportLessonResponse_ImportLessonError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowNumber int32  `protobuf:"varint,1,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ImportLessonResponse_ImportLessonError) Reset() {
	*x = ImportLessonResponse_ImportLessonError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportLessonResponse_ImportLessonError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLessonResponse_ImportLessonError) ProtoMessage() {}

func (x *ImportLessonResponse_ImportLessonError) ProtoReflect() protoreflect.Message {
	mi := &file_lessonmgmt_v1_lesson_executor_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLessonResponse_ImportLessonError.ProtoReflect.Descriptor instead.
func (*ImportLessonResponse_ImportLessonError) Descriptor() ([]byte, []int) {
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ImportLessonResponse_ImportLessonError) GetRowNumber() int32 {
	if x != nil {
		return x.RowNumber
	}
	return 0
}

func (x *ImportLessonResponse_ImportLessonError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_lessonmgmt_v1_lesson_executor_proto protoreflect.FileDescriptor

var file_lessonmgmt_v1_lesson_executor_proto_rawDesc = []byte{
	0x0a, 0x23, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74,
	0x2f, 0x76, 0x31, 0x2f, 0x7a, 0x6f, 0x6f, 0x6d, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0b, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x6f, 0x77, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x19, 0x0a, 0x17, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x18, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x20, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x53, 0x56, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x21, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x53, 0x56, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4c, 0x0a, 0x13, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x6f, 0x6e, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65,
	0x22, 0xaf, 0x01, 0x0a, 0x14, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a, 0x48, 0x0a, 0x11, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x72, 0x6f, 0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x1c, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a,
	0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a,
	0x6f, 0x6e, 0x65, 0x22, 0x33, 0x0a, 0x1d, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x16, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4d, 0x0a, 0x17,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x21, 0x0a, 0x1f, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36,
	0x0a, 0x20, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x65,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x57, 0x0a, 0x1f, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x22,
	0x56, 0x0a, 0x20, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x32, 0xe9, 0x07, 0x0a, 0x15, 0x4c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x7e, 0x0a, 0x19, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x43, 0x53, 0x56, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2f,
	0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x53, 0x56,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x30, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x53,
	0x56, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x60, 0x0a, 0x0f, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x25, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x11,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5a, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x27, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5a, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x5a, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x18, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x2e, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2f, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x63, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x26, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67,
	0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c,
	0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x72, 0x0a, 0x15, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x2e, 0x6c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x45,
	0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x18, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x2e, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x69, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x62, 0x75,
	0x66, 0x2f, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x76, 0x31, 0x3b,
	0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lessonmgmt_v1_lesson_executor_proto_rawDescOnce sync.Once
	file_lessonmgmt_v1_lesson_executor_proto_rawDescData = file_lessonmgmt_v1_lesson_executor_proto_rawDesc
)

func file_lessonmgmt_v1_lesson_executor_proto_rawDescGZIP() []byte {
	file_lessonmgmt_v1_lesson_executor_proto_rawDescOnce.Do(func() {
		file_lessonmgmt_v1_lesson_executor_proto_rawDescData = protoimpl.X.CompressGZIP(file_lessonmgmt_v1_lesson_executor_proto_rawDescData)
	})
	return file_lessonmgmt_v1_lesson_executor_proto_rawDescData
}

var file_lessonmgmt_v1_lesson_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_lessonmgmt_v1_lesson_executor_proto_goTypes = []interface{}{
	(*ImportError)(nil),                            // 0: lessonmgmt.v1.ImportError
	(*ExportClassroomsRequest)(nil),                // 1: lessonmgmt.v1.ExportClassroomsRequest
	(*ExportClassroomsResponse)(nil),               // 2: lessonmgmt.v1.ExportClassroomsResponse
	(*GenerateLessonCSVTemplateRequest)(nil),       // 3: lessonmgmt.v1.GenerateLessonCSVTemplateRequest
	(*GenerateLessonCSVTemplateResponse)(nil),      // 4: lessonmgmt.v1.GenerateLessonCSVTemplateResponse
	(*ImportLessonRequest)(nil),                    // 5: lessonmgmt.v1.ImportLessonRequest
	(*ImportLessonResponse)(nil),                   // 6: lessonmgmt.v1.ImportLessonResponse
	(*ExportTeacherRequest)(nil),                   // 7: lessonmgmt.v1.ExportTeacherRequest
	(*ExportTeacherResponse)(nil),                  // 8: lessonmgmt.v1.ExportTeacherResponse
	(*ExportEnrolledStudentRequest)(nil),           // 9: lessonmgmt.v1.ExportEnrolledStudentRequest
	(*ExportEnrolledStudentResponse)(nil),          // 10: lessonmgmt.v1.ExportEnrolledStudentResponse
	(*ImportClassroomRequest)(nil),                 // 11: lessonmgmt.v1.ImportClassroomRequest
	(*ImportClassroomResponse)(nil),                // 12: lessonmgmt.v1.ImportClassroomResponse
	(*ExportCourseTeachingTimeRequest)(nil),        // 13: lessonmgmt.v1.ExportCourseTeachingTimeRequest
	(*ExportCourseTeachingTimeResponse)(nil),       // 14: lessonmgmt.v1.ExportCourseTeachingTimeResponse
	(*ImportCourseTeachingTimeRequest)(nil),        // 15: lessonmgmt.v1.ImportCourseTeachingTimeRequest
	(*ImportCourseTeachingTimeResponse)(nil),       // 16: lessonmgmt.v1.ImportCourseTeachingTimeResponse
	(*ImportLessonResponse_ImportLessonError)(nil), // 17: lessonmgmt.v1.ImportLessonResponse.ImportLessonError
	(*ImportZoomAccountRequest)(nil),               // 18: lessonmgmt.v1.ImportZoomAccountRequest
	(*ImportZoomAccountResponse)(nil),              // 19: lessonmgmt.v1.ImportZoomAccountResponse
}
var file_lessonmgmt_v1_lesson_executor_proto_depIdxs = []int32{
	17, // 0: lessonmgmt.v1.ImportLessonResponse.errors:type_name -> lessonmgmt.v1.ImportLessonResponse.ImportLessonError
	0,  // 1: lessonmgmt.v1.ImportClassroomResponse.errors:type_name -> lessonmgmt.v1.ImportError
	0,  // 2: lessonmgmt.v1.ImportCourseTeachingTimeResponse.errors:type_name -> lessonmgmt.v1.ImportError
	3,  // 3: lessonmgmt.v1.LessonExecutorService.GenerateLessonCSVTemplate:input_type -> lessonmgmt.v1.GenerateLessonCSVTemplateRequest
	11, // 4: lessonmgmt.v1.LessonExecutorService.ImportClassroom:input_type -> lessonmgmt.v1.ImportClassroomRequest
	5,  // 5: lessonmgmt.v1.LessonExecutorService.ImportLesson:input_type -> lessonmgmt.v1.ImportLessonRequest
	18, // 6: lessonmgmt.v1.LessonExecutorService.ImportZoomAccount:input_type -> lessonmgmt.v1.ImportZoomAccountRequest
	15, // 7: lessonmgmt.v1.LessonExecutorService.ImportCourseTeachingTime:input_type -> lessonmgmt.v1.ImportCourseTeachingTimeRequest
	1,  // 8: lessonmgmt.v1.LessonExecutorService.ExportClassrooms:input_type -> lessonmgmt.v1.ExportClassroomsRequest
	7,  // 9: lessonmgmt.v1.LessonExecutorService.ExportTeacher:input_type -> lessonmgmt.v1.ExportTeacherRequest
	9,  // 10: lessonmgmt.v1.LessonExecutorService.ExportEnrolledStudent:input_type -> lessonmgmt.v1.ExportEnrolledStudentRequest
	13, // 11: lessonmgmt.v1.LessonExecutorService.ExportCourseTeachingTime:input_type -> lessonmgmt.v1.ExportCourseTeachingTimeRequest
	4,  // 12: lessonmgmt.v1.LessonExecutorService.GenerateLessonCSVTemplate:output_type -> lessonmgmt.v1.GenerateLessonCSVTemplateResponse
	12, // 13: lessonmgmt.v1.LessonExecutorService.ImportClassroom:output_type -> lessonmgmt.v1.ImportClassroomResponse
	6,  // 14: lessonmgmt.v1.LessonExecutorService.ImportLesson:output_type -> lessonmgmt.v1.ImportLessonResponse
	19, // 15: lessonmgmt.v1.LessonExecutorService.ImportZoomAccount:output_type -> lessonmgmt.v1.ImportZoomAccountResponse
	16, // 16: lessonmgmt.v1.LessonExecutorService.ImportCourseTeachingTime:output_type -> lessonmgmt.v1.ImportCourseTeachingTimeResponse
	2,  // 17: lessonmgmt.v1.LessonExecutorService.ExportClassrooms:output_type -> lessonmgmt.v1.ExportClassroomsResponse
	8,  // 18: lessonmgmt.v1.LessonExecutorService.ExportTeacher:output_type -> lessonmgmt.v1.ExportTeacherResponse
	10, // 19: lessonmgmt.v1.LessonExecutorService.ExportEnrolledStudent:output_type -> lessonmgmt.v1.ExportEnrolledStudentResponse
	14, // 20: lessonmgmt.v1.LessonExecutorService.ExportCourseTeachingTime:output_type -> lessonmgmt.v1.ExportCourseTeachingTimeResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_lessonmgmt_v1_lesson_executor_proto_init() }
func file_lessonmgmt_v1_lesson_executor_proto_init() {
	if File_lessonmgmt_v1_lesson_executor_proto != nil {
		return
	}
	file_lessonmgmt_v1_zoom_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportClassroomsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportClassroomsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateLessonCSVTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateLessonCSVTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportLessonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportLessonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportTeacherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportTeacherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportEnrolledStudentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportEnrolledStudentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportClassroomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportClassroomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportCourseTeachingTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportCourseTeachingTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCourseTeachingTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCourseTeachingTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lessonmgmt_v1_lesson_executor_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportLessonResponse_ImportLessonError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lessonmgmt_v1_lesson_executor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lessonmgmt_v1_lesson_executor_proto_goTypes,
		DependencyIndexes: file_lessonmgmt_v1_lesson_executor_proto_depIdxs,
		MessageInfos:      file_lessonmgmt_v1_lesson_executor_proto_msgTypes,
	}.Build()
	File_lessonmgmt_v1_lesson_executor_proto = out.File
	file_lessonmgmt_v1_lesson_executor_proto_rawDesc = nil
	file_lessonmgmt_v1_lesson_executor_proto_goTypes = nil
	file_lessonmgmt_v1_lesson_executor_proto_depIdxs = nil
}
