// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/manabie-com/backend/internal/golibs/database"
	entities "github.com/manabie-com/backend/internal/payment/entities"

	mock "github.com/stretchr/testify/mock"
)

// IStudentProductServiceForRetrieveRecurringProduct is an autogenerated mock type for the IStudentProductServiceForRetrieveRecurringProduct type
type IStudentProductServiceForRetrieveRecurringProduct struct {
	mock.Mock
}

// GetActiveRecurringProductsOfStudentInLocation provides a mock function with given fields: ctx, db, studentID, locationID
func (_m *IStudentProductServiceForRetrieveRecurringProduct) GetActiveRecurringProductsOfStudentInLocation(ctx context.Context, db database.QueryExecer, studentID string, locationID string) ([]entities.StudentProduct, error) {
	ret := _m.Called(ctx, db, studentID, locationID)

	var r0 []entities.StudentProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.QueryExecer, string, string) ([]entities.StudentProduct, error)); ok {
		return rf(ctx, db, studentID, locationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.QueryExecer, string, string) []entities.StudentProduct); ok {
		r0 = rf(ctx, db, studentID, locationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.StudentProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.QueryExecer, string, string) error); ok {
		r1 = rf(ctx, db, studentID, locationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecurringProductsOfStudentInLocationForLOA provides a mock function with given fields: ctx, db, studentID, locationID
func (_m *IStudentProductServiceForRetrieveRecurringProduct) GetRecurringProductsOfStudentInLocationForLOA(ctx context.Context, db database.QueryExecer, studentID string, locationID string) ([]entities.StudentProduct, error) {
	ret := _m.Called(ctx, db, studentID, locationID)

	var r0 []entities.StudentProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.QueryExecer, string, string) ([]entities.StudentProduct, error)); ok {
		return rf(ctx, db, studentID, locationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.QueryExecer, string, string) []entities.StudentProduct); ok {
		r0 = rf(ctx, db, studentID, locationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.StudentProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.QueryExecer, string, string) error); ok {
		r1 = rf(ctx, db, studentID, locationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentProductsByStudentProductIDs provides a mock function with given fields: ctx, db, studentProductIDs
func (_m *IStudentProductServiceForRetrieveRecurringProduct) GetStudentProductsByStudentProductIDs(ctx context.Context, db database.Ext, studentProductIDs []string) ([]entities.StudentProduct, error) {
	ret := _m.Called(ctx, db, studentProductIDs)

	var r0 []entities.StudentProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Ext, []string) ([]entities.StudentProduct, error)); ok {
		return rf(ctx, db, studentProductIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Ext, []string) []entities.StudentProduct); ok {
		r0 = rf(ctx, db, studentProductIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.StudentProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Ext, []string) error); ok {
		r1 = rf(ctx, db, studentProductIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIStudentProductServiceForRetrieveRecurringProduct interface {
	mock.TestingT
	Cleanup(func())
}

// NewIStudentProductServiceForRetrieveRecurringProduct creates a new instance of IStudentProductServiceForRetrieveRecurringProduct. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIStudentProductServiceForRetrieveRecurringProduct(t mockConstructorTestingTNewIStudentProductServiceForRetrieveRecurringProduct) *IStudentProductServiceForRetrieveRecurringProduct {
	mock := &IStudentProductServiceForRetrieveRecurringProduct{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
