// Code generated by mockgen. DO NOT EDIT.
package mock_domain

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
	"github.com/manabie-com/backend/internal/notification/entities"
)

type MockDataRetentionService struct {
	mock.Mock
}

func (r *MockDataRetentionService) AssignIndividualRetentionNamesForNotification(arg1 context.Context, arg2 database.QueryExecer, arg3 *entities.InfoNotification) (*entities.InfoNotification, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.InfoNotification), args.Error(1)
}

func (r *MockDataRetentionService) AssignRetentionNameForUserNotification(arg1 context.Context, arg2 database.QueryExecer, arg3 entities.UserInfoNotifications) (entities.UserInfoNotifications, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(entities.UserInfoNotifications), args.Error(1)
}
