// Code generated by mockgen. DO NOT EDIT.
package mock_services

import (
	"context"

	"github.com/manabie-com/backend/internal/lessonmgmt/modules/zoom/domain"

	"github.com/stretchr/testify/mock"
)

type MockZoomService struct {
	mock.Mock
}

func (m *MockZoomService) RetryGenerateZoomLink(arg1 context.Context, arg2 string, arg3 *domain.ZoomGenerateMeetingRequest) (*domain.GenerateZoomLinkResponse, error) {
	args := m.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.GenerateZoomLinkResponse), args.Error(1)
}

func (m *MockZoomService) GenerateMultiZoomLink(arg1 context.Context, arg2 string, arg3 []*domain.ZoomGenerateMeetingRequest) ([]*domain.GenerateZoomLinkResponse, error) {
	args := m.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*domain.GenerateZoomLinkResponse), args.Error(1)
}

func (m *MockZoomService) RetryGetListUsers(arg1 context.Context, arg2 *domain.ZoomGetListUserRequest) (*domain.UserZoomResponse, error) {
	args := m.Called(arg1, arg2)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.UserZoomResponse), args.Error(1)
}

func (m *MockZoomService) RetryDeleteZoomLink(arg1 context.Context, arg2 string) (bool, error) {
	args := m.Called(arg1, arg2)

	if args.Get(0) == nil {
		return false, args.Error(1)
	}
	return args.Get(0).(bool), args.Error(1)
}

