ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS event TEXT NOT NULL DEFAULT 'NOTIFICATION_EVENT_NONE'::text;

ALTER TABLE public.notifications ADD CHECK (event = ANY (ARRAY[
    'NOTIFICATION_EVENT_NONE',
    'NOTIFICATION_EVENT_X_LO_COMPLETED',
    'NOTIFICATION_EVENT_TEACHER_GIVE_ASSIGNMENT',
    'NOTIFICATION_EVENT_TEACHER_RETURN_ASSIGNMENT',
    'NOTIFICATION_EVENT_STUDENT_SUBMIT_ASSIGNMENT',
    'NOTIFICATION_EVENT_ASSIGNMENT_UPDATED'
]));
