ALTER TABLE ONLY public.notifications DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE public.notifications ADD CHECK (type = ANY (ARRAY[
  'NOTIFICATION_TYPE_NONE',
  'NOTIFICATION_TYPE_TEXT',
  'NOTIFICATION_TYPE_PROMO_CODE',
  'NOTIFICATION_TYPE_ASSIGNMENT'
]));
