ALTER TABLE IF EXISTS public.chapters
ALTER COLUMN grade DROP NOT NULL;

ALTER TABLE IF EXISTS public.courses
ALTER COLUMN  grade DROP NOT NULL;

ALTER TABLE IF EXISTS public.learning_objectives
ALTER COLUMN grade DROP NOT NULL, ALTER COLUMN  subject DROP NOT NULL;
