ALTER TABLE lessons ADD COLUMN IF NOT EXISTS center_id TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS teaching_method TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS teaching_medium TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS scheduling_status  TEXT DEFAULT 'LESSON_SCHEDULING_STATUS_PUBLISHED';