ALTER TABLE ONLY public.info_notifications DROP CONSTRAINT IF EXISTS notification_type_check;
ALTER TABLE public.info_notifications
    ADD CONSTRAINT notification_type_check CHECK (type = ANY (ARRAY[
		'NOTIFICATION_TYPE_NONE',
		'NOTIFICATION_TYPE_TEXT',
		'NOTIFICATION_TYPE_PROMO_CODE',
		'NOTIFICATION_TYPE_ASSIGNMENT',
		'NOTIFICATION_TYPE_COMPOSED',
		'NOTIFICATION_TYPE_NATS_ASYNC'
]::text[]));
