ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS working_status TEXT NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS end_date DATE;

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS remarks TEXT;
