DROP RULE IF EXISTS LESSON_MEMBER_LOCK on lesson_members;

DROP RULE IF EXISTS LESSON_TEACHER_LOCK on lessons_teachers;

DROP RULE IF EXISTS LESSON_REPORT_LOCK on lesson_reports;

DROP RULE IF EXISTS LESSON_LOCK on lessons;
