ALTER TYPE product_type RENAME VALUE 'ONE_TIME' TO 'PACKAGE_TYPE_ONE_TIME';
ALTER TYPE product_type RENAME VALUE 'SCHEDULED' TO 'PACKAGE_TYPE_SCHEDULED';
ALTER TYPE product_type RENAME VALUE 'SLOT_BASED' TO 'PACKAGE_TYPE_SLOT_BASED';
ALTER TYPE product_type RENAME VALUE 'FREQUENCY' TO 'PACKAGE_TYPE_FREQUENCY';
