// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package epb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// InternalReaderServiceClient is the client API for InternalReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalReaderServiceClient interface {
	RetrieveBookIDByStudyPlanID(ctx context.Context, in *RetrieveBookIDByStudyPlanIDRequest, opts ...grpc.CallOption) (*RetrieveBookIDByStudyPlanIDResponse, error)
}

type internalReaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalReaderServiceClient(cc grpc.ClientConnInterface) InternalReaderServiceClient {
	return &internalReaderServiceClient{cc}
}

func (c *internalReaderServiceClient) RetrieveBookIDByStudyPlanID(ctx context.Context, in *RetrieveBookIDByStudyPlanIDRequest, opts ...grpc.CallOption) (*RetrieveBookIDByStudyPlanIDResponse, error) {
	out := new(RetrieveBookIDByStudyPlanIDResponse)
	err := c.cc.Invoke(ctx, "/eureka.v1.InternalReaderService/RetrieveBookIDByStudyPlanID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalReaderServiceServer is the server API for InternalReaderService service.
// All implementations should embed UnimplementedInternalReaderServiceServer
// for forward compatibility
type InternalReaderServiceServer interface {
	RetrieveBookIDByStudyPlanID(context.Context, *RetrieveBookIDByStudyPlanIDRequest) (*RetrieveBookIDByStudyPlanIDResponse, error)
}

// UnimplementedInternalReaderServiceServer should be embedded to have forward compatible implementations.
type UnimplementedInternalReaderServiceServer struct {
}

func (UnimplementedInternalReaderServiceServer) RetrieveBookIDByStudyPlanID(context.Context, *RetrieveBookIDByStudyPlanIDRequest) (*RetrieveBookIDByStudyPlanIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBookIDByStudyPlanID not implemented")
}

// UnsafeInternalReaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalReaderServiceServer will
// result in compilation errors.
type UnsafeInternalReaderServiceServer interface {
	mustEmbedUnimplementedInternalReaderServiceServer()
}

func RegisterInternalReaderServiceServer(s grpc.ServiceRegistrar, srv InternalReaderServiceServer) {
	s.RegisterService(&_InternalReaderService_serviceDesc, srv)
}

func _InternalReaderService_RetrieveBookIDByStudyPlanID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBookIDByStudyPlanIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalReaderServiceServer).RetrieveBookIDByStudyPlanID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eureka.v1.InternalReaderService/RetrieveBookIDByStudyPlanID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalReaderServiceServer).RetrieveBookIDByStudyPlanID(ctx, req.(*RetrieveBookIDByStudyPlanIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalReaderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eureka.v1.InternalReaderService",
	HandlerType: (*InternalReaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveBookIDByStudyPlanID",
			Handler:    _InternalReaderService_RetrieveBookIDByStudyPlanID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eureka/v1/internal_reader.proto",
}
