// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/manabie-com/backend/internal/golibs/database"
	entities "github.com/manabie-com/backend/internal/payment/entities"

	mock "github.com/stretchr/testify/mock"

	pmpb "github.com/manabie-com/backend/pkg/manabuf/payment/v1"
)

// IBillItemServiceForCustomOrder is an autogenerated mock type for the IBillItemServiceForCustomOrder type
type IBillItemServiceForCustomOrder struct {
	mock.Mock
}

// CreateCustomBillItem provides a mock function with given fields: ctx, db, customBillingItem, order, locationName
func (_m *IBillItemServiceForCustomOrder) CreateCustomBillItem(ctx context.Context, db database.QueryExecer, customBillingItem *pmpb.CustomBillingItem, order entities.Order, locationName string) error {
	ret := _m.Called(ctx, db, customBillingItem, order, locationName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.QueryExecer, *pmpb.CustomBillingItem, entities.Order, string) error); ok {
		r0 = rf(ctx, db, customBillingItem, order, locationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIBillItemServiceForCustomOrder interface {
	mock.TestingT
	Cleanup(func())
}

// NewIBillItemServiceForCustomOrder creates a new instance of IBillItemServiceForCustomOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIBillItemServiceForCustomOrder(t mockConstructorTestingTNewIBillItemServiceForCustomOrder) *IBillItemServiceForCustomOrder {
	mock := &IBillItemServiceForCustomOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
