// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
	"github.com/manabie-com/backend/internal/zeus/entities"
)

type MockActivityLogRepo struct {
	mock.Mock
}

func (r *MockActivityLogRepo) Create(arg1 context.Context, arg2 database.QueryExecer, arg3 *entities.ActivityLog) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}

func (r *MockActivityLogRepo) CreateBulk(arg1 context.Context, arg2 database.QueryExecer, arg3 []*entities.ActivityLog) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}
