{
 "title": "Dashboard is generated for bob-hasura service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rpc/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"bob-hasura\", destination_service_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"bob-hasura\", destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Status code Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"bob-hasura\", destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (response_code) / ignoring(response_code) group_left sum(rate(istio_requests_total{destination_service_name=~\"bob-hasura\", destination_service_namespace=\"$namespace\"}[$__rate_interval])) * 100 > 0",
     "legendFormat": "{{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"^(bob-hasura-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(bob-hasura-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"core\"}) / count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(bob-hasura-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"core\"}) / count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",container!=\"POD\",pod=~\"^(bob-hasura-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container!=\"POD\",pod=~\"^(bob-hasura-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"byte\"}) / count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container!=\"POD\",pod=~\"^(bob-hasura-[^hasuramigrateproxyjprep]).*\",namespace=\"$namespace\",unit=\"core\"}) / count(kube_pod_info{namespace=\"$namespace\",pod=~\"^(bob-[^hasuramigrateproxyjprep]).*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Receive Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_bytes_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_bytes_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_response_bytes_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "current"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_response_bytes_bucket{destination_service_name=~\"bob-hasura\",destination_service_namespace=\"$namespace\"}[$__rate_interval] offset $__range)) by (le))",
     "legendFormat": "last"
    }
   ]
  }
 ]
}