{
 "title": "Hasura Proxy",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "Staging : staging-2, JP-Partners : jp-partners, Tokyo : tokyo, Local : kind-kind"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_io_server_completed_rpcs{gke_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\",deployment=~\".*-hasura.*\"}, deployment)"
    }
   },
   { "name": "hasura_query_regexp", "label": "Hasura Query Regexp", "query": ".*" },
   { "name": "interval", "label": "Statistic interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Average Query Cache Hit Ratio",
   "type": "timeseries",
   "description": "Average query cache hit ratio computed over user-specified Statistic Interval.",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_cache{namespace=\"$namespace\",hasura_proxy_service=\"$service\",hasura_query!=\"\",cache_status=\"hit\",hasura_query=~\"$hasura_query_regexp\"}[$interval]))by(hasura_query)/sum(rate(hasura_cache{namespace=\"$namespace\",hasura_proxy_service=\"$service\",hasura_query!=\"\",hasura_query=~\"$hasura_query_regexp\"}[$interval]))by(hasura_query)",
     "legendFormat": "{{hasura_query}}"
    }
   ]
  },
  {
   "title": "Cache Hit Count",
   "type": "timeseries",
   "description": "Number of cache hit successfully and correctly",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "manabie_io_hasura_cache_hit{namespace=\"$namespace\",hasura_proxy_service=\"$service\",hasura_query=~\"$hasura_query_regexp\"}",
     "legendFormat": "{{hasura_query}}"
    }
   ]
  },
  {
   "title": "Cache Miss Count",
   "type": "timeseries",
   "description": "Number of requests that did not have cache",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "manabie_io_hasura_cache_miss{namespace=\"$namespace\",hasura_proxy_service=\"$service\",hasura_query=~\"$hasura_query_regexp\"}",
     "legendFormat": "{{hasura_query}}"
    }
   ]
  },
  {
   "title": "Query Cache Hit Ratio",
   "type": "timeseries",
   "description": "Query cache hit ratio at a given point of time (averaged over 2 min interval)",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_cache{namespace=\"$namespace\",hasura_proxy_service=\"$service\",hasura_query!=\"\",cache_status=\"hit\",hasura_query=~\"$hasura_query_regexp\"}[2m]))by(hasura_query)/sum(rate(hasura_cache{namespace=\"$namespace\",hasura_proxy_service=\"$service\",hasura_query!=\"\",hasura_query=~\"$hasura_query_regexp\"}[2m]))by(hasura_query)",
     "legendFormat": "{{hasura_query}} "
    }
   ]
  },
  {
   "title": "Cache Incorrectly Hit Count",
   "type": "timeseries",
   "description": "Number of hit cache but actually return the wrong data",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "manabie_io_hasura_cache_stale{namespace=\"$namespace\",hasura_proxy_service=\"$service\",hasura_query=~\"$hasura_query_regexp\"}",
     "legendFormat": "{{hasura_query}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": " sum(rate(opencensus_io_http_client_completed_count{namespace=\"$namespace\",hasura_proxy_service=~\"$service\",hasura_query=~\"$hasura_query_regexp\"}[2m])) by (hasura_query)",
     "legendFormat": "{{ hasura_query }} {{ hasura_proxy_service }}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_client_roundtrip_latency_bucket{namespace=\"$namespace\",hasura_proxy_service=~\"$service\",hasura_query=~\"$hasura_query_regexp\"}[3m])) by (le,hasura_query)) ",
     "legendFormat": "{{ hasura_query }}"
    },
    {}
   ]
  }
 ]
}