CREATE TABLE IF NOT EXISTS bob.lessons (
	lesson_id text NOT NULL,
	teacher_id text NULL,
	course_id text NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	deleted_at timestamptz NULL,
	end_at timestamptz NULL,
	control_settings jsonb NULL,
	lesson_group_id text NULL,
	room_id text NULL,
	lesson_type text NULL,
	status text NULL,
	stream_learner_counter int4 NOT NULL,
	learner_ids _text NOT NULL,
	name text NULL,
	start_time timestamptz NULL,
	end_time timestamptz NULL,
	resource_path text NOT NULL,
	room_state jsonb NULL,
	teaching_model text NULL,
	class_id text NULL,
	center_id text NULL,
	teaching_method text NULL,
	teaching_medium text NULL,
	scheduling_status text NULL,
	is_locked bool NOT NULL,
	scheduler_id text NULL,
	zoom_link TEXT,
	zoom_owner_id TEXT,
	zoom_id TEXT,
	zoom_occurrence_id TEXT,
	CONSTRAINT lessons_pk PRIMARY KEY (lesson_id)
);

CREATE TABLE IF NOT EXISTS bob.lesson_members (
	lesson_id text NOT NULL,
	user_id text NOT NULL,
	updated_at timestamptz NOT NULL,
	created_at timestamptz NOT NULL,
	deleted_at timestamptz NULL,
	resource_path text NOT NULL,
	attendance_status text NULL,
	attendance_remark text NULL,
	course_id text NULL,
	attendance_notice text NULL,
	attendance_reason text NULL,
	attendance_note text NULL,
	user_first_name text NULL,
	user_last_name text NULL,
	CONSTRAINT pk__lesson_members PRIMARY KEY (lesson_id, user_id)
);

ALTER PUBLICATION publication_for_datawarehouse ADD TABLE bob.lessons,bob.lesson_members;
