SET 'auto.offset.reset' = 'earliest';

CREATE STREAM IF NOT EXISTS INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.invoicemgmt.invoice_schedule_student', value_format='AVRO');

CREATE STREAM IF NOT EXISTS INVOICE_SCHEDULE_STUDENT_STREAM_FORMATTED_V1
    AS SELECT
        INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->INVOICE_SCHEDULE_STUDENT_ID AS KEY,
        AS_VALUE(INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->INVOICE_SCHEDULE_STUDENT_ID) AS INVOICE_SCHEDULE_STUDENT_ID,
        INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->INVOICE_SCHEDULE_HISTORY_ID AS INVOICE_SCHEDULE_HISTORY_ID,
        INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->STUDENT_ID AS STUDENT_ID,
        INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->ERROR_DETAILS AS ERROR_DETAILS,
        INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->ACTUAL_ERROR_DETAILS AS ACTUAL_ERROR_DETAILS,
        INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS INVOICE_SCHEDULE_STUDENT_CREATED_AT,
        CAST(NULL AS VARCHAR) AS INVOICE_SCHEDULE_STUDENT_UPDATED_AT,
        CAST(NULL AS VARCHAR) AS INVOICE_SCHEDULE_STUDENT_DELETED_AT
    FROM INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1
    WHERE INVOICE_SCHEDULE_STUDENT_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY AFTER->INVOICE_SCHEDULE_STUDENT_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}INVOICE_SCHEDULE_STUDENT_STREAM_FORMATTED_V1', value_format='AVRO');


CREATE TABLE IF NOT EXISTS INVOICE_SCHEDULE_STUDENT_PUBLIC_INFO_V1
AS SELECT
    INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.KEY AS INVOICE_SCHEDULE_STUDENT_ID,
    AS_VALUE(INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.KEY) AS INVOICE_SCHEDULE_HISTORY_ID,
    INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.STUDENT_ID AS STUDENT_ID,
    INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.ERROR_DETAILS AS ERROR_DETAILS,
    INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.ACTUAL_ERROR_DETAILS AS ACTUAL_ERROR_DETAILS,
    INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.INVOICE_SCHEDULE_STUDENT_CREATED_AT AS INVOICE_SCHEDULE_STUDENT_CREATED_AT,
    INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.INVOICE_SCHEDULE_STUDENT_UPDATED_AT AS INVOICE_SCHEDULE_STUDENT_UPDATED_AT,
    INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.INVOICE_SCHEDULE_STUDENT_DELETED_AT AS INVOICE_SCHEDULE_STUDENT_DELETED_AT,
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.TOTAL_STUDENTS AS INVOICE_SCHEDULE_ID, 
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.TOTAL_STUDENTS AS NUMBER_OF_FAILED_INVOICES,
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.TOTAL_STUDENTS AS TOTAL_STUDENTS,
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.EXECUTION_START_DATE AS EXECUTION_START_DATE,
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.EXECUTION_END_DATE AS EXECUTION_END_DATE,
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.INVOICE_SCHEDULE_HISTORY_CREATED_AT AS INVOICE_SCHEDULE_HISTORY_CREATED_AT,
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.INVOICE_SCHEDULE_HISTORY_UPDATED_AT AS INVOICE_SCHEDULE_HISTORY_UPDATED_AT,
    INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.INVOICE_SCHEDULE_HISTORY_DELETED_AT AS INVOICE_SCHEDULE_HISTORY_DELETED_AT
FROM INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1
JOIN INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1
ON INVOICE_SCHEDULE_STUDENT_TABLE_FORMATTED_V1.INVOICE_SCHEDULE_HISTORY_ID = INVOICE_SCHEDULE_HISTORY_TABLE_FORMATTED_V1.KEY;


CREATE SINK CONNECTOR IF NOT EXISTS SINK_INVOICE_SCHEDULE_STUDENT_PUBLIC_INFO_V1 WITH (
      'connector.class'='io.confluent.connect.jdbc.JdbcSinkConnector',
      'transforms.unwrap.delete.handling.mode'='drop',
      'tasks.max'='1',
      'topics'='{{ .Values.topicPrefix }}INVOICE_SCHEDULE_STUDENT_PUBLIC_INFO_V1',
      'fields.whitelist'='invoice_schedule_student_id,invoice_schedule_history_id,student_id,error_details,actual_error_details,invoice_schedule_student_created_at,invoice_schedule_student_updated_at,invoice_schedule_student_deleted_at,invoice_schedule_id,number_of_failed_invoices,total_students,execution_start_date,execution_end_date,invoice_schedule_history_created_at,invoice_schedule_history_updated_at,invoice_schedule_history_deleted_at',
      'key.converter'='org.apache.kafka.connect.storage.StringConverter',
      'value.converter'='io.confluent.connect.avro.AvroConverter',
      'value.converter.schema.registry.url'='{{ .Values.cpRegistryHost }}',
      'delete.enabled'='false',
      'transforms.unwrap.drop.tombstones'='true',
      'auto.create'='true',
      'connection.url'='${file:/decrypted/kafka-connect.secrets.properties:kec_url}',
      'insert.mode'='upsert',
      'table.name.format'='public.invoice_schedule_student',
      'pk.mode'='record_key',
      'transforms'='RenameField',
      'transforms.RenameField.type'= 'org.apache.kafka.connect.transforms.ReplaceField$Value',
      'transforms.RenameField.renames'='INVOICE_SCHEDULE_STUDENT_ID:invoice_schedule_student_id,INVOICE_SCHEDULE_HISTORY_ID:invoice_schedule_history_id,STUDENT_ID:student_id,ERROR_DETAILS:error_details,ACTUAL_ERROR_DETAILS:actual_error_details,INVOICE_SCHEDULE_STUDENT_CREATED_AT:invoice_schedule_student_created_at,INVOICE_SCHEDULE_STUDENT_UPDATED_AT:invoice_schedule_student_updated_at,INVOICE_SCHEDULE_STUDENT_DELETED_AT:invoice_schedule_student_deleted_at,INVOICE_SCHEDULE_ID:invoice_schedule_id,NUMBER_OF_FAILED_INVOICES:number_of_failed_invoices,TOTAL_STUDENTS:total_students,EXECUTION_START_DATE:execution_start_date,EXECUTION_END_DATE:execution_end_date,INVOICE_SCHEDULE_HISTORY_CREATED_AT:invoice_schedule_history_created_at,INVOICE_SCHEDULE_HISTORY_UPDATED_AT:invoice_schedule_history_updated_at,INVOICE_SCHEDULE_HISTORY_DELETED_AT:invoice_schedule_history_deleted_at',
      'pk.fields'='invoice_schedule_student_id'
);
