CREATE TABLE IF NOT EXISTS TIMESHEET_JOIN_OWH
AS SELECT
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.KEY AS KEY,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.OTHER_WORKING_HOURS_ID AS OTHER_WORKING_HOURS_ID,
    TIMESHEET_TIMESHEET_TABLE.KEY AS TIMESHEET_ID,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.TIMESHEET_CONFIG_ID AS TIMESHEET_CONFIG_ID,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.START_TIME AS START_TIME,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.END_TIME AS END_TIME,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.TOTAL_HOUR AS TOTAL_HOUR,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.REMARKS AS OTHER_WORKING_HOUR_REMARKS,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.CREATED_AT AS OTHER_WORKING_HOUR_CREATED_AT,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.UPDATED_AT AS OTHER_WORKING_HOUR_UPDATED_AT,
    TIMESHEET_OTHER_WORKING_HOURS_TABLE.DELETED_AT AS OTHER_WORKING_HOUR_DELETED_AT,
    TIMESHEET_TIMESHEET_TABLE.STAFF_ID AS STAFF_ID,
    TIMESHEET_TIMESHEET_TABLE.TIMESHEET_STATUS AS TIMESHEET_STATUS,
    TIMESHEET_TIMESHEET_TABLE.TIMESHEET_DATE AS TIMESHEET_DATE,
    TIMESHEET_TIMESHEET_TABLE.REMARK AS TIMESHEET_REMARK,
    TIMESHEET_TIMESHEET_TABLE.LOCATION_ID AS LOCATION_ID,
    TIMESHEET_TIMESHEET_TABLE.CREATED_AT AS TIMESHEET_CREATED_AT,
    TIMESHEET_TIMESHEET_TABLE.UPDATED_AT AS TIMESHEET_UPDATED_AT,
    TIMESHEET_TIMESHEET_TABLE.DELETED_AT AS TIMESHEET_DELETED_AT
FROM TIMESHEET_OTHER_WORKING_HOURS_TABLE
JOIN TIMESHEET_TIMESHEET_TABLE
ON TIMESHEET_OTHER_WORKING_HOURS_TABLE.TIMESHEET_ID = TIMESHEET_TIMESHEET_TABLE.KEY;


CREATE TABLE IF NOT EXISTS TS_OTHER_WORKING
AS SELECT
    TIMESHEET_JOIN_OWH.KEY AS ROWKEY,
    AS_VALUE(TIMESHEET_JOIN_OWH.KEY) AS OTHER_WORKING_HOURS_ID,
    TIMESHEET_JOIN_OWH.TIMESHEET_ID AS TIMESHEET_ID,
    TIMESHEET_TIMESHEET_CONFIG_TABLE.KEY AS TIMESHEET_CONFIG_ID,
    TIMESHEET_JOIN_OWH.START_TIME AS START_TIME,
    TIMESHEET_JOIN_OWH.END_TIME AS END_TIME,
    TIMESHEET_JOIN_OWH.TOTAL_HOUR AS TOTAL_HOUR,
    TIMESHEET_JOIN_OWH.OTHER_WORKING_HOUR_REMARKS AS OTHER_WORKING_HOUR_REMARKS,
    TIMESHEET_JOIN_OWH.OTHER_WORKING_HOUR_CREATED_AT AS OTHER_WORKING_HOUR_CREATED_AT,
    TIMESHEET_JOIN_OWH.OTHER_WORKING_HOUR_UPDATED_AT AS OTHER_WORKING_HOUR_UPDATED_AT,
    TIMESHEET_JOIN_OWH.OTHER_WORKING_HOUR_DELETED_AT AS OTHER_WORKING_HOUR_DELETED_AT,
    TIMESHEET_TIMESHEET_CONFIG_TABLE.CONFIG_TYPE AS CONFIG_TYPE,
    TIMESHEET_TIMESHEET_CONFIG_TABLE.CONFIG_VALUE AS CONFIG_VALUE,
    TIMESHEET_TIMESHEET_CONFIG_TABLE.CREATED_AT AS TIMESHEET_CONFIG_CREATED_AT,
    TIMESHEET_TIMESHEET_CONFIG_TABLE.UPDATED_AT AS TIMESHEET_CONFIG_UPDATED_AT,
    TIMESHEET_TIMESHEET_CONFIG_TABLE.DELETED_AT AS TIMESHEET_CONFIG_DELETED_AT,
    TIMESHEET_JOIN_OWH.STAFF_ID AS STAFF_ID,
    TIMESHEET_JOIN_OWH.TIMESHEET_STATUS AS TIMESHEET_STATUS,
    TIMESHEET_JOIN_OWH.TIMESHEET_DATE AS TIMESHEET_DATE,
    TIMESHEET_JOIN_OWH.timesheet_remark AS TIMESHEET_REMARK,
    TIMESHEET_JOIN_OWH.LOCATION_ID AS LOCATION_ID,
    TIMESHEET_JOIN_OWH.TIMESHEET_CREATED_AT AS TIMESHEET_CREATED_AT,
    TIMESHEET_JOIN_OWH.TIMESHEET_UPDATED_AT AS TIMESHEET_UPDATED_AT,
    TIMESHEET_JOIN_OWH.TIMESHEET_DELETED_AT AS TIMESHEET_DELETED_AT
FROM TIMESHEET_JOIN_OWH
JOIN TIMESHEET_TIMESHEET_CONFIG_TABLE 
ON TIMESHEET_JOIN_OWH.TIMESHEET_CONFIG_ID = TIMESHEET_TIMESHEET_CONFIG_TABLE.KEY;

CREATE TABLE IF NOT EXISTS AUTO_CREATE_FLAG_ACTIVITY_LOG
AS SELECT
    TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE.KEY AS AUTO_CREATE_FLAG_ACTIVITY_LOG_ID,
    TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE.STAFF_ID AS STAFF_ID,
    TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE.CHANGE_TIME AS CHANGE_TIME,
    TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE.FLAG_ON AS FLAG_ON,
    TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE.CREATED_AT AS CREATED_AT,
    TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE.UPDATED_AT AS UPDATED_AT,
    TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE.DELETED_AT AS DELETED_AT
FROM TIMESHEET_AUTO_CREATE_FLAG_ACTIVITY_LOG_TABLE;