SET 'auto.offset.reset' = 'earliest';
CREATE STREAM IF NOT EXISTS STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1 WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.bob.student_enrollment_status_history', value_format='AVRO');
CREATE STREAM IF NOT EXISTS STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1
    AS SELECT
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->STUDENT_ID AS STUDENT_ID,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->LOCATION_ID AS LOCATION_ID,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->ENROLLMENT_STATUS AS ENROLLMENT_STATUS,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->START_DATE AS START_DATE,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->END_DATE AS END_DATE,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->COMMENT AS COMMENT,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS CREATED_AT,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS UPDATED_AT,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->DELETED_AT AS DELETED_AT,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->ORDER_ID AS ORDER_ID,
        STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->ORDER_SEQUENCE_NUMBER AS ORDER_SEQUENCE_NUMBER

    FROM STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1
    WHERE STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}';

CREATE STREAM IF NOT EXISTS STUDENT_ENROLLMENT_STATUS_HISTORY_PUBLIC_INFO_V1 
AS SELECT
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.STUDENT_ID AS STUDENT_ID,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.LOCATION_ID AS LOCATION_ID,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.ENROLLMENT_STATUS AS ENROLLMENT_STATUS,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.START_DATE AS START_DATE,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.END_DATE AS END_DATE,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.COMMENT AS COMMENT,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.CREATED_AT AS CREATED_AT,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.UPDATED_AT AS UPDATED_AT,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.DELETED_AT AS DELETED_AT,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.ORDER_ID AS ORDER_ID,
    STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1.ORDER_SEQUENCE_NUMBER AS ORDER_SEQUENCE_NUMBER

FROM STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1;

CREATE SINK CONNECTOR IF NOT EXISTS STUDENT_ENROLLMENT_STATUS_HISTORY_STREAM_FORMATED_V1 WITH (
      'connector.class'='io.confluent.connect.jdbc.JdbcSinkConnector',
      'transforms.unwrap.delete.handling.mode'='drop',
      'tasks.max'='1',
      'topics'='{{ .Values.topicPrefix }}STUDENT_ENROLLMENT_STATUS_HISTORY_PUBLIC_INFO_V1',
      'fields.whitelist'='student_id,location_id,enrollment_status,start_date,end_date,comment,created_at,updated_at,deleted_at,order_id,order_sequence_number',
      'key.converter'='org.apache.kafka.connect.storage.StringConverter',
      'value.converter'='io.confluent.connect.avro.AvroConverter',
      'value.converter.schema.registry.url'='{{ .Values.cpRegistryHost }}',
      'delete.enabled'='false',
      'transforms.unwrap.drop.tombstones'='true',
      'auto.create'='true',
      'connection.url'='${file:/decrypted/kafka-connect.secrets.properties:kec_url}',
      'insert.mode'='upsert',
      'table.name.format'='bob.student_enrollment_status_history_public_info',
      'pk.mode'='record_value',
      'transforms'='RenameField',
      'transforms.RenameField.type'= 'org.apache.kafka.connect.transforms.ReplaceField$Value',
      'transforms.RenameField.renames'='STUDENT_ID:student_id,LOCATION_ID:location_id,ENROLLMENT_STATUS:enrollment_status,START_DATE:start_date,END_DATE:end_date,COMMENT:comment,CREATED_AT:created_at,UPDATED_AT:updated_at,DELETED_AT:deleted_at,ORDER_ID:order_id,ORDER_SEQUENCE_NUMBER:order_sequence_number',
      'pk.fields'='student_id,location_id,enrollment_status,start_date'
);