SET 'auto.offset.reset' = 'earliest';

CREATE STREAM IF NOT EXISTS BANK_ACCOUNT_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.invoicemgmt.bank_account', value_format='AVRO');

CREATE STREAM IF NOT EXISTS BANK_ACCOUNT_STREAM_FORMATTED_V1
    AS SELECT
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_ACCOUNT_ID AS KEY,
        AS_VALUE(BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_ACCOUNT_ID) AS BANK_ACCOUNT_ID,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->STUDENT_PAYMENT_DETAIL_ID AS STUDENT_PAYMENT_DETAIL_ID,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->STUDENT_ID AS STUDENT_ID,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->IS_VERIFIED AS IS_VERIFIED,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_BRANCH_ID AS BANK_BRANCH_ID,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_ACCOUNT_NUMBER AS BANK_ACCOUNT_NUMBER,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_ACCOUNT_HOLDER AS BANK_ACCOUNT_HOLDER,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_ACCOUNT_TYPE AS BANK_ACCOUNT_TYPE,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_ID AS BANK_ID,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS BANK_ACCOUNT_CREATED_AT,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS BANK_ACCOUNT_UPDATED_AT,
        BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->DELETED_AT AS BANK_ACCOUNT_DELETED_AT
    FROM BANK_ACCOUNT_STREAM_ORIGIN_V1
    WHERE BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY BANK_ACCOUNT_STREAM_ORIGIN_V1.AFTER->BANK_ACCOUNT_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS BANK_ACCOUNT_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}BANK_ACCOUNT_STREAM_FORMATTED_V1', value_format='AVRO');

CREATE TABLE IF NOT EXISTS BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1
AS SELECT
    BANK_ACCOUNT_TABLE_FORMATTED_V1.KEY as ROW_KEY,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ACCOUNT_ID as BANK_ACCOUNT_ID,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.STUDENT_PAYMENT_DETAIL_ID as STUDENT_PAYMENT_DETAIL_ID,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.STUDENT_ID AS STUDENT_ID,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.IS_VERIFIED AS IS_VERIFIED,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_BRANCH_ID AS BANK_BRANCH_ID,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ACCOUNT_NUMBER AS BANK_ACCOUNT_NUMBER,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ACCOUNT_HOLDER AS BANK_ACCOUNT_HOLDER,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ACCOUNT_TYPE AS BANK_ACCOUNT_TYPE,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ID AS BANK_ID,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ACCOUNT_CREATED_AT AS BANK_ACCOUNT_CREATED_AT,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ACCOUNT_UPDATED_AT AS BANK_ACCOUNT_UPDATED_AT,
    BANK_ACCOUNT_TABLE_FORMATTED_V1.BANK_ACCOUNT_DELETED_AT AS BANK_ACCOUNT_DELETED_AT,
    STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2.PAYER_NAME AS PAYER_NAME,
    STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2.PAYER_PHONE_NUMBER AS PAYER_PHONE_NUMBER,
    STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2.PAYMENT_METHOD AS PAYMENT_METHOD,
    STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2.STUDENT_PAYMENT_DETAIL_CREATED_AT AS STUDENT_PAYMENT_DETAIL_CREATED_AT,
    STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2.STUDENT_PAYMENT_DETAIL_UPDATED_AT AS STUDENT_PAYMENT_DETAIL_UPDATED_AT,
    STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2.STUDENT_PAYMENT_DETAIL_DELETED_AT AS STUDENT_PAYMENT_DETAIL_DELETED_AT
FROM BANK_ACCOUNT_TABLE_FORMATTED_V1
JOIN STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2
    ON BANK_ACCOUNT_TABLE_FORMATTED_V1.STUDENT_PAYMENT_DETAIL_ID = STUDENT_PAYMENT_DETAIL_TABLE_FORMATTED_V2.KEY;

CREATE TABLE IF NOT EXISTS BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_AND_BANK_V1
AS SELECT
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.ROW_KEY as ROW_KEY,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ACCOUNT_ID as BANK_ACCOUNT_ID,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.STUDENT_PAYMENT_DETAIL_ID as STUDENT_PAYMENT_DETAIL_ID,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.STUDENT_ID AS STUDENT_ID,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.IS_VERIFIED AS IS_VERIFIED,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_BRANCH_ID AS BANK_BRANCH_ID,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ACCOUNT_NUMBER AS BANK_ACCOUNT_NUMBER,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ACCOUNT_HOLDER AS BANK_ACCOUNT_HOLDER,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ACCOUNT_TYPE AS BANK_ACCOUNT_TYPE,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ID AS BANK_ID,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ACCOUNT_CREATED_AT AS BANK_ACCOUNT_CREATED_AT,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ACCOUNT_UPDATED_AT AS BANK_ACCOUNT_UPDATED_AT,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ACCOUNT_DELETED_AT AS BANK_ACCOUNT_DELETED_AT,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.PAYER_NAME AS PAYER_NAME,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.PAYER_PHONE_NUMBER AS PAYER_PHONE_NUMBER,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.PAYMENT_METHOD AS PAYMENT_METHOD,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.STUDENT_PAYMENT_DETAIL_CREATED_AT AS STUDENT_PAYMENT_DETAIL_CREATED_AT,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.STUDENT_PAYMENT_DETAIL_UPDATED_AT AS STUDENT_PAYMENT_DETAIL_UPDATED_AT,
    BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.STUDENT_PAYMENT_DETAIL_DELETED_AT AS STUDENT_PAYMENT_DETAIL_DELETED_AT,
    BANK_TABLE_FORMATTED_V1.BANK_CODE AS BANK_CODE,
    BANK_TABLE_FORMATTED_V1.BANK_NAME AS BANK_NAME,
    BANK_TABLE_FORMATTED_V1.BANK_NAME_PHONETIC AS BANK_NAME_PHONETIC,
    BANK_TABLE_FORMATTED_V1.BANK_IS_ARCHIVED AS BANK_IS_ARCHIVED,
    BANK_TABLE_FORMATTED_V1.BANK_CREATED_AT AS BANK_CREATED_AT,
    BANK_TABLE_FORMATTED_V1.BANK_UPDATED_AT AS BANK_UPDATED_AT,
    BANK_TABLE_FORMATTED_V1.BANK_DELETED_AT AS BANK_DELETED_AT
FROM BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1
JOIN BANK_TABLE_FORMATTED_V1
    ON BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_V1.BANK_ID = BANK_TABLE_FORMATTED_V1.KEY;

CREATE SINK CONNECTOR IF NOT EXISTS SINK_BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_AND_BANK_V1 WITH (
      'connector.class'='io.confluent.connect.jdbc.JdbcSinkConnector',
      'transforms.unwrap.delete.handling.mode'='drop',
      'tasks.max'='1',
      'topics'='{{ .Values.topicPrefix }}BANK_ACCOUNT_WITH_STUDENT_PAYMENT_DETAIL_AND_BANK_V1',
      'fields.whitelist'='bank_account_id,student_payment_detail_id,student_id,is_verified,bank_branch_id,bank_account_number,bank_account_holder,bank_account_type,bank_id,bank_account_created_at,bank_account_updated_at,bank_account_deleted_at,payer_name,payer_phone_number,payment_method,student_payment_detail_created_at,student_payment_detail_updated_at,student_payment_detail_deleted_at,bank_code,bank_name,bank_name_phonetic,bank_is_archived,bank_created_at,bank_updated_at,bank_deleted_at',
      'key.converter'='org.apache.kafka.connect.storage.StringConverter',
      'value.converter'='io.confluent.connect.avro.AvroConverter',
      'value.converter.schema.registry.url'='{{ .Values.cpRegistryHost }}',
      'delete.enabled'='false',
      'transforms.unwrap.drop.tombstones'='true',
      'auto.create'='true',
      'connection.url'='${file:/decrypted/kafka-connect.secrets.properties:kec_url}',
      'insert.mode'='upsert',
      'table.name.format'='public.bank_account',
      'pk.mode'='record_value',
      'transforms'='RenameField',
      'transforms.RenameField.type'= 'org.apache.kafka.connect.transforms.ReplaceField$Value',
      'transforms.RenameField.renames'='BANK_ACCOUNT_ID:bank_account_id,STUDENT_PAYMENT_DETAIL_ID:student_payment_detail_id,STUDENT_ID:student_id,IS_VERIFIED:is_verified,BANK_BRANCH_ID:bank_branch_id,BANK_ACCOUNT_NUMBER:bank_account_number,BANK_ACCOUNT_HOLDER:bank_account_holder,BANK_ACCOUNT_TYPE:bank_account_type,BANK_ID:bank_id,BANK_ACCOUNT_CREATED_AT:bank_account_created_at,BANK_ACCOUNT_UPDATED_AT:bank_account_updated_at,BANK_ACCOUNT_DELETED_AT:bank_account_deleted_at,PAYER_NAME:payer_name,PAYER_PHONE_NUMBER:payer_phone_number,PAYMENT_METHOD:payment_method,STUDENT_PAYMENT_DETAIL_CREATED_AT:student_payment_detail_created_at,STUDENT_PAYMENT_DETAIL_UPDATED_AT:student_payment_detail_updated_at,STUDENT_PAYMENT_DETAIL_DELETED_AT:student_payment_detail_deleted_at,BANK_CODE:bank_code,BANK_NAME:bank_name,BANK_NAME_PHONETIC:bank_name_phonetic,BANK_IS_ARCHIVED:bank_is_archived,BANK_CREATED_AT:bank_created_at,BANK_UPDATED_AT:bank_updated_at,BANK_DELETED_AT:bank_deleted_at',
      'pk.fields'='bank_account_id'
);
