SET 'auto.offset.reset' = 'earliest';

CREATE STREAM IF NOT EXISTS PARTNER_BANK_STREAM_ORIGIN_V1  WITH (kafka_topic='{{ .Values.global.environment }}.kec.datalake.invoicemgmt.partner_bank', value_format='AVRO');

CREATE STREAM IF NOT EXISTS PARTNER_BANK_STREAM_FORMATTED_V1
    AS SELECT
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->PARTNER_BANK_ID AS KEY,
        AS_VALUE(PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->PARTNER_BANK_ID) AS PARTNER_BANK_ID,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->BANK_NUMBER AS PARTNER_BANK_BANK_NUMBER,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->BANK_NAME AS PARTNER_BANK_BANK_NAME,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->BANK_BRANCH_NUMBER AS PARTNER_BANK_BANK_BRANCH_NUMBER,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->BANK_BRANCH_NAME AS PARTNER_BANK_BANK_BRANCH_NAME,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->DEPOSIT_ITEMS AS DEPOSIT_ITEMS,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->CONSIGNOR_CODE AS CONSIGNOR_CODE,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->CONSIGNOR_NAME AS CONSIGNOR_NAME,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->IS_DEFAULT AS IS_DEFAULT,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->RECORD_LIMIT AS RECORD_LIMIT,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->REMARKS AS PARTNER_BANK_REMARKS,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->IS_ARCHIVED AS PARTNER_BANK_IS_ARCHIVED,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->CREATED_AT AS PARTNER_BANK_CREATED_AT,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->UPDATED_AT AS PARTNER_BANK_UPDATED_AT,
        PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->DELETED_AT AS PARTNER_BANK_DELETED_AT
    FROM PARTNER_BANK_STREAM_ORIGIN_V1
    WHERE PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->RESOURCE_PATH = '{{ .Values.kecResourcePath }}'
    PARTITION BY PARTNER_BANK_STREAM_ORIGIN_V1.AFTER->PARTNER_BANK_ID
    EMIT CHANGES;

CREATE TABLE IF NOT EXISTS PARTNER_BANK_TABLE_FORMATTED_V1 (KEY VARCHAR PRIMARY KEY) with (kafka_topic='{{ .Values.topicPrefix }}PARTNER_BANK_STREAM_FORMATTED_V1', value_format='AVRO');
