CREATE TABLE IF NOT EXISTS AUTO_CREATE_TIMESHEET_FLAG
AS SELECT
    TIMESHEET_AUTO_CREATE_TIMESHEET_FLAG_TABLE.KEY AS STAFF_ID,
    TIMESHEET_AUTO_CREATE_TIMESHEET_FLAG_TABLE.FLAG_ON AS FLAG_ON,
    TIMESHEET_AUTO_CREATE_TIMESHEET_FLAG_TABLE.CREATED_AT AS CREATED_AT,
    TIMESHEET_AUTO_CREATE_TIMESHEET_FLAG_TABLE.UPDATED_AT AS UPDATED_AT,
    TIMESHEET_AUTO_CREATE_TIMESHEET_FLAG_TABLE.DELETED_AT AS DELETED_AT
FROM TIMESHEET_AUTO_CREATE_TIMESHEET_FLAG_TABLE;

CREATE TABLE IF NOT EXISTS TIMESHEET_CONFIRMATION_CUT_OFF_DATE
AS SELECT
    TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE.KEY AS TIMESHEET_CONFIRMATION_CUT_OFF_DATE_ID,
    TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE.CUT_OFF_DATE AS CUT_OFF_DATE,
    TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE.START_DATE AS START_DATE,
    TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE.END_DATE AS END_DATE,
    TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE.CREATED_AT AS CREATED_AT,
    TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE.UPDATED_AT AS UPDATED_AT,
    TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE.DELETED_AT AS DELETED_AT
FROM TIMESHEET_TIMESHEET_CONFIRMATION_CUT_OFF_DATE_TABLE;

CREATE TABLE IF NOT EXISTS TIMESHEET_CONFIRMATION_INFO
AS SELECT
    TIMESHEET_TIMESHEET_CONFIRMATION_INFO_TABLE.KEY AS TIMESHEET_CONFIRMATION_INFO_ID,
    TIMESHEET_TIMESHEET_CONFIRMATION_INFO_TABLE.PERIOD_ID AS PERIOD_ID,
    TIMESHEET_TIMESHEET_CONFIRMATION_INFO_TABLE.LOCATION_ID AS LOCATION_ID,
    TIMESHEET_TIMESHEET_CONFIRMATION_INFO_TABLE.CREATED_AT AS CREATED_AT,
    TIMESHEET_TIMESHEET_CONFIRMATION_INFO_TABLE.UPDATED_AT AS UPDATED_AT,
    TIMESHEET_TIMESHEET_CONFIRMATION_INFO_TABLE.DELETED_AT AS DELETED_AT
FROM TIMESHEET_TIMESHEET_CONFIRMATION_INFO_TABLE;

CREATE TABLE IF NOT EXISTS TIMESHEET_CONFIRMATION_PERIOD
AS SELECT
    TIMESHEET_TIMESHEET_CONFIRMATION_PERIOD_TABLE.KEY AS TIMESHEET_CONFIRMATION_PERIOD_ID,
    TIMESHEET_TIMESHEET_CONFIRMATION_PERIOD_TABLE.START_DATE AS START_DATE,
    TIMESHEET_TIMESHEET_CONFIRMATION_PERIOD_TABLE.END_DATE AS END_DATE,
    TIMESHEET_TIMESHEET_CONFIRMATION_PERIOD_TABLE.CREATED_AT AS CREATED_AT,
    TIMESHEET_TIMESHEET_CONFIRMATION_PERIOD_TABLE.UPDATED_AT AS UPDATED_AT,
    TIMESHEET_TIMESHEET_CONFIRMATION_PERIOD_TABLE.DELETED_AT AS DELETED_AT
FROM TIMESHEET_TIMESHEET_CONFIRMATION_PERIOD_TABLE;