CREATE TABLE IF NOT EXISTS TS_TRANSPORTATION
AS SELECT
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.KEY AS TRANSPORTATION_EXPENSE_ID,
    TIMESHEET_TIMESHEET_TABLE.KEY AS TIMESHEET_ID,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.TRANSPORTATION_TYPE AS TRANSPORTATION_TYPE,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.TRANSPORTATION_FROM AS TRANSPORTATION_FROM,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.TRANSPORTATION_TO AS TRANSPORTATION_TO,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.COST_AMOUNT AS COST_AMOUNT,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.ROUND_TRIP AS ROUND_TRIP,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.REMARKS AS TRANSPORTATION_EXPENSE_REMARKS,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.CREATED_AT AS TRANSPORTATION_EXPENSE_CREATED_AT,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.UPDATED_AT AS TRANSPORTATION_EXPENSE_UPDATED_AT,
    TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.DELETED_AT AS TRANSPORTATION_EXPENSE_DELETED_AT,
    TIMESHEET_TIMESHEET_TABLE.TIMESHEET_STATUS AS TIMESHEET_STATUS,
    TIMESHEET_TIMESHEET_TABLE.TIMESHEET_DATE AS TIMESHEET_DATE,
    TIMESHEET_TIMESHEET_TABLE.REMARK AS TIMESHEET_REMARK,
    TIMESHEET_TIMESHEET_TABLE.CREATED_AT AS TIMESHEET_CREATED_AT,
    TIMESHEET_TIMESHEET_TABLE.UPDATED_AT AS TIMESHEET_UPDATED_AT,
    TIMESHEET_TIMESHEET_TABLE.DELETED_AT AS TIMESHEET_DELETED_AT,
    TIMESHEET_TIMESHEET_TABLE.STAFF_ID AS STAFF_ID
FROM TIMESHEET_TRANSPORTATION_EXPENSE_TABLE
JOIN TIMESHEET_TIMESHEET_TABLE 
ON TIMESHEET_TRANSPORTATION_EXPENSE_TABLE.TIMESHEET_ID = TIMESHEET_TIMESHEET_TABLE.KEY;

CREATE TABLE IF NOT EXISTS STAFF_TRANSPORTATION_EXPENSE
AS SELECT
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.KEY AS STAFF_TRANSPORTATION_EXPENSE_ID,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.STAFF_ID AS STAFF_ID,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.LOCATION_ID AS LOCATION_ID,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.TRANSPORTATION_TYPE AS TRANSPORT_TYPE,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.TRANSPORTATION_FROM AS TRANSPORTATION_FROM,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.TRANSPORTATION_TO AS TRANSPORTATION_TO,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.COST_AMOUNT AS COST_AMOUNT,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.ROUND_TRIP AS ROUND_TRIP,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.REMARKS AS REMARKS,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.CREATED_AT AS CREATED_AT,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.UPDATED_AT AS UPDATED_AT,
    TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE.DELETED_AT AS DELETED_AT
FROM TIMESHEET_STAFF_TRANSPORTATION_EXPENSE_TABLE;

