// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
	"github.com/manabie-com/backend/internal/payment/entities"
)

type MockOrderItemRepo struct {
	mock.Mock
}

func (r *MockOrderItemRepo) CountOrderItemsByOrderID(arg1 context.Context, arg2 database.QueryExecer, arg3 string) (int, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(int), args.Error(1)
}

func (r *MockOrderItemRepo) Create(arg1 context.Context, arg2 database.QueryExecer, arg3 entities.OrderItem) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}

func (r *MockOrderItemRepo) GetAllByOrderID(arg1 context.Context, arg2 database.QueryExecer, arg3 string) ([]*entities.OrderItem, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entities.OrderItem), args.Error(1)
}

func (r *MockOrderItemRepo) GetOrderItemByStudentProductID(arg1 context.Context, arg2 database.QueryExecer, arg3 string) (entities.OrderItem, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(entities.OrderItem), args.Error(1)
}

func (r *MockOrderItemRepo) GetOrderItemsByOrderIDWithPaging(arg1 context.Context, arg2 database.QueryExecer, arg3 string, arg4 int64, arg5 int64) ([]entities.OrderItem, error) {
	args := r.Called(arg1, arg2, arg3, arg4, arg5)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.OrderItem), args.Error(1)
}

func (r *MockOrderItemRepo) GetOrderItemsByOrderIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 []string) ([]entities.OrderItem, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.OrderItem), args.Error(1)
}

func (r *MockOrderItemRepo) GetOrderItemsByProductIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 []string) ([]entities.OrderItem, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.OrderItem), args.Error(1)
}

func (r *MockOrderItemRepo) GetStudentProductIDsForVoidOrderByOrderID(arg1 context.Context, arg2 database.QueryExecer, arg3 string) ([]string, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]string), args.Error(1)
}
