// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/jackc/pgtype"
	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/golibs/database"
)

type MockCourseClassRepo struct {
	mock.Mock
}

func (r *MockCourseClassRepo) Find(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.Int4Array) (map[pgtype.Int4]pgtype.TextArray, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(map[pgtype.Int4]pgtype.TextArray), args.Error(1)
}

func (r *MockCourseClassRepo) FindByCourseIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray) (map[pgtype.Text]pgtype.Int4Array, error) {
	args := r.Called(arg1, arg2, arg3)
	return args.Get(0).(map[pgtype.Text]pgtype.Int4Array), args.Error(1)
}

func (r *MockCourseClassRepo) FindClassInCourse(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.TextArray, arg4 pgtype.Int4Array) (map[pgtype.Text]pgtype.Int4Array, error) {
	args := r.Called(arg1, arg2, arg3, arg4)
	return args.Get(0).(map[pgtype.Text]pgtype.Int4Array), args.Error(1)
}
