// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/jackc/pgtype"
	"github.com/stretchr/testify/mock"

	"github.com/manabie-com/backend/internal/bob/entities"
	"github.com/manabie-com/backend/internal/golibs/database"
)

type MockStudentSubscriptionAccessPathRepo struct {
	mock.Mock
}

func (r *MockStudentSubscriptionAccessPathRepo) DeleteByStudentSubscriptionID(arg1 context.Context, arg2 database.QueryExecer, arg3 pgtype.Text) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}

func (r *MockStudentSubscriptionAccessPathRepo) FindStudentSubscriptionIDsByLocationIDs(arg1 context.Context, arg2 database.QueryExecer, arg3 []string) ([]string, error) {
	args := r.Called(arg1, arg2, arg3)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]string), args.Error(1)
}

func (r *MockStudentSubscriptionAccessPathRepo) Upsert(arg1 context.Context, arg2 database.Ext, arg3 []*entities.StudentSubscriptionAccessPath) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}
